import type { FacetView } from "@kohaku-ui/intents";
import type { JsonObject } from "@kohaku-ui/spec-core";
import facetViewsData from "../generated/facet-views.json";
import type { Lang } from "../i18n/lang.js";

/**
 * The views selectable on the dashboard (= normalized Intents) and their facet descriptors.
 * The single source is sample-api's INTENT_DEFINITIONS; this data-imports the facet-views.json generated by
 * `pnpm intents:emit`.
 * Facet operations merge into normalized Intents as GuiActions (to the same Composition Service as natural language).
 */
export const FACET_VIEWS = facetViewsData.views as FacetView[];

/** The default view (initial display when the URL has no intent specified). */
export const DEFAULT_VIEW: FacetView = FACET_VIEWS[0]!;

/**
 * Picks the display label for the current language: the locale overlay (labels.ja etc., emitted by
 * the bilingual intent definitions) when present, otherwise the canonical (English) label.
 */
export function facetLabel(entry: { label: string; labels?: Record<string, string> }, lang: Lang): string {
  return entry.labels?.[lang] ?? entry.label;
}

/**
 * The single implementation of client-side coerce for facet values. valueType is derived from Zod's coerce and baked into
 * facet-views.json, so by definition it matches the server's normalizeParams (z.coerce.number)
 * (unifies the two former implementations: FacetPanel.coerce and DashboardPage's `/^\d+$/`).
 */
export function coerceFacetValue(valueType: "number" | "string", value: string): string | number {
  return valueType === "number" ? Number(value) : value;
}

/** param key → valueType (the union across all views). Used for coerce when restoring from the URL. */
const valueTypeByKey: Record<string, "number" | "string"> = {};
for (const view of FACET_VIEWS) {
  for (const facet of view.facets) {
    valueTypeByKey[facet.key] = facet.valueType;
  }
}

/**
 * URL query → Intent params. Coerces using the facet's valueType. Keys not declared as facets
 * (e.g. the detail limit) are passed through as strings, and the server's normalizeParams ultimately coerces + defaults them
 * (client coerce is a safety net; server validation is authoritative).
 */
export function parseFacetParams(searchParams: URLSearchParams): JsonObject {
  const params: JsonObject = {};
  for (const [key, value] of searchParams.entries()) {
    if (key === "intent") continue;
    params[key] = coerceFacetValue(valueTypeByKey[key] ?? "string", value);
  }
  return params;
}
