"""Design-kit tests (mirror of packages/composer/test/design-kit.test.ts and design-kit-lint.test.ts).

_EXPECTED_KIT_FRAGMENT below is read from the cross-language golden fixture generated by
spec/scripts/generate-cross-language-fixtures.ts (spec/test/fixtures/cross-language-canonical.json's
promptFragments.designKit; also asserted directly against DEFAULT_KIT_VOCABULARY in
test_cross_language_golden.py). Change the TS constants and regenerate the fixture; do not hand-edit this
value, and do not hand-copy it into another test — that is exactly the duplication this fixture replaces.
"""

from __future__ import annotations

import asyncio
from typing import Any

from kohaku.composer import (
    DEFAULT_KIT_SKELETON,
    DEFAULT_KIT_VOCABULARY,
    L2_SYSTEM_PROMPT,
    ComposeContext,
    ComposePolicy,
    DesignKitVocabulary,
    DesignSystemGuide,
    IntentComposeInput,
    compose,
    design_kit_prompt_fragment,
)
from kohaku.composer.l2_lint import collect_l2_issues, collect_unknown_kit_classes
from kohaku.composer.prompt import build_l2_prompt
from kohaku.llm import FakeLlm
from kohaku.registry import core_catalog, resolve_catalog
from kohaku.spec import Intent, IntentInput, compute_intent_hash
from kohaku.storage import FileStoragePort

from ..conftest import load_cross_language_fixture
from .test_compose import _REF, _FakeSemantic

_CATALOG = resolve_catalog(core_catalog())

_EXPECTED_KIT_FRAGMENT: str = load_cross_language_fixture()["promptFragments"]["designKit"]


def _widget(body: str, script: str = "") -> str:
    return (
        "<!DOCTYPE html><html><head><title>Custom</title><style>.chart-container{width:100%}</style></head>"
        f"<body>{body}<script>window.kohaku.fetchData('{_REF}').then(function(d){{{script}window.kohaku.ready();}});"
        "</script></body></html>"
    )


_KIT_HTML = _widget(
    '<div class="k-card"><div class="k-card-title">Sales</div><div class="k-grid k-grid-3 gap-4">'
    '<div class="k-kpi"><span class="k-kpi-delta is-up">▲ 3%</span></div></div>'
    '<table class="k-table"><tr><th class="k-num">Sales</th></tr></table><div class="chart-container grid-container"></div></div>',
    'var el=document.createElement("div");el.className="k-notice k-notice-info mt-4";el.classList.add("text-muted","hidden");',
)
_UNKNOWN_HTML = _widget(
    '<div class="k-panel p-4 text-gray-700"><span class="k-kpi-value">1</span></div>',
    'var el=document.createElement("div");el.className="k-tile";el.classList.add("rounded-xl");',
)
_INTENT_INPUT = IntentComposeInput(intent=IntentInput(canonical="sales.summary", params={"fy": 2026}))


class TestVocabularyAndFragment:
    def test_counts(self) -> None:
        """48 classes, 134 utilities, 28 namespaces (every reserved margin/padding/sizing prefix in
        `namespaces` now has at least one utility behind it — see the design-kit-contract test)."""
        assert len(DEFAULT_KIT_VOCABULARY.classes) == 48
        assert len(DEFAULT_KIT_VOCABULARY.utilities) == 134
        assert len(DEFAULT_KIT_VOCABULARY.namespaces) == 28

    def test_id_and_version(self) -> None:
        assert DEFAULT_KIT_VOCABULARY.id == "kohaku"
        assert DEFAULT_KIT_VOCABULARY.version == "1"
        assert "k-" in DEFAULT_KIT_VOCABULARY.namespaces
        assert "gap-" in DEFAULT_KIT_VOCABULARY.namespaces
        assert "grid-cols-3" in DEFAULT_KIT_VOCABULARY.utilities
        assert "k-card" in DEFAULT_KIT_VOCABULARY.classes

    def test_skeleton_uses_only_vocabulary_classes_and_is_a_body_fragment(self) -> None:
        import re

        known = set(DEFAULT_KIT_VOCABULARY.classes) | set(DEFAULT_KIT_VOCABULARY.utilities) | {
            "is-up",
            "is-down",
        }
        for m in re.finditer(r'class="([^"]*)"', DEFAULT_KIT_SKELETON):
            for cls in m.group(1).split():
                assert cls in known, cls
        assert "<html" not in DEFAULT_KIT_SKELETON
        assert "<script" not in DEFAULT_KIT_SKELETON

    def test_golden_fragment(self) -> None:
        assert design_kit_prompt_fragment(DEFAULT_KIT_VOCABULARY) == _EXPECTED_KIT_FRAGMENT

    def test_custom_kit_insertion_order_and_skeleton(self) -> None:
        custom = DesignKitVocabulary(
            id="acme",
            version="3",
            classes={"k-tile": "tile"},
            utilities=("flex",),
            namespaces=("k-",),
            skeleton='<div class="k-tile">x</div>',
        )
        fragment = design_kit_prompt_fragment(custom)
        assert fragment.split("\n")[0] == "## Design kit (acme v3)"
        assert "  - k-tile: tile" in fragment
        assert (
            "- Utilities (exactly these names exist; any other utility name has no effect): flex" in fragment
        )
        assert '  <div class="k-tile">x</div>' in fragment
        assert "Sales by region" not in fragment

    def test_classes_sorted_by_name_not_insertion_order(self) -> None:
        """m-15: mirrors the TS sibling test. Python dict iteration is insertion order, so this is the
        side of the cross-language pair that would silently pass even with no sort at all if "2col" were
        not included — "2col" only diverges from TS (which special-cases integer-like keys ahead of every
        non-numeric one, sorted-or-not) once both languages actually sort by name."""
        fragment = design_kit_prompt_fragment(
            DesignKitVocabulary(
                id="custom",
                version="1",
                classes={"zebra": "z", "2col": "two columns", "alpha": "a"},
                utilities=(),
                namespaces=(),
            )
        )
        class_lines = [line for line in fragment.split("\n") if line.startswith("  - ")]
        assert class_lines == ["  - 2col: two columns", "  - alpha: a", "  - zebra: z"]

    def test_empty_sections_omitted_entirely(self) -> None:
        """m-14: an empty classes/utilities/namespaces section is omitted (heading included), not left
        dangling on a colon."""
        fragment = design_kit_prompt_fragment(
            DesignKitVocabulary(id="empty", version="1", classes={}, utilities=(), namespaces=())
        )
        assert "Kit classes" not in fragment
        assert "Component classes" not in fragment
        assert "Utilities (" not in fragment
        assert "Reserved prefixes" not in fragment
        for line in fragment.split("\n"):
            assert not line.rstrip().endswith(":")

    def test_no_skeleton_without_explicit_one_on_a_non_built_in_kit(self) -> None:
        """m-14: without an explicit skeleton, a non-built-in kit gets no Skeleton section at all — never
        the built-in k-* skeleton, which uses classes this kit does not define."""
        fragment = design_kit_prompt_fragment(
            DesignKitVocabulary(id="empty", version="1", classes={}, utilities=(), namespaces=())
        )
        assert "Skeleton of a well-formed widget body" not in fragment
        assert "k-card" not in fragment
        assert "Sales by region" not in fragment

    def test_explicit_skeleton_still_honored(self) -> None:
        fragment = design_kit_prompt_fragment(
            DesignKitVocabulary(
                id="empty",
                version="1",
                classes={},
                utilities=(),
                namespaces=(),
                skeleton="<div>ok</div>",
            )
        )
        assert "Skeleton of a well-formed widget body" in fragment
        assert "  <div>ok</div>" in fragment

    def test_structural_copy_of_default_kit_still_shows_the_skeleton(self) -> None:
        """m-14, revised in review: design_kit_prompt_fragment no longer special-cases
        DEFAULT_KIT_VOCABULARY by reference identity (an earlier version did, and broke silently whenever
        a caller's DEFAULT_KIT_VOCABULARY reference wasn't `is`-identical to this module's own —
        dataclasses.replace(), a JSON round-trip, etc.). DEFAULT_KIT_VOCABULARY instead declares its own
        `skeleton=DEFAULT_KIT_SKELETON`, so a structural copy carries it over like any other field — no
        identity dependency left to break."""
        copy = DesignKitVocabulary(
            id=DEFAULT_KIT_VOCABULARY.id,
            version=DEFAULT_KIT_VOCABULARY.version,
            classes=dict(DEFAULT_KIT_VOCABULARY.classes),
            utilities=DEFAULT_KIT_VOCABULARY.utilities,
            namespaces=DEFAULT_KIT_VOCABULARY.namespaces,
            skeleton=DEFAULT_KIT_VOCABULARY.skeleton,
        )
        assert copy is not DEFAULT_KIT_VOCABULARY
        fragment = design_kit_prompt_fragment(copy)
        assert "Skeleton of a well-formed widget body" in fragment
        assert "Sales by region" in fragment

    def test_lookalike_kit_with_no_skeleton_of_its_own_gets_no_skeleton(self) -> None:
        """The failure m-14 originally set out to prevent: an id/version match alone must not resurrect
        the built-in skeleton (whose k-card/k-grid-3/k-table classes this kit may not even define). The
        declared `skeleton` field governs, not a structural id/version match."""
        lookalike = DesignKitVocabulary(
            id=DEFAULT_KIT_VOCABULARY.id,
            version=DEFAULT_KIT_VOCABULARY.version,
            classes={"k-tile": "tile"},
            utilities=(),
            namespaces=(),
        )
        fragment = design_kit_prompt_fragment(lookalike)
        assert "Skeleton of a well-formed widget body" not in fragment

    def test_system_prompt_ends_with_design_brief(self) -> None:
        assert "Keep the design simple and readable" not in L2_SYSTEM_PROMPT
        assert "- Design brief (follow every point):" in L2_SYSTEM_PROMPT
        assert (
            L2_SYSTEM_PROMPT.split("\n")[-1]
            == "  - never leave browser-default styling on tables, buttons or inputs"
        )

    def test_kit_section_follows_design_system_section(self) -> None:
        intent_input = IntentInput(canonical="sales.custom", params={"request": "test"})
        intent = Intent(
            canonical=intent_input.canonical,
            params=intent_input.params,
            hash=compute_intent_hash(intent_input),
        )
        prompt = build_l2_prompt(
            intent=intent,
            refs=[_REF],
            shapes_by_ref={},
            design_system=DesignSystemGuide(kit=DEFAULT_KIT_VOCABULARY),
        )
        assert prompt.index("## Design system") < prompt.index("## Design kit") < prompt.index(
            "## Output language"
        )
        assert _EXPECTED_KIT_FRAGMENT in prompt
        without = build_l2_prompt(
            intent=intent, refs=[_REF], shapes_by_ref={}, design_system=DesignSystemGuide()
        )
        assert "## Design kit" not in without


class TestUnknownClassLint:
    def test_collect_unknown(self) -> None:
        assert collect_unknown_kit_classes(_UNKNOWN_HTML, DEFAULT_KIT_VOCABULARY) == [
            "k-panel",
            "k-tile",
            "rounded-xl",
            "text-gray-700",
        ]
        assert collect_unknown_kit_classes(_KIT_HTML, DEFAULT_KIT_VOCABULARY) == []

    def test_is_up_and_a_misspelling_of_it_are_both_ignored(self) -> None:
        """Neither is-up nor is-upp starts with a reserved namespace prefix, so both are ignored —
        not because of any is-up/is-down special-casing (there is none)."""
        html = _widget('<div class="k-kpi-delta is-up"></div><div class="is-upp"></div>')
        assert collect_unknown_kit_classes(html, DEFAULT_KIT_VOCABULARY) == []

    def test_ignores_interpolated_and_concatenation_prefix_class_names(self) -> None:
        html = _widget(
            '<div class="k-bar k-series-${i}"></div><div class="k-series-"></div>',
            "el.className = `k-${kind}`;",
        )
        assert collect_unknown_kit_classes(html, DEFAULT_KIT_VOCABULARY) == []

    def test_still_flags_an_invented_series_class(self) -> None:
        assert collect_unknown_kit_classes(
            _widget('<div class="k-series-9"></div>'), DEFAULT_KIT_VOCABULARY
        ) == ["k-series-9"]

    def test_scans_set_attribute_class(self) -> None:
        """setAttribute("class", …) — SVG elements cannot use className."""
        html = _widget(
            '<div class="k-card"></div>', 'rect.setAttribute("class", "k-axis k-tickz");'
        )
        assert collect_unknown_kit_classes(html, DEFAULT_KIT_VOCABULARY) == ["k-tickz"]

    def test_does_not_flag_the_now_covered_spacing_and_sizing_utilities(self) -> None:
        assert (
            collect_unknown_kit_classes(
                _widget('<div class="mx-auto pt-2 h-full"></div>'), DEFAULT_KIT_VOCABULARY
            )
            == []
        )

    def test_scans_class_list_toggle_remove_replace(self) -> None:
        html = _widget(
            '<div class="k-card"></div>',
            'el.classList.toggle("k-hiddenn", x); el.classList.remove("k-tilee"); '
            'el.classList.replace("k-oldd", "hidden");',
        )
        assert collect_unknown_kit_classes(html, DEFAULT_KIT_VOCABULARY) == [
            "k-hiddenn",
            "k-oldd",
            "k-tilee",
        ]

    def test_class_list_toggle_with_a_real_kit_class_is_not_flagged(self) -> None:
        html = _widget('<div class="k-card"></div>', 'el.classList.toggle("hidden", x);')
        assert collect_unknown_kit_classes(html, DEFAULT_KIT_VOCABULARY) == []

    def test_issue_only_with_kit(self) -> None:
        assert collect_l2_issues(_UNKNOWN_HTML) == []
        assert collect_l2_issues(_UNKNOWN_HTML, enforce_token_colors=True) == []
        issues = collect_l2_issues(_UNKNOWN_HTML, kit=DEFAULT_KIT_VOCABULARY)
        assert len(issues) == 1 and issues[0].startswith("L2_UNKNOWN_CLASS")
        assert "k-panel, k-tile, rounded-xl, text-gray-700" in issues[0]
        assert collect_l2_issues(_KIT_HTML, kit=DEFAULT_KIT_VOCABULARY) == []


class TestComposeWiring:
    def _ctx(self, llm: FakeLlm, storage: FileStoragePort, guide: DesignSystemGuide) -> ComposeContext:
        policy = ComposePolicy(allowL2=True, routeTier=lambda _i: "L2", designSystem=guide)
        return ComposeContext(catalog=_CATALOG, semantic=_FakeSemantic(), storage=storage, llm=llm, policy=policy)

    def test_unknown_class_is_repaired(self, tmp_path: Any) -> None:
        async def run() -> None:
            llm = FakeLlm(texts=[_UNKNOWN_HTML, _KIT_HTML])
            result = await compose(
                _INTENT_INPUT,
                self._ctx(llm, FileStoragePort(tmp_path), DesignSystemGuide(kit=DEFAULT_KIT_VOCABULARY)),
            )
            assert len(llm.calls) == 2
            assert "## Design kit (kohaku v1)" in llm.calls[0].prompt
            assert any("L2_UNKNOWN_CLASS" in i for i in result.trace.attempts[0].issues or [])
            assert "L2_UNKNOWN_CLASS" in llm.calls[1].prompt
            sandbox = next(c for c in result.spec.components if c.type == "sandbox.html")
            assert sandbox.artifact is not None and sandbox.artifact.inline == _KIT_HTML

        asyncio.run(run())

    def test_enforce_off(self, tmp_path: Any) -> None:
        async def run() -> None:
            llm = FakeLlm(texts=[_UNKNOWN_HTML])
            guide = DesignSystemGuide(kit=DEFAULT_KIT_VOCABULARY, enforceKitClasses=False)
            result = await compose(_INTENT_INPUT, self._ctx(llm, FileStoragePort(tmp_path), guide))
            assert len(llm.calls) == 1
            assert "## Design kit (kohaku v1)" in llm.calls[0].prompt
            sandbox = next(c for c in result.spec.components if c.type == "sandbox.html")
            assert sandbox.artifact is not None and sandbox.artifact.inline == _UNKNOWN_HTML

        asyncio.run(run())
