"""The core catalog (Port of TS registry/src/core).

The serializable part of a component definition (type / version / description / capabilities /
props JSON Schema / fallback target / generation) is read as the source of truth from
_data/core-catalog.json, exported from the TS implementation (generated by
`pnpm --filter @kohaku-ui/registry run export-core-catalog`, drift-checked by CI). Because a
fallback's mapProps is a function it cannot be JSON-ified, so it is hand-ported into this module's
_FALLBACK_MAP_PROPS — a test verifies that "every fallbackType in the JSON has a map_props implementation".
"""

from __future__ import annotations

import json
from collections.abc import Callable
from functools import cache
from importlib import resources
from typing import Any

from kohaku.spec import JsonObject, js_string

from ..catalog import Catalog
from ..define import define_component
from ..props_schema import PropsSchema
from ..types import (
    CapabilityDecl,
    ComponentDefinition,
    FallbackDecl,
    ImplementationDecl,
)


def _markdown(text: str) -> JsonObject:
    return {"markdown": text}


def _nullish(*candidates: object) -> object:
    """Equivalent to JS's `a ?? b ?? …`. Returns the first non-None candidate (the last candidate if all are None).

    The TS-side core/*.ts fallback.mapProps use `p["x"] ?? default`, so both a missing key **and an explicit null**
    fall to the default (null coalescing targets only null/undefined and preserves ""/0/false). Python's
    `dict.get(key, default)` only defaults a missing key, leaving an explicit None as None, which would become
    js_string(None)="null"; this fills that gap.
    """
    for c in candidates:
        if c is not None:
            return c
    return candidates[-1]


# Hand-port of the TS-side core/*.ts fallback.mapProps (type -> function). Defaulting via _nullish
# matches TS's `??` (which also falls an explicit null to the default).
_FALLBACK_MAP_PROPS: dict[str, Callable[[JsonObject], JsonObject]] = {
    "presentChart": lambda p: {"editable": False},
    "presentList": lambda p: {"editable": False},
    "presentSpreadsheet": lambda p: _markdown("(This table does not support text rendering)"),
    "presentForm": lambda p: _markdown("(This form is not available on this surface)"),
    "presentMetric": lambda p: _markdown(f"**{js_string(_nullish(p.get('label'), ''))}**"),
    "action.button": lambda p: _markdown(
        f'(Action "{js_string(_nullish(p.get("label"), ""))}" is not available on this surface)'
    ),
    "control.select": lambda p: _markdown(
        f"**{js_string(_nullish(p.get('label'), p.get('value'), ''))}**"
    ),
    "ui.loading": lambda p: _markdown(js_string(_nullish(p.get("label"), "Loading…"))),
    "overlay.toast": lambda p: _markdown(js_string(_nullish(p.get("message"), ""))),
    "layout.tabs": lambda p: {},
    "layout.tab": lambda p: {},
    "overlay.dialog": lambda p: {},
}


def _build_definition(entry: dict[str, Any]) -> ComponentDefinition:
    type_ = entry["type"]
    fallback_type = entry.get("fallbackType")
    fallback: FallbackDecl | None = None
    if fallback_type is not None:
        map_props = _FALLBACK_MAP_PROPS.get(type_)
        if map_props is None:
            raise RuntimeError(
                f'core catalog "{type_}" has no fallback mapProps ported to Python'
                " (add it to _FALLBACK_MAP_PROPS)"
            )
        fallback = FallbackDecl(type=fallback_type, map_props=map_props)
    impl = entry.get("implementation") or {"kind": "native"}
    return define_component(
        ComponentDefinition(
            type=type_,
            version=entry["version"],
            description=entry["description"],
            propsSchema=PropsSchema(entry["propsSchema"]),
            capabilities=CapabilityDecl(
                events=list(entry["capabilities"]["events"]),
                data=entry["capabilities"]["data"],
                children=entry["capabilities"]["children"],
                editable=entry["capabilities"].get("editable"),
                surfaces=entry["capabilities"].get("surfaces"),
            ),
            implementation=ImplementationDecl(kind=impl["kind"], html=impl.get("html")),
            fallback=fallback,
            generation=entry.get("generation", "allowed"),
        )
    )


@cache
def core_catalog() -> Catalog:
    """The core catalog (the part whose maintenance the framework takes on).

    Products contribute only their delta via Catalog(components=[...]) (a federated composition).
    """
    data = json.loads(
        resources.files("kohaku.registry._data").joinpath("core-catalog.json").read_text("utf-8")
    )
    return Catalog(components=[_build_definition(e) for e in data["components"]])
