/**
 * MCP server (stdio) for external chat clients (Claude / MCPJam, etc.).
 * Because it uses the same Ports and Composition Service as sample-api,
 * "same request content → same Spec as the Web app → same renderer rendering" holds in external chat too.
 *
 * The common setup (env, createApp, recorder, attach) is consolidated in src/setup.ts, and
 * this file only handles connecting to the stdio transport. Remote connections (claude.ai / ChatGPT, etc.)
 * use the Streamable HTTP entry (src/http.ts, `pnpm start:http`).
 *
 * Usage (e.g. registering with Claude Code):
 *   claude mcp add kohaku-sales -- pnpm --dir <repo>/apps/sample-mcp start
 * For UI display, run `pnpm --dir apps/sample-mcp build:renderer` beforehand.
 * Terminal hosts that cannot render an iframe (Claude Code / Codex CLI, etc.) get the same rendering
 * as the Web app via the self-contained HTML generated by `kohaku_render_snapshot` (open in a browser / publish as an Artifact).
 */
import { StdioServerTransport } from "@modelcontextprotocol/server/stdio";
import { createKohakuMcpSetup } from "./setup.js";

const setup = await createKohakuMcpSetup();
const server = setup.createServer();

await server.connect(new StdioServerTransport());
console.error("kohaku-sales-sample MCP server: ready (stdio)");
