"""kohaku.composer — UI Composition Service (port of TS packages/composer)."""

from .budget import (
    BudgetVerdict,
    ComposeBudget,
    DeadlineGuard,
    check_budget,
    create_deadline_guard,
    sum_spent_tokens,
)
from .compose import (
    COMPOSER_ID,
    ComposeInput,
    ComposeOptions,
    ComposeResult,
    IntentComposeInput,
    RecomposePatch,
    compose,
    finish,
    negotiate_spec,
    post_and_validate,
    prepare_compose,
    recompose,
    run_generation,
)
from .compose_stream import (
    ComposeStreamEvent,
    StreamDoneEvent,
    StreamPatchEvent,
    StreamSpecEvent,
    compose_stream,
)
from .context import (
    BudgetCheckErrorContext,
    ComposeContext,
    ComposeErrorContext,
    ComposeObserver,
    ComposePolicy,
    EffortPolicy,
    FewShotPolicy,
    FixedSpecSource,
    L2SmokeContext,
    ResolvedRefs,
    TierLlm,
    TierLlmFingerprintMaterial,
    TierModelIdentity,
    policy_fingerprint,
    resolve_tier_llm,
    tier_llm_fingerprint_material,
)
from .design_system import (
    DEFAULT_TOKEN_DESCRIPTIONS,
    DesignSystemGuide,
    design_system_prompt_fragment,
    token_to_css_var,
)
from .errors import ComposeError, ComposeErrorCode
from .fallback import build_fallback_spec
from .fixation import FixationCheck, materialize_fixation
from .l2_js_sidecar import L2JsSidecar, create_l2_js_sidecar
from .l2_lint import collect_l2_issues, extract_html_document, extract_title
from .post import (
    STANDARD_RULES,
    PostProcessContext,
    PostRule,
    canonical_props,
    chart_kind,
    normalize_ids,
    post_process,
    sort_order,
)
from .prompt import (
    L1_SYSTEM_PROMPT,
    L2_SYSTEM_PROMPT,
    PROMPT_REVISION,
    FewShotExample,
    append_l1_repair_feedback,
    append_l2_repair_feedback,
    build_l1_prompt,
    build_l1_prompt_parts,
    build_l1_prompt_static,
    build_l2_prompt,
    build_l2_prompt_parts,
    build_l2_prompt_static,
    default_generator_version,
)
from .trace import ComposeAttempt, ComposeTrace, TokenUsage, TraceInput

__all__ = [
    "COMPOSER_ID",
    "DEFAULT_TOKEN_DESCRIPTIONS",
    "L1_SYSTEM_PROMPT",
    "L2_SYSTEM_PROMPT",
    "PROMPT_REVISION",
    "STANDARD_RULES",
    "BudgetCheckErrorContext",
    "BudgetVerdict",
    "ComposeAttempt",
    "ComposeBudget",
    "ComposeContext",
    "ComposeError",
    "ComposeErrorCode",
    "ComposeErrorContext",
    "ComposeInput",
    "ComposeObserver",
    "ComposeOptions",
    "ComposePolicy",
    "ComposeResult",
    "ComposeStreamEvent",
    "ComposeTrace",
    "DeadlineGuard",
    "DesignSystemGuide",
    "EffortPolicy",
    "FewShotExample",
    "FewShotPolicy",
    "FixationCheck",
    "FixedSpecSource",
    "IntentComposeInput",
    "L2JsSidecar",
    "L2SmokeContext",
    "PostProcessContext",
    "PostRule",
    "RecomposePatch",
    "ResolvedRefs",
    "StreamDoneEvent",
    "StreamPatchEvent",
    "StreamSpecEvent",
    "TierLlm",
    "TierLlmFingerprintMaterial",
    "TierModelIdentity",
    "TokenUsage",
    "TraceInput",
    "append_l1_repair_feedback",
    "append_l2_repair_feedback",
    "build_fallback_spec",
    "build_l1_prompt",
    "build_l1_prompt_parts",
    "build_l1_prompt_static",
    "build_l2_prompt",
    "build_l2_prompt_parts",
    "build_l2_prompt_static",
    "canonical_props",
    "chart_kind",
    "check_budget",
    "collect_l2_issues",
    "compose",
    "compose_stream",
    "create_deadline_guard",
    "create_l2_js_sidecar",
    "default_generator_version",
    "design_system_prompt_fragment",
    "extract_html_document",
    "extract_title",
    "finish",
    "materialize_fixation",
    "negotiate_spec",
    "normalize_ids",
    "policy_fingerprint",
    "post_and_validate",
    "post_process",
    "prepare_compose",
    "recompose",
    "resolve_tier_llm",
    "run_generation",
    "sort_order",
    "sum_spent_tokens",
    "tier_llm_fingerprint_material",
    "token_to_css_var",
]
