/**
 * Constant file templates for `kohaku init`: text a generated project receives verbatim (no per-dataset
 * substitution beyond the explicit `__SOURCE__` / `__NAME__` placeholders replaced in render.ts). Keeping
 * these as plain strings (rather than a template-engine file) means each one is exactly the TypeScript /
 * JSON / HTML a generated project ships with, readable and diffable as such.
 */

export const DOMAIN_PORT_TEMPLATE = `import type { DataShape, DomainPort, JsonObject, OperationDescriptor, TabularColumn, TabularData } from "@kohaku-ui/spec-core";
import { type Cell, COLUMNS, DATA_VERSION, type Row, ROWS } from "./dataset.js";

/**
 * DomainPort over the rows in data/*.json: three read operations (query://<source>/{summary,trend,records}).
 * Generated by \`kohaku init\`; edit freely — this file is yours. Aggregations: sum / avg of a measure, or the row count.
 */

export type Granularity = "month" | "quarter" | "year";
type Agg = "sum" | "avg";

function str(v: unknown): string | undefined {
  return typeof v === "string" && v !== "" ? v : undefined;
}

function num(v: unknown): number | undefined {
  const n = typeof v === "number" ? v : typeof v === "string" ? Number(v) : Number.NaN;
  return Number.isFinite(n) ? n : undefined;
}

export function label(name: string): string {
  const spaced = name.replace(/[_-]+/g, " ");
  return spaced.charAt(0).toUpperCase() + spaced.slice(1);
}

/** Dimension filters (\`region=japan\`) and the inclusive time window (\`from\` / \`to\` as ISO prefixes: "2026-04", "2026"). */
function filterRows(args: JsonObject): Row[] {
  const from = str(args["from"]);
  const to = str(args["to"]);
  return ROWS.filter((row) => {
    for (const dim of COLUMNS.dimensions) {
      const want = str(args[dim]);
      if (want != null && String(row[dim] ?? "") !== want) return false;
    }
    if (COLUMNS.time != null) {
      const t = String(row[COLUMNS.time] ?? "");
      if (from != null && t < from) return false;
      if (to != null && t.slice(0, to.length) > to) return false;
    }
    return true;
  });
}

function bucket(value: Cell, granularity: Granularity): string {
  const s = String(value ?? "");
  const year = s.slice(0, 4);
  const month = Number(s.slice(5, 7)) || 1;
  if (granularity === "year") return year;
  if (granularity === "quarter") return \`\${year}-Q\${Math.floor((month - 1) / 3) + 1}\`;
  return s.slice(0, 7);
}

function metricOf(args: JsonObject): string {
  const m = str(args["metric"]);
  return m != null && (m === "count" || COLUMNS.measures.includes(m)) ? m : (COLUMNS.measures[0] ?? "count");
}

function aggOf(args: JsonObject): Agg {
  return args["agg"] === "avg" ? "avg" : "sum";
}

function groupByOf(args: JsonObject): string {
  const g = str(args["groupBy"]);
  return g != null && COLUMNS.dimensions.includes(g) ? g : COLUMNS.dimensions[0]!;
}

function aggregate(rows: Row[], keyOf: (row: Row) => string, metric: string, agg: Agg): { key: string; value: number }[] {
  const acc = new Map<string, { sum: number; count: number }>();
  for (const row of rows) {
    const key = keyOf(row);
    const entry = acc.get(key) ?? { sum: 0, count: 0 };
    entry.count += 1;
    if (metric !== "count") entry.sum += num(row[metric]) ?? 0;
    acc.set(key, entry);
  }
  return [...acc.entries()].map(([key, e]) => ({
    key,
    value: metric === "count" ? e.count : agg === "avg" ? (e.count === 0 ? 0 : e.sum / e.count) : e.sum,
  }));
}

function measureColumn(metric: string, agg: Agg): TabularColumn {
  const l = metric === "count" ? "Count" : agg === "avg" ? \`Average \${label(metric)}\` : label(metric);
  return { key: metric, label: l, type: "number" };
}

export function summary(args: JsonObject): TabularData {
  const groupBy = groupByOf(args);
  const metric = metricOf(args);
  const agg = aggOf(args);
  const rows = aggregate(filterRows(args), (row) => String(row[groupBy] ?? ""), metric, agg)
    .sort((a, b) => b.value - a.value)
    .map((r) => ({ [groupBy]: r.key, [metric]: r.value }) as JsonObject);
  return {
    columns: [{ key: groupBy, label: label(groupBy), type: "string" }, measureColumn(metric, agg)],
    rows,
    dataVersion: DATA_VERSION,
  };
}

export function trend(args: JsonObject): TabularData {
  const time = COLUMNS.time;
  if (time == null) throw new Error("trend needs a time column; this dataset has none");
  const granularity = (str(args["granularity"]) ?? "month") as Granularity;
  const metric = metricOf(args);
  const agg = aggOf(args);
  const rows = aggregate(filterRows(args), (row) => bucket(row[time] ?? null, granularity), metric, agg)
    .sort((a, b) => a.key.localeCompare(b.key))
    .map((r) => ({ [granularity]: r.key, [metric]: r.value }) as JsonObject);
  return {
    columns: [{ key: granularity, label: label(granularity), type: "string" }, measureColumn(metric, agg)],
    rows,
    dataVersion: DATA_VERSION,
  };
}

export function records(args: JsonObject): TabularData {
  const limit = Math.min(500, Math.max(1, num(args["limit"]) ?? 100));
  const columns: TabularColumn[] = [
    ...COLUMNS.dimensions.map((d) => ({ key: d, label: label(d), type: "string" as const })),
    ...(COLUMNS.time != null ? [{ key: COLUMNS.time, label: label(COLUMNS.time), type: "string" as const }] : []),
    ...COLUMNS.measures.map((m) => ({ key: m, label: label(m), type: "number" as const })),
  ];
  const rows = filterRows(args).slice(0, limit).map((row) => Object.fromEntries(columns.map((c) => [c.key, row[c.key] ?? null])) as JsonObject);
  return { columns, rows, dataVersion: DATA_VERSION, total: ROWS.length };
}

export const OPERATIONS = { summary, trend, records } as const;

/** Column metadata only (no rows): what composer's chart-kind rules and props filling see (reference passing). */
export function shapeOf(op: string, args: JsonObject): DataShape | null {
  if (!Object.hasOwn(OPERATIONS, op)) return null;
  if (op === "trend" && COLUMNS.time == null) return null;
  const { columns } = OPERATIONS[op as keyof typeof OPERATIONS](args);
  return {
    columns: columns.map((c) => ({
      name: c.key,
      type: c.type,
      role: c.type === "number" ? "measure" : op === "trend" && c.key !== metricOf(args) ? "time" : "dimension",
    })),
    rowCountHint: ROWS.length,
  };
}

export function createDomainPort(): DomainPort {
  const names = Object.keys(OPERATIONS).filter((op) => op !== "trend" || COLUMNS.time != null);
  return {
    async listOperations(): Promise<OperationDescriptor[]> {
      return names.map((name) => ({ name, description: \`\${name} query over the \${label(COLUMNS.source)} data\`, resultShape: shapeOf(name, {}) ?? undefined }));
    },
    // InvocationContext (principal / capability) is intentionally not consumed: this generated port has
    // no per-principal data filtering, so it implements the 2-argument subset of DomainPort.invoke.
    async invoke(op: string, args: JsonObject): Promise<unknown> {
      if (!names.includes(op)) throw new Error(\`unknown operation: \${op}\`);
      return OPERATIONS[op as keyof typeof OPERATIONS](args);
    },
  };
}
`;

export const FIXED_SPECS_TEMPLATE = `import type { FixedSpecSource } from "@kohaku-ui/composer";
import { type CanonicalIntent, type ComponentNode, type QueryHandle, SPEC_VERSION, type UISpec } from "@kohaku-ui/spec-core";
import { COLUMNS } from "./dataset.js";
import { label } from "./domain-port.js";

/**
 * L0 fixed Specs: "app UI is a solidified L1 Spec". \`__SOURCE__.summary\` never goes through the LLM — this template
 * builds the Spec deterministically (adoption-ladder Step 0). Add more views here as they stabilize, or let the
 * fixation pipeline (Step 2) pin L1 output for you.
 */
export function createFixedSpecs(): FixedSpecSource {
  const builders: Record<string, (intent: CanonicalIntent, refs: QueryHandle[]) => UISpec> = {
    "__SOURCE__.summary": summaryView,
  };
  return {
    async lookup(intent) {
      return builders[intent.canonical] ?? null;
    },
  };
}

function summaryView(intent: CanonicalIntent, refs: QueryHandle[]): UISpec {
  const p = intent.params;
  const groupBy = String(p["groupBy"] ?? COLUMNS.dimensions[0]);
  const metric = String(p["metric"] ?? COLUMNS.measures[0] ?? "count");
  const agg = String(p["agg"] ?? "sum");
  const ref = refs[0]!.uri;
  const title = \`\${metric === "count" ? "Row count" : \`\${agg === "avg" ? "Average" : "Total"} \${label(metric).toLowerCase()}\`} by \${label(groupBy).toLowerCase()}\`;
  const components: ComponentNode[] = [
    { id: "root", type: "layout.stack", props: { direction: "vertical", gap: "md" }, children: ["t", "c", "g"] },
    { id: "t", type: "text.heading", props: { level: 2, text: title } },
    { id: "c", type: "presentChart", props: { kind: "bar", x: groupBy, y: metric }, data: { $ref: ref } },
    { id: "g", type: "presentSpreadsheet", props: { editable: false }, data: { $ref: ref } },
  ];
  return {
    kohaku: SPEC_VERSION,
    intent,
    dataVersion: "template",
    components,
    events: [],
    provenance: { tier: "L0", composedBy: "fixed-spec-template", cache: "miss" },
  };
}
`;

export const APP_TEMPLATE = `import { existsSync } from "node:fs";
import { createHmacAuthzPort } from "@kohaku-ui/authz-hmac";
import { type ComposeContext, defaultGeneratorVersion } from "@kohaku-ui/composer";
import { createKohakuRoutes } from "@kohaku-ui/host-rest";
import type { LlmPort } from "@kohaku-ui/llm";
import { coreCatalog, resolveCatalog } from "@kohaku-ui/registry";
import { createIntentCatalog, createLlmSemanticPort } from "@kohaku-ui/semantic-llm";
import type { AuthzPort, StoragePort } from "@kohaku-ui/spec-core";
import { createMemoryStoragePort } from "@kohaku-ui/storage-memory";
import { Hono } from "hono";
import { DATA_VERSION } from "./dataset.js";
import { createDomainPort, shapeOf } from "./domain-port.js";
import { createFixedSpecs } from "./fixed-specs.js";
import { INTENT_DEFINITIONS, SOURCE } from "./intents.js";

export interface AppDeps {
  llm: LlmPort;
  storage?: StoragePort;
  authz?: AuthzPort;
}

/**
 * Wires the four Ports into host-rest. Generated by \`kohaku init\` — the defaults (in-memory storage, HMAC capabilities,
 * the LLM-backed SemanticPort) are starting points; replace any of them with your product's own implementation
 * (the contract is @kohaku-ui/spec-core's ports.ts).
 */
export function createApp(deps: AppDeps): { app: Hono; composeCtx: ComposeContext } {
  // Load .env here too (not just in server/main.ts): this function is also called directly by
  // test/golden.test.ts and by anyone scripting against the generated project without going through
  // main.ts, and it must see the same KOHAKU_CAPABILITY_SECRET either way. process.loadEnvFile never
  // overrides a variable already present in the environment, so calling it more than once is harmless.
  if (existsSync(".env")) process.loadEnvFile(".env");
  const storage = deps.storage ?? createMemoryStoragePort();
  const secret = process.env["KOHAKU_CAPABILITY_SECRET"];
  if (!secret) {
    throw new Error("KOHAKU_CAPABILITY_SECRET is required (see .env.example)");
  }
  const authz = deps.authz ?? createHmacAuthzPort(secret);
  const intentCatalog = createIntentCatalog(INTENT_DEFINITIONS.map((d) => d.toIntentDef()));
  const semantic = createLlmSemanticPort({
    llm: deps.llm,
    catalog: intentCatalog,
    dataVersion: () => DATA_VERSION,
    describeShape: (ref) => shapeOf(ref.path, ref.params),
  });
  const composeCtx: ComposeContext = {
    catalog: resolveCatalog(coreCatalog),
    semantic,
    storage,
    llm: deps.llm,
    policy: {
      // Step 0: the summary view is an L0 fixed Spec. Step 1: everything else is L1 (LLM). Step 2 (L2 free generation,
      // promotion, fixation) is off — see README.md for how to enable it.
      fixedSpecs: createFixedSpecs(),
      allowL2: false,
      generatorVersion: defaultGeneratorVersion(deps.llm),
    },
  };

  const app = new Hono();
  app.route("/api/kohaku", createKohakuRoutes({ compose: composeCtx, domain: createDomainPort(), authz, querySource: SOURCE }));
  // Facet descriptors for the dashboard's selectors, derived from the same Intent definitions (no codegen step).
  app.get("/api/app/facet-views", (c) => c.json({ views: INTENT_DEFINITIONS.map((d) => d.toFacetView()).filter((v) => v.facets.length > 0) }));
  app.get("/api/health", (c) => c.json({ ok: true, llm: { provider: deps.llm.provider, model: deps.llm.modelId }, dataVersion: DATA_VERSION }));
  return { app, composeCtx };
}
`;

export const MAIN_TEMPLATE = `import { existsSync } from "node:fs";
import { serve } from "@hono/node-server";
import { createLlmFromEnv } from "@kohaku-ui/llm";
import { createApp } from "./app.js";

if (existsSync(".env")) process.loadEnvFile(".env");

// Without an API key the L0 view (the summary dashboard) still renders; chat and the L1 views need one — see README.md.
const llm = createLlmFromEnv();
const { app } = createApp({ llm });
const port = Number(process.env["PORT"] ?? 8787);
serve({ fetch: app.fetch, port }, (info) => {
  console.log(\`kohaku host: http://localhost:\${info.port}/api/kohaku (LLM: \${llm.provider} / \${llm.modelId})\`);
});
`;

export const WEB_MAIN_TEMPLATE = `import { createKohakuClient, type ComposeView } from "@kohaku-ui/client";
import { createBindingClient } from "@kohaku-ui/data-binding";
import { defaultLightTheme } from "@kohaku-ui/renderer-core";
import { RendererProvider, SpecView, type SurfaceEvent } from "@kohaku-ui/renderer-react";
import { createCoreRegistry } from "@kohaku-ui/renderer-react/core";
import { type ReactNode, StrictMode, useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";

const client = createKohakuClient({ baseUrl: "/api/kohaku" });
const impls = createCoreRegistry();

interface FacetView {
  intent: string;
  label: string;
  facets: { key: string; label: string; options: { value: string; label: string }[]; allowEmpty?: string }[];
}

/** Renders a composed Spec. Both surfaces (dashboard and chat) go through this, so identical Specs render identically. */
function Surface(props: { view: ComposeView; onEvent?: (e: SurfaceEvent) => void }): ReactNode {
  const binding = useMemo(() => createBindingClient({ baseUrl: "/api/kohaku", capability: props.view.capability }), [props.view.capability]);
  const value = useMemo(
    () => ({ impls, binding, theme: defaultLightTheme, ...(props.onEvent != null ? { onEvent: props.onEvent } : {}) }),
    [binding, props.onEvent],
  );
  return (
    <RendererProvider value={value}>
      <SpecView spec={props.view.spec} />
    </RendererProvider>
  );
}

function Dashboard(): ReactNode {
  const [views, setViews] = useState<FacetView[]>([]);
  const [intent, setIntent] = useState<string | null>(null);
  const [params, setParams] = useState<Record<string, string>>({});
  const [view, setView] = useState<ComposeView | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch("/api/app/facet-views")
      .then((r) => r.json())
      .then((json: { views: FacetView[] }) => {
        setViews(json.views);
        setIntent(json.views[0]?.intent ?? null);
      })
      .catch((e) => setError(String(e)));
  }, []);

  useEffect(() => {
    if (intent == null) return;
    setError(null);
    client
      .compose({ input: { kind: "gui", action: "view.select", params: { intent, ...params } }, session: { surface: "web" } })
      .then(setView)
      .catch((e) => setError(e instanceof Error ? e.message : String(e)));
  }, [intent, params]);

  const current = views.find((v) => v.intent === intent);
  const onEvent = (e: SurfaceEvent): void => {
    if (view == null) return;
    client
      .sendEvent({ intent: { canonical: view.spec.intent.canonical, params: view.spec.intent.params }, on: e.on, payload: e.payload, session: { surface: "web" } })
      .then(setView)
      .catch((err) => setError(err instanceof Error ? err.message : String(err)));
  };

  return (
    <div style={{ display: "grid", gridTemplateColumns: "220px 1fr", gap: 24 }}>
      <aside style={{ display: "flex", flexDirection: "column", gap: 12 }}>
        <label>
          View
          <select value={intent ?? ""} onChange={(e) => { setIntent(e.target.value); setParams({}); }}>
            {views.map((v) => <option key={v.intent} value={v.intent}>{v.label}</option>)}
          </select>
        </label>
        {current?.facets.map((f) => (
          <label key={f.key}>
            {f.label}
            <select value={params[f.key] ?? ""} onChange={(e) => setParams({ ...params, [f.key]: e.target.value })}>
              {f.allowEmpty != null && <option value="">{f.allowEmpty}</option>}
              {f.options.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}
            </select>
          </label>
        ))}
      </aside>
      <main>
        {error != null && <p style={{ color: "#b91c1c" }}>{error}</p>}
        {view != null && (
          <>
            <p style={{ fontSize: 12, color: "#6b7280" }}>
              {view.spec.provenance.tier} · cache:{view.spec.provenance.cache}
            </p>
            <Surface view={view} onEvent={onEvent} />
          </>
        )}
      </main>
    </div>
  );
}

function Chat(): ReactNode {
  const [text, setText] = useState("");
  const [items, setItems] = useState<{ question: string; intent?: string; view?: ComposeView; error?: string }[]>([]);
  const ask = async (): Promise<void> => {
    const question = text.trim();
    if (question === "") return;
    setText("");
    setItems((prev) => [...prev, { question }]);
    try {
      const { intent } = await client.normalizeIntent({ input: { kind: "nl", text: question }, session: { surface: "chat" } });
      const view = await client.compose({ intent: { canonical: intent.canonical, params: intent.params }, session: { surface: "chat" } });
      setItems((prev) => prev.map((it) => (it.question === question && it.view == null ? { ...it, intent: intent.canonical, view } : it)));
    } catch (e) {
      const error = e instanceof Error ? e.message : String(e);
      setItems((prev) => prev.map((it) => (it.question === question && it.view == null ? { ...it, error } : it)));
    }
  };
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
      {items.map((it, i) => (
        <div key={i}>
          <p><strong>You:</strong> {it.question}</p>
          {it.intent != null && <p style={{ fontSize: 12, color: "#6b7280" }}>→ {it.intent}</p>}
          {it.error != null && <p style={{ color: "#b91c1c" }}>{it.error}</p>}
          {it.view != null && <Surface view={it.view} />}
        </div>
      ))}
      <form onSubmit={(e) => { e.preventDefault(); void ask(); }} style={{ display: "flex", gap: 8 }}>
        <input value={text} onChange={(e) => setText(e.target.value)} placeholder="Ask about your data…" style={{ flex: 1, padding: 8 }} />
        <button type="submit">Ask</button>
      </form>
    </div>
  );
}

function App(): ReactNode {
  const [tab, setTab] = useState<"dashboard" | "chat">("dashboard");
  return (
    <div style={{ fontFamily: "system-ui, sans-serif", padding: 24, maxWidth: 1100, margin: "0 auto" }}>
      <nav style={{ display: "flex", gap: 8, marginBottom: 16 }}>
        <button type="button" onClick={() => setTab("dashboard")} disabled={tab === "dashboard"}>Dashboard</button>
        <button type="button" onClick={() => setTab("chat")} disabled={tab === "chat"}>Chat</button>
      </nav>
      {tab === "dashboard" ? <Dashboard /> : <Chat />}
    </div>
  );
}

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
`;

export const INDEX_HTML_TEMPLATE = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>__NAME__ · kohaku</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/web/main.tsx"></script>
  </body>
</html>
`;

export const VITE_CONFIG_TEMPLATE = `import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [react()],
  server: { port: 5173, proxy: { "/api": \`http://localhost:\${process.env["PORT"] ?? 8787}\` } },
});
`;

export const TSCONFIG_TEMPLATE = `{
  "compilerOptions": {
    "target": "ES2023",
    "lib": ["ES2023", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "moduleResolution": "bundler",
    "jsx": "react-jsx",
    "strict": true,
    "verbatimModuleSyntax": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "noEmit": true,
    "types": ["node", "vite/client"]
  },
  "include": ["server", "web", "test", "vite.config.ts"]
}
`;

export const DEV_SCRIPT_TEMPLATE = `// Runs the API (tsx watch) and the web dev server (vite) together; Ctrl-C stops both.
import { spawn } from "node:child_process";

const children = [
  spawn("npx", ["tsx", "watch", "server/main.ts"], { stdio: "inherit", shell: process.platform === "win32" }),
  spawn("npx", ["vite"], { stdio: "inherit", shell: process.platform === "win32" }),
];
const stop = () => {
  for (const child of children) child.kill("SIGINT");
};
process.on("SIGINT", stop);
process.on("SIGTERM", stop);
for (const child of children) child.on("exit", (code) => { if (code != null && code !== 0) { stop(); process.exitCode = code; } });
`;

export const GOLDEN_TEST_TEMPLATE_INIT = `/**
 * Golden Spec regression (generated by kohaku init). Pins the structure of Intent → Spec; LLM output jitter
 * (provenance / hashes / component ids) is normalized away by runGolden. No LLM is used: fixtures for L1 views
 * carry the model's raw drafts (FakeLlm), the L0 summary fixture needs none.
 *
 * Generating / updating \`expected\`: KOHAKU_GOLDEN_UPDATE=1 npm test writes each fixture's expected back from the actual
 * compose output (deterministic, no LLM); review the diff and commit. A fixture whose expected is still null fails
 * until you do that. Never run update mode in CI.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { type ComposeContext, type ComposeInput, compose } from "@kohaku-ui/composer";
import { type GoldenCase, runGolden } from "@kohaku-ui/evals";
import { FakeLlm } from "@kohaku-ui/llm/fake";
import type { UISpec } from "@kohaku-ui/spec-core";
import { describe, expect, it } from "vitest";
import { createApp } from "../server/app.js";

const GOLDEN_DIR = join(dirname(fileURLToPath(import.meta.url)), "golden");
const UPDATE = process.env["KOHAKU_GOLDEN_UPDATE"] === "1";
if (UPDATE && process.env["CI"] != null) {
  throw new Error("KOHAKU_GOLDEN_UPDATE=1 must not run in CI (it rewrites goldens instead of asserting them)");
}

interface GoldenFixture {
  name: string;
  input: ComposeInput;
  drafts: unknown[];
  expected: UISpec | null;
}

function makeContext(drafts: unknown[]): ComposeContext {
  return createApp({ llm: new FakeLlm({ objects: drafts }) }).composeCtx;
}

const files = existsSync(GOLDEN_DIR) ? readdirSync(GOLDEN_DIR).filter((f) => f.endsWith(".json")).sort() : [];

describe("golden regression", () => {
  for (const file of files) {
    const path = join(GOLDEN_DIR, file);
    const fixture = JSON.parse(readFileSync(path, "utf8")) as GoldenFixture;
    it(fixture.name, async () => {
      const ctx = makeContext(fixture.drafts);
      if (UPDATE) {
        const { spec } = await compose(fixture.input, ctx);
        writeFileSync(path, \`\${JSON.stringify({ ...fixture, expected: spec }, null, 2)}\\n\`);
        return;
      }
      expect(fixture.expected, \`\${file}: expected not generated. Generate it with KOHAKU_GOLDEN_UPDATE=1 npm test\`).not.toBeNull();
      const cases: GoldenCase[] = [{ name: fixture.name, input: fixture.input, expected: fixture.expected! }];
      const report = await runGolden(cases, ctx);
      const failed = report.cases.find((c) => !c.pass);
      expect(report.pass, failed ? \`golden mismatch (\${file})\\n\${failed.expected}\\n---\\n\${failed.actual}\` : undefined).toBe(true);
    });
  }
});
`;

export const ENV_EXAMPLE_TEMPLATE = `# Pick one provider. Without a key the summary dashboard (L0) still works; chat and the other views need the LLM.
KOHAKU_LLM_PROVIDER=claude
# KOHAKU_LLM_API_KEY=   # or export ANTHROPIC_API_KEY / OPENAI_API_KEY / GOOGLE_GENERATIVE_AI_API_KEY instead
# Local, no key: KOHAKU_LLM_PROVIDER=ollama KOHAKU_LLM_MODEL=gemma4:e4b

# HMAC signing secret for capability tokens. \`kohaku init\` already generated a random one into .env
# (git-ignored, not this file); set this only if you need a fixed value of your own. The server refuses
# to start without one (see server/app.ts).
KOHAKU_CAPABILITY_SECRET=
PORT=8787
`;

export const GITIGNORE_TEMPLATE = `node_modules/
dist/
.env
`;
