/**
 * Constant file templates for `kohaku init`: text a generated project receives verbatim (no per-dataset
 * substitution beyond the explicit `__SOURCE__` / `__NAME__` placeholders replaced in render.ts). Keeping
 * these as plain strings (rather than a template-engine file) means each one is exactly the TypeScript /
 * JSON / HTML a generated project ships with, readable and diffable as such.
 */

export const DOMAIN_PORT_TEMPLATE = `import type { DataShape, DomainPort, JsonObject, OperationDescriptor, TabularColumn, TabularData } from "@kohaku-ui/spec-core";
import { type Cell, COLUMNS, DATA_VERSION, type Row, ROWS } from "./dataset.js";

/**
 * DomainPort over the rows in data/*.json: three read operations (query://<source>/{summary,trend,records}).
 * Generated by \`kohaku init\`; edit freely — this file is yours. Aggregations: sum / avg of a measure, or the row count.
 */

export type Granularity = "month" | "quarter" | "year";
type Agg = "sum" | "avg";

function str(v: unknown): string | undefined {
  return typeof v === "string" && v !== "" ? v : undefined;
}

function num(v: unknown): number | undefined {
  const n = typeof v === "number" ? v : typeof v === "string" ? Number(v) : Number.NaN;
  return Number.isFinite(n) ? n : undefined;
}

export function label(name: string): string {
  const spaced = name.replace(/[_-]+/g, " ");
  return spaced.charAt(0).toUpperCase() + spaced.slice(1);
}

/** Dimension filters (\`region=japan\`) and the inclusive time window (\`from\` / \`to\` as ISO prefixes: "2026-04", "2026"). */
function filterRows(args: JsonObject): Row[] {
  const from = str(args["from"]);
  const to = str(args["to"]);
  return ROWS.filter((row) => {
    for (const dim of COLUMNS.dimensions) {
      const want = str(args[dim]);
      if (want != null && String(row[dim] ?? "") !== want) return false;
    }
    if (COLUMNS.time != null) {
      const t = String(row[COLUMNS.time] ?? "");
      if (from != null && t < from) return false;
      if (to != null && t.slice(0, to.length) > to) return false;
    }
    return true;
  });
}

function bucket(value: Cell, granularity: Granularity): string {
  const s = String(value ?? "");
  const year = s.slice(0, 4);
  const month = Number(s.slice(5, 7)) || 1;
  if (granularity === "year") return year;
  if (granularity === "quarter") return \`\${year}-Q\${Math.floor((month - 1) / 3) + 1}\`;
  return s.slice(0, 7);
}

function metricOf(args: JsonObject): string {
  const m = str(args["metric"]);
  return m != null && (m === "count" || COLUMNS.measures.includes(m)) ? m : (COLUMNS.measures[0] ?? "count");
}

function aggOf(args: JsonObject): Agg {
  return args["agg"] === "avg" ? "avg" : "sum";
}

function groupByOf(args: JsonObject): string {
  const g = str(args["groupBy"]);
  return g != null && COLUMNS.dimensions.includes(g) ? g : COLUMNS.dimensions[0]!;
}

function aggregate(rows: Row[], keyOf: (row: Row) => string, metric: string, agg: Agg): { key: string; value: number }[] {
  const acc = new Map<string, { sum: number; count: number }>();
  for (const row of rows) {
    const key = keyOf(row);
    const entry = acc.get(key) ?? { sum: 0, count: 0 };
    entry.count += 1;
    if (metric !== "count") entry.sum += num(row[metric]) ?? 0;
    acc.set(key, entry);
  }
  return [...acc.entries()].map(([key, e]) => ({
    key,
    value: metric === "count" ? e.count : agg === "avg" ? (e.count === 0 ? 0 : e.sum / e.count) : e.sum,
  }));
}

function measureColumn(metric: string, agg: Agg): TabularColumn {
  const l = metric === "count" ? "Count" : agg === "avg" ? \`Average \${label(metric)}\` : label(metric);
  return { key: metric, label: l, type: "number" };
}

export function summary(args: JsonObject): TabularData {
  const groupBy = groupByOf(args);
  const metric = metricOf(args);
  const agg = aggOf(args);
  const rows = aggregate(filterRows(args), (row) => String(row[groupBy] ?? ""), metric, agg)
    .sort((a, b) => b.value - a.value)
    .map((r) => ({ [groupBy]: r.key, [metric]: r.value }) as JsonObject);
  return {
    columns: [{ key: groupBy, label: label(groupBy), type: "string" }, measureColumn(metric, agg)],
    rows,
    dataVersion: DATA_VERSION,
  };
}

export function trend(args: JsonObject): TabularData {
  const time = COLUMNS.time;
  if (time == null) throw new Error("trend needs a time column; this dataset has none");
  const granularity = (str(args["granularity"]) ?? "month") as Granularity;
  const metric = metricOf(args);
  const agg = aggOf(args);
  const rows = aggregate(filterRows(args), (row) => bucket(row[time] ?? null, granularity), metric, agg)
    .sort((a, b) => a.key.localeCompare(b.key))
    .map((r) => ({ [granularity]: r.key, [metric]: r.value }) as JsonObject);
  return {
    columns: [{ key: granularity, label: label(granularity), type: "string" }, measureColumn(metric, agg)],
    rows,
    dataVersion: DATA_VERSION,
  };
}

export function records(args: JsonObject): TabularData {
  const limit = Math.min(500, Math.max(1, num(args["limit"]) ?? 100));
  const columns: TabularColumn[] = [
    ...COLUMNS.dimensions.map((d) => ({ key: d, label: label(d), type: "string" as const })),
    ...(COLUMNS.time != null ? [{ key: COLUMNS.time, label: label(COLUMNS.time), type: "string" as const }] : []),
    ...COLUMNS.measures.map((m) => ({ key: m, label: label(m), type: "number" as const })),
  ];
  const rows = filterRows(args).slice(0, limit).map((row) => Object.fromEntries(columns.map((c) => [c.key, row[c.key] ?? null])) as JsonObject);
  return { columns, rows, dataVersion: DATA_VERSION, total: ROWS.length };
}

export const OPERATIONS = { summary, trend, records } as const;

/** Column metadata only (no rows): what composer's chart-kind rules and props filling see (reference passing). */
export function shapeOf(op: string, args: JsonObject): DataShape | null {
  if (!Object.hasOwn(OPERATIONS, op)) return null;
  if (op === "trend" && COLUMNS.time == null) return null;
  const { columns } = OPERATIONS[op as keyof typeof OPERATIONS](args);
  return {
    columns: columns.map((c) => ({
      name: c.key,
      type: c.type,
      role: c.type === "number" ? "measure" : op === "trend" && c.key !== metricOf(args) ? "time" : "dimension",
    })),
    rowCountHint: ROWS.length,
  };
}

export function createDomainPort(): DomainPort {
  const names = Object.keys(OPERATIONS).filter((op) => op !== "trend" || COLUMNS.time != null);
  return {
    async listOperations(): Promise<OperationDescriptor[]> {
      return names.map((name) => ({ name, description: \`\${name} query over the \${label(COLUMNS.source)} data\`, resultShape: shapeOf(name, {}) ?? undefined }));
    },
    // InvocationContext (principal / capability) is intentionally not consumed: this generated port has
    // no per-principal data filtering, so it implements the 2-argument subset of DomainPort.invoke.
    async invoke(op: string, args: JsonObject): Promise<unknown> {
      if (!names.includes(op)) throw new Error(\`unknown operation: \${op}\`);
      return OPERATIONS[op as keyof typeof OPERATIONS](args);
    },
  };
}
`;

export const FIXED_SPECS_TEMPLATE = `import type { FixedSpecSource } from "@kohaku-ui/composer";
import { type CanonicalIntent, type ComponentNode, type QueryHandle, SPEC_VERSION, type UISpec } from "@kohaku-ui/spec-core";
import { COLUMNS } from "./dataset.js";
import { label } from "./domain-port.js";

/**
 * L0 fixed Specs: "app UI is a solidified L1 Spec". \`__SOURCE__.summary\` never goes through the LLM — this template
 * builds the Spec deterministically (adoption-ladder Step 0). Add more views here as they stabilize, or let the
 * fixation pipeline (Step 2) pin L1 output for you.
 */
export function createFixedSpecs(): FixedSpecSource {
  const builders: Record<string, (intent: CanonicalIntent, refs: QueryHandle[]) => UISpec> = {
    "__SOURCE__.summary": summaryView,
  };
  return {
    async lookup(intent) {
      return builders[intent.canonical] ?? null;
    },
  };
}

function summaryView(intent: CanonicalIntent, refs: QueryHandle[]): UISpec {
  const p = intent.params;
  const groupBy = String(p["groupBy"] ?? COLUMNS.dimensions[0]);
  const metric = String(p["metric"] ?? COLUMNS.measures[0] ?? "count");
  const agg = String(p["agg"] ?? "sum");
  const ref = refs[0]!.uri;
  const title = \`\${metric === "count" ? "Row count" : \`\${agg === "avg" ? "Average" : "Total"} \${label(metric).toLowerCase()}\`} by \${label(groupBy).toLowerCase()}\`;
  const components: ComponentNode[] = [
    { id: "root", type: "layout.stack", props: { direction: "vertical", gap: "md" }, children: ["t", "c", "g"] },
    { id: "t", type: "text.heading", props: { level: 2, text: title } },
    { id: "c", type: "presentChart", props: { kind: "bar", x: groupBy, y: metric }, data: { $ref: ref } },
    { id: "g", type: "presentSpreadsheet", props: { editable: false }, data: { $ref: ref } },
  ];
  return {
    kohaku: SPEC_VERSION,
    intent,
    dataVersion: "template",
    components,
    events: [],
    provenance: { tier: "L0", composedBy: "fixed-spec-template", cache: "miss" },
  };
}
`;

export const SERVER_PORTS_TEMPLATE = `import { defaultGeneratorVersion } from "@kohaku-ui/composer";
import { createKohakuHost, type KohakuHost } from "@kohaku-ui/host";
import type { LlmPort } from "@kohaku-ui/llm";
import type { AuthzPort, StoragePort } from "@kohaku-ui/spec-core";
import { DATA_VERSION } from "./dataset.js";
import { createDomainPort, shapeOf } from "./domain-port.js";
import { createFixedSpecs } from "./fixed-specs.js";
import { INTENT_DEFINITIONS, SOURCE } from "./intents.js";

export interface PortDeps {
  llm: LlmPort;
  storage?: StoragePort;
  authz?: AuthzPort;
}

/**
 * Wires the generated project onto \`createKohakuHost()\` (see @kohaku-ui/host's README) — the defaults
 * (in-memory storage, HMAC capabilities, the LLM-backed SemanticPort) are starting points; replace any of
 * them with your product's own implementation (the contract is @kohaku-ui/spec-core's ports.ts). The
 * capability secret is resolved from KOHAKU_CAPABILITY_SECRET by createKohakuHost itself (see .env.example);
 * it throws if neither that env var nor \`deps.authz\` is set.
 *
 * Kept separate from app.ts (which adds the REST-specific facet-views / health routes) so any other front
 * door built on the same Ports -- an MCP server (see server/mcp-server.ts if you generated one with
 * \`--mcp\`), a script, a test -- builds the exact same host without importing Hono routes it does not need.
 */
export function createPorts(deps: PortDeps): KohakuHost {
  return createKohakuHost({
    domain: createDomainPort(),
    querySource: SOURCE,
    llm: deps.llm,
    storage: deps.storage,
    authz: deps.authz,
    intents: INTENT_DEFINITIONS.map((d) => d.toIntentDef()),
    dataVersion: () => DATA_VERSION,
    describeShape: (ref) => shapeOf(ref.path, ref.params),
    policy: {
      // Step 0: the summary view is an L0 fixed Spec. Step 1: everything else is L1 (LLM). Step 2 (L2 free generation,
      // promotion, fixation) is off — see README.md for how to enable it.
      fixedSpecs: createFixedSpecs(),
      allowL2: false,
      generatorVersion: defaultGeneratorVersion(deps.llm),
    },
    // Set KOHAKU_DEBUG=1 (see .env.example) for the full cause chain + stack trace on every logged failure,
    // instead of a one-line summary -- useful when a compose falls back and you need to know why.
    debug: process.env["KOHAKU_DEBUG"] === "1",
  });
}
`;

export const APP_TEMPLATE = `import { existsSync } from "node:fs";
import type { ComposeContext } from "@kohaku-ui/composer";
import type { Hono } from "hono";
import { DATA_VERSION } from "./dataset.js";
import { INTENT_DEFINITIONS } from "./intents.js";
import { createPorts, type PortDeps } from "./ports.js";

export type AppDeps = PortDeps;

/**
 * The REST front door: server/ports.ts's createPorts builds the host (Ports + compose), and this adds the
 * two extra routes the generated dashboard uses (facet-views for the selector UI, health for a smoke check).
 */
export function createApp(deps: AppDeps): { app: Hono; composeCtx: ComposeContext } {
  // Load .env here too (not just in server/main.ts): this function is also called directly by
  // test/golden.test.ts and by anyone scripting against the generated project without going through
  // main.ts, and it must see the same KOHAKU_CAPABILITY_SECRET either way. process.loadEnvFile never
  // overrides a variable already present in the environment, so calling it more than once is harmless.
  if (existsSync(".env")) process.loadEnvFile(".env");
  const { app, compose } = createPorts(deps);
  // Facet descriptors for the dashboard's selectors, derived from the same Intent definitions (no codegen step).
  app.get("/api/app/facet-views", (c) => c.json({ views: INTENT_DEFINITIONS.map((d) => d.toFacetView()).filter((v) => v.facets.length > 0) }));
  app.get("/api/health", (c) => c.json({ ok: true, llm: { provider: deps.llm.provider, model: deps.llm.modelId }, dataVersion: DATA_VERSION }));
  return { app, composeCtx: compose };
}
`;

export const MAIN_TEMPLATE = `import { existsSync } from "node:fs";
import { serve } from "@hono/node-server";
import { createLlmFromEnv } from "@kohaku-ui/llm";
import { createApp } from "./app.js";

if (existsSync(".env")) process.loadEnvFile(".env");

// Without an API key the L0 view (the summary dashboard) still renders; chat and the L1 views need one — see README.md.
const llm = createLlmFromEnv();
const { app } = createApp({ llm });
const port = Number(process.env["PORT"] ?? 8787);
serve({ fetch: app.fetch, port }, (info) => {
  console.log(\`kohaku host: http://localhost:\${info.port}/api/kohaku (LLM: \${llm.provider} / \${llm.modelId})\`);
});
`;

export const WEB_MAIN_TEMPLATE = `import { createKohakuClient, type ComposeView } from "@kohaku-ui/client";
import { createBindingClient } from "@kohaku-ui/data-binding";
import { defaultLightTheme } from "@kohaku-ui/renderer-core";
import { RendererProvider, SpecView, type SurfaceEvent } from "@kohaku-ui/renderer-react";
import { createCoreRegistry } from "@kohaku-ui/renderer-react/core";
import { type ReactNode, StrictMode, useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";

const client = createKohakuClient({ baseUrl: "/api/kohaku" });
const impls = createCoreRegistry();

interface FacetView {
  intent: string;
  label: string;
  facets: { key: string; label: string; options: { value: string; label: string }[]; allowEmpty?: string }[];
}

/** Renders a composed Spec. Both surfaces (dashboard and chat) go through this, so identical Specs render identically. */
function Surface(props: { view: ComposeView; onEvent?: (e: SurfaceEvent) => void }): ReactNode {
  const binding = useMemo(() => createBindingClient({ baseUrl: "/api/kohaku", capability: props.view.capability }), [props.view.capability]);
  const value = useMemo(
    () => ({ impls, binding, theme: defaultLightTheme, ...(props.onEvent != null ? { onEvent: props.onEvent } : {}) }),
    [binding, props.onEvent],
  );
  return (
    <RendererProvider value={value}>
      <SpecView spec={props.view.spec} />
    </RendererProvider>
  );
}

function Dashboard(): ReactNode {
  const [views, setViews] = useState<FacetView[]>([]);
  const [intent, setIntent] = useState<string | null>(null);
  const [params, setParams] = useState<Record<string, string>>({});
  const [view, setView] = useState<ComposeView | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch("/api/app/facet-views")
      .then((r) => r.json())
      .then((json: { views: FacetView[] }) => {
        setViews(json.views);
        setIntent(json.views[0]?.intent ?? null);
      })
      .catch((e) => setError(String(e)));
  }, []);

  useEffect(() => {
    if (intent == null) return;
    setError(null);
    client
      .compose({ input: { kind: "gui", action: "view.select", params: { intent, ...params } }, session: { surface: "web" } })
      .then(setView)
      .catch((e) => setError(e instanceof Error ? e.message : String(e)));
  }, [intent, params]);

  const current = views.find((v) => v.intent === intent);
  const onEvent = (e: SurfaceEvent): void => {
    if (view == null) return;
    client
      .sendEvent({ intent: { canonical: view.spec.intent.canonical, params: view.spec.intent.params }, on: e.on, payload: e.payload, session: { surface: "web" } })
      .then(setView)
      .catch((err) => setError(err instanceof Error ? err.message : String(err)));
  };

  return (
    <div style={{ display: "grid", gridTemplateColumns: "220px 1fr", gap: 24 }}>
      <aside style={{ display: "flex", flexDirection: "column", gap: 12 }}>
        <label>
          View
          <select value={intent ?? ""} onChange={(e) => { setIntent(e.target.value); setParams({}); }}>
            {views.map((v) => <option key={v.intent} value={v.intent}>{v.label}</option>)}
          </select>
        </label>
        {current?.facets.map((f) => (
          <label key={f.key}>
            {f.label}
            <select value={params[f.key] ?? ""} onChange={(e) => setParams({ ...params, [f.key]: e.target.value })}>
              {f.allowEmpty != null && <option value="">{f.allowEmpty}</option>}
              {f.options.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}
            </select>
          </label>
        ))}
      </aside>
      <main>
        {error != null && <p style={{ color: "#b91c1c" }}>{error}</p>}
        {view != null && (
          <>
            <p style={{ fontSize: 12, color: "#6b7280" }}>
              {view.spec.provenance.tier} · cache:{view.spec.provenance.cache}
            </p>
            <Surface view={view} onEvent={onEvent} />
          </>
        )}
      </main>
    </div>
  );
}

function Chat(): ReactNode {
  const [text, setText] = useState("");
  const [items, setItems] = useState<{ question: string; intent?: string; view?: ComposeView; error?: string }[]>([]);
  const ask = async (): Promise<void> => {
    const question = text.trim();
    if (question === "") return;
    setText("");
    setItems((prev) => [...prev, { question }]);
    try {
      const { intent } = await client.normalizeIntent({ input: { kind: "nl", text: question }, session: { surface: "chat" } });
      const view = await client.compose({ intent: { canonical: intent.canonical, params: intent.params }, session: { surface: "chat" } });
      setItems((prev) => prev.map((it) => (it.question === question && it.view == null ? { ...it, intent: intent.canonical, view } : it)));
    } catch (e) {
      const error = e instanceof Error ? e.message : String(e);
      setItems((prev) => prev.map((it) => (it.question === question && it.view == null ? { ...it, error } : it)));
    }
  };
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
      {items.map((it, i) => (
        <div key={i}>
          <p><strong>You:</strong> {it.question}</p>
          {it.intent != null && <p style={{ fontSize: 12, color: "#6b7280" }}>→ {it.intent}</p>}
          {it.error != null && <p style={{ color: "#b91c1c" }}>{it.error}</p>}
          {it.view != null && <Surface view={it.view} />}
        </div>
      ))}
      <form onSubmit={(e) => { e.preventDefault(); void ask(); }} style={{ display: "flex", gap: 8 }}>
        <input value={text} onChange={(e) => setText(e.target.value)} placeholder="Ask about your data…" style={{ flex: 1, padding: 8 }} />
        <button type="submit">Ask</button>
      </form>
    </div>
  );
}

function App(): ReactNode {
  const [tab, setTab] = useState<"dashboard" | "chat">("dashboard");
  return (
    <div style={{ fontFamily: "system-ui, sans-serif", padding: 24, maxWidth: 1100, margin: "0 auto" }}>
      <nav style={{ display: "flex", gap: 8, marginBottom: 16 }}>
        <button type="button" onClick={() => setTab("dashboard")} disabled={tab === "dashboard"}>Dashboard</button>
        <button type="button" onClick={() => setTab("chat")} disabled={tab === "chat"}>Chat</button>
      </nav>
      {tab === "dashboard" ? <Dashboard /> : <Chat />}
    </div>
  );
}

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
`;

export const INDEX_HTML_TEMPLATE = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>__NAME__ · kohaku</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/web/main.tsx"></script>
  </body>
</html>
`;

export const VITE_CONFIG_TEMPLATE = `import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [react()],
  server: { port: 5173, proxy: { "/api": \`http://localhost:\${process.env["PORT"] ?? 8787}\` } },
});
`;

export const TSCONFIG_TEMPLATE = `{
  "compilerOptions": {
    "target": "ES2023",
    "lib": ["ES2023", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "moduleResolution": "bundler",
    "jsx": "react-jsx",
    "strict": true,
    "verbatimModuleSyntax": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "noEmit": true,
    "types": ["node", "vite/client"]
  },
  "include": ["server", "web", "test", "vite.config.ts"]
}
`;

export const DEV_SCRIPT_TEMPLATE = `// Runs the API (tsx watch) and the web dev server (vite) together; Ctrl-C stops both.
import { spawn } from "node:child_process";

const children = [
  spawn("npx", ["tsx", "watch", "server/main.ts"], { stdio: "inherit", shell: process.platform === "win32" }),
  spawn("npx", ["vite"], { stdio: "inherit", shell: process.platform === "win32" }),
];
const stop = () => {
  for (const child of children) child.kill("SIGINT");
};
process.on("SIGINT", stop);
process.on("SIGTERM", stop);
for (const child of children) child.on("exit", (code) => { if (code != null && code !== 0) { stop(); process.exitCode = code; } });
`;

export const GOLDEN_TEST_TEMPLATE_INIT = `/**
 * Golden Spec regression (generated by kohaku init). Pins the structure of Intent → Spec; LLM output jitter
 * (provenance / hashes / component ids) is normalized away by runGolden. No LLM is used: fixtures for L1 views
 * carry the model's raw drafts (FakeLlm), the L0 summary fixture needs none.
 *
 * Generating / updating \`expected\`: KOHAKU_GOLDEN_UPDATE=1 npm test writes each fixture's expected back from the actual
 * compose output (deterministic, no LLM); review the diff and commit. A fixture whose expected is still null fails
 * until you do that. Never run update mode in CI.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { type ComposeContext, type ComposeInput, compose } from "@kohaku-ui/composer";
import { type GoldenCase, runGolden } from "@kohaku-ui/evals";
import { FakeLlm } from "@kohaku-ui/llm/fake";
import type { UISpec } from "@kohaku-ui/spec-core";
import { describe, expect, it } from "vitest";
import { createApp } from "../server/app.js";

const GOLDEN_DIR = join(dirname(fileURLToPath(import.meta.url)), "golden");
const UPDATE = process.env["KOHAKU_GOLDEN_UPDATE"] === "1";
if (UPDATE && process.env["CI"] != null) {
  throw new Error("KOHAKU_GOLDEN_UPDATE=1 must not run in CI (it rewrites goldens instead of asserting them)");
}

interface GoldenFixture {
  name: string;
  input: ComposeInput;
  drafts: unknown[];
  expected: UISpec | null;
}

function makeContext(drafts: unknown[]): ComposeContext {
  return createApp({ llm: new FakeLlm({ objects: drafts }) }).composeCtx;
}

const files = existsSync(GOLDEN_DIR) ? readdirSync(GOLDEN_DIR).filter((f) => f.endsWith(".json")).sort() : [];

describe("golden regression", () => {
  for (const file of files) {
    const path = join(GOLDEN_DIR, file);
    const fixture = JSON.parse(readFileSync(path, "utf8")) as GoldenFixture;
    it(fixture.name, async () => {
      const ctx = makeContext(fixture.drafts);
      if (UPDATE) {
        const { spec } = await compose(fixture.input, ctx);
        writeFileSync(path, \`\${JSON.stringify({ ...fixture, expected: spec }, null, 2)}\\n\`);
        return;
      }
      expect(fixture.expected, \`\${file}: expected not generated. Generate it with KOHAKU_GOLDEN_UPDATE=1 npm test\`).not.toBeNull();
      const cases: GoldenCase[] = [{ name: fixture.name, input: fixture.input, expected: fixture.expected! }];
      const report = await runGolden(cases, ctx);
      const failed = report.cases.find((c) => !c.pass);
      expect(report.pass, failed ? \`golden mismatch (\${file})\\n\${failed.expected}\\n---\\n\${failed.actual}\` : undefined).toBe(true);
    });
  }
});
`;

export const ENV_EXAMPLE_TEMPLATE = `# Pick one provider. Without a key the summary dashboard (L0) still works; chat and the other views need the LLM.
KOHAKU_LLM_PROVIDER=claude
# KOHAKU_LLM_API_KEY=   # or export ANTHROPIC_API_KEY / OPENAI_API_KEY / GOOGLE_GENERATIVE_AI_API_KEY instead
# Local, no key: KOHAKU_LLM_PROVIDER=ollama KOHAKU_LLM_MODEL=gemma4:e4b

# HMAC signing secret for capability tokens. \`kohaku init\` already generated a random one into .env
# (git-ignored, not this file); set this only if you need a fixed value of your own. The server refuses
# to start without one (see server/ports.ts).
KOHAKU_CAPABILITY_SECRET=
PORT=8787

# Set to 1 for verbose error logging (the full cause chain + stack trace on every compose/request failure,
# instead of a one-line summary) -- see server/ports.ts.
# KOHAKU_DEBUG=
`;

export const GITIGNORE_TEMPLATE = `node_modules/
dist/
.env
`;

/** Appended to GITIGNORE_TEMPLATE when \`kohaku init --mcp\` generates the MCP front door. */
export const GITIGNORE_MCP_EXTRA = `.kohaku/
`;

export const MCP_SERVER_TEMPLATE = `import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { KohakuHost } from "@kohaku-ui/host";
import { attachKohakuMcp } from "@kohaku-ui/host/mcp";
import { intentToolsFromCatalog } from "@kohaku-ui/host-mcp-apps";
import { loadRendererHtml } from "@kohaku-ui/mcp-renderer";
import type { McpServer } from "@modelcontextprotocol/server";
import { INTENT_DEFINITIONS } from "./intents.js";

/**
 * Self-contained snapshot HTML (kohaku_render_snapshot, for UI-incapable hosts like Claude Code / Codex
 * CLI) is saved here, next to this file rather than under process.cwd() -- Claude Desktop launches an MCP
 * server from an arbitrary working directory, so a cwd-relative path would silently write (or fail to
 * find) files in the wrong place. Git-ignored (see .gitignore); safe to delete any time.
 */
const SNAPSHOT_DIR = join(dirname(fileURLToPath(import.meta.url)), "..", ".kohaku", "snapshots");

/**
 * Attaches the generated project's host (built by createPorts in server/ports.ts -- the same Ports and
 * compose the REST front door in server/app.ts builds on) to an MCP server, via \`@kohaku-ui/host/mcp\`'s
 * \`attachKohakuMcp\`. "Same request content -> same Spec -> same rendering" holds across both front doors
 * this way.
 *
 * The caller builds the host ONCE per process and passes it in: the Spec cache, fixations, lineage and
 * single-flight state all live in that host's storage, so building a new one per MCP exchange would throw
 * them away and regenerate every L1 view on each call.
 *
 * \`rendererHtml\` is \`@kohaku-ui/mcp-renderer\`'s pre-built, dependency-free core renderer bundle -- swap it
 * for your own build (see that package's README's "./boot" section) once you have product-specific
 * component implementations to bake in. \`intentTools\` exposes every Intent in server/intents.ts as a typed
 * MCP tool (e.g. \`sales_summary\` for a project whose data source is named "sales") in addition to the
 * generic \`kohaku_compose\`.
 */
export function attachMcpServer(server: McpServer, host: KohakuHost): void {
  attachKohakuMcp(server, host, {
    rendererHtml: loadRendererHtml,
    intentTools: intentToolsFromCatalog(INTENT_DEFINITIONS.map((d) => d.toToolSource())),
    snapshotWriter: async (fileName, html) => {
      await mkdir(SNAPSHOT_DIR, { recursive: true });
      const path = join(SNAPSHOT_DIR, fileName);
      await writeFile(path, html, "utf8");
      return path;
    },
  });
}
`;

export const MCP_STDIO_TEMPLATE = `import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createLlmFromEnv } from "@kohaku-ui/llm";
import { McpServer } from "@modelcontextprotocol/server";
import { StdioServerTransport } from "@modelcontextprotocol/server/stdio";
import { attachMcpServer } from "./mcp-server.js";
import { createPorts } from "./ports.js";

/**
 * MCP server (stdio) for terminal / desktop hosts (Claude Desktop, Claude Code, Codex CLI, ...). Registered
 * with Claude Desktop by \`npm run mcp:claude-desktop\` (see scripts/claude-desktop.mjs); run directly with
 * \`npm run mcp\`.
 *
 * .env is resolved next to this file (not process.cwd()) because Claude Desktop launches MCP servers from
 * an arbitrary working directory -- a cwd-relative check (server/app.ts's approach) would silently miss it.
 */
const ENV_PATH = join(dirname(fileURLToPath(import.meta.url)), "..", ".env");
if (existsSync(ENV_PATH)) process.loadEnvFile(ENV_PATH);

const llm = createLlmFromEnv();
const server = new McpServer({ name: "__NAME__", version: "0.1.0" });
attachMcpServer(server, createPorts({ llm }));

await server.connect(new StdioServerTransport());
console.error("__NAME__ MCP server: ready (stdio)");
`;

export const MCP_HTTP_TEMPLATE = `import { existsSync } from "node:fs";
import { createServer as createHttpServer, type IncomingMessage } from "node:http";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createLlmFromEnv } from "@kohaku-ui/llm";
import { hostHeaderValidation, originValidation, toNodeHandler } from "@modelcontextprotocol/node";
import { createMcpHandler, McpServer } from "@modelcontextprotocol/server";
import { attachMcpServer } from "./mcp-server.js";
import { createPorts } from "./ports.js";

/**
 * MCP server (Streamable HTTP) for remote / browser-based hosts (claude.ai, ChatGPT) -- claude.ai and
 * ChatGPT can only connect through a remote MCP connector, not stdio. Run with \`npm run mcp:http\`
 * (default :8788, override with PORT).
 *
 * No authentication (a local demo default): put this behind your own auth (e.g. @kohaku-ui/authz-jwt) before
 * exposing it beyond localhost -- see https://github.com/yosuque/kohaku/blob/main/docs/user-guide.md#6-embedding-it-into-your-own-product
 * Until then it defends itself against a web page in your browser driving it (DNS rebinding / CSRF): the Host
 * header must be localhost / 127.0.0.1 / [::1], and a request that carries an Origin header (browsers always
 * do) must come from one of those too. Clients that send no Origin (Claude Desktop, MCP connectors calling
 * from a server) are unaffected. Behind a tunnel or a reverse proxy the Host is your public name -- allow it
 * with KOHAKU_MCP_ALLOWED_HOSTS=name1,name2 (hostnames, no port); allow a browser-based caller's origin with
 * KOHAKU_MCP_ALLOWED_ORIGINS=name1,name2 (hostnames, no scheme or port).
 *
 * .env is resolved next to this file, the same reasoning as server/mcp.ts.
 */
const ENV_PATH = join(dirname(fileURLToPath(import.meta.url)), "..", ".env");
if (existsSync(ENV_PATH)) process.loadEnvFile(ENV_PATH);

const llm = createLlmFromEnv();
const port = Number(process.env["PORT"] ?? 8788);

// The host (Ports + Spec cache + lineage) is built ONCE for the whole process. The handler below builds a
// fresh McpServer per exchange, but every one of them attaches to this same host -- building a new host per
// request would start each call with empty storage: no Spec cache, no fixation, no lineage, so an L1 view
// would be regenerated by the LLM every time.
const host = createPorts({ llm });

const LOCAL_HOSTNAMES = ["localhost", "127.0.0.1", "[::1]"];
const extraNames = (value: string | undefined): string[] =>
  (value ?? "").split(",").map((name) => name.trim()).filter((name) => name !== "");
const validateHost = hostHeaderValidation([...LOCAL_HOSTNAMES, ...extraNames(process.env["KOHAKU_MCP_ALLOWED_HOSTS"])]);
const validateOrigin = originValidation([...LOCAL_HOSTNAMES, ...extraNames(process.env["KOHAKU_MCP_ALLOWED_ORIGINS"])]);

/** JSON-RPC bodies are a few KB; anything past this is refused before it piles up in memory. */
const MAX_BODY_BYTES = 4 * 1024 * 1024;

class BodyTooLargeError extends Error {}

async function readJsonBody(req: IncomingMessage): Promise<unknown> {
  const declared = Number(req.headers["content-length"]);
  if (Number.isFinite(declared) && declared > MAX_BODY_BYTES) throw new BodyTooLargeError();
  const chunks: Buffer[] = [];
  let total = 0;
  for await (const chunk of req) {
    total += (chunk as Buffer).byteLength;
    if (total > MAX_BODY_BYTES) throw new BodyTooLargeError();
    chunks.push(chunk as Buffer);
  }
  const raw = Buffer.concat(chunks).toString("utf8").trim();
  return raw === "" ? undefined : JSON.parse(raw);
}

// Stateless serving (MCP protocol version 2026-07-28 removed protocol-level sessions): a fresh McpServer
// per exchange, all attached to the one host above.
const mcpHandler = createMcpHandler(() => {
  const server = new McpServer({ name: "__NAME__", version: "0.1.0" });
  attachMcpServer(server, host);
  return server;
});
const handleMcp = toNodeHandler(mcpHandler);

const httpServer = createHttpServer(async (req, res) => {
  // Each guard has already answered with a 403 when it returns false.
  if (!validateHost(req, res)) return;
  if (!validateOrigin(req, res)) return;
  // Only an Origin that passed validateOrigin is ever echoed back -- never "*".
  const origin = req.headers.origin;
  if (origin != null) {
    res.setHeader("Access-Control-Allow-Origin", origin);
    res.setHeader("Vary", "Origin");
    res.setHeader("Access-Control-Allow-Methods", "GET, POST, DELETE, OPTIONS");
    res.setHeader("Access-Control-Allow-Headers", "Content-Type, Accept, Authorization, mcp-protocol-version");
  }
  if (req.method === "OPTIONS") {
    res.writeHead(204).end();
    return;
  }
  try {
    if (req.method === "POST") {
      // Read the body under the size cap ourselves and hand it to the adapter as the parsed body.
      let body: unknown;
      try {
        body = await readJsonBody(req);
      } catch (err) {
        const tooLarge = err instanceof BodyTooLargeError;
        res.setHeader("Connection", "close");
        res.writeHead(tooLarge ? 413 : 400, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ jsonrpc: "2.0", error: { code: tooLarge ? -32000 : -32700, message: tooLarge ? "Request body too large" : "Parse error" }, id: null }));
        return;
      }
      await handleMcp(req, res, body);
      return;
    }
    await handleMcp(req, res);
  } catch (err) {
    console.error("[mcp-http] request failed:", err);
    if (!res.headersSent) res.writeHead(500).end();
  }
});

// Closing the server also tears down the handler (aborts in-flight exchanges, closes their McpServer instances).
httpServer.on("close", () => {
  void mcpHandler.close();
});

// Bind to 127.0.0.1 by default (local only); override with HOST for LAN/container exposure.
const bindHost = process.env["HOST"] ?? "127.0.0.1";
httpServer.listen(port, bindHost, () => {
  console.log(\`__NAME__ MCP server: ready (Streamable HTTP) at http://\${bindHost}:\${port}/mcp\`);
});
`;

/**
 * Copied verbatim into every \`kohaku init --mcp\` project (the template itself is not parameterized -- it
 * reads the sibling claude_desktop_config.example.json this same init run wrote, and \`npm run
 * mcp:claude-desktop\` is the only thing that ever invokes it). Backs up the user's existing Claude Desktop config to \`.bak\` and merges
 * in this project's mcpServers entry, or (with --print) just prints the merged result without writing
 * anything. **The real config is only ever touched by a person explicitly running this script** -- kohaku
 * init itself never runs it.
 */
export const CLAUDE_DESKTOP_SCRIPT_TEMPLATE = `#!/usr/bin/env node
/**
 * Registers this project's MCP server with Claude Desktop: merges the entry from
 * claude_desktop_config.example.json (generated alongside this script by \`kohaku init --mcp\`) into Claude
 * Desktop's own config file, after backing the existing file up to \`<config>.bak\`.
 *
 * Usage:
 *   npm run mcp:claude-desktop            # back up (if a config already exists) + write
 *   npm run mcp:claude-desktop -- --print # print the merged result; write nothing
 *
 * Restart Claude Desktop afterwards to pick up the change.
 *
 * The config file location is auto-detected per OS (see claudeDesktopConfigPath) -- override it with
 * --config <path> or the KOHAKU_CLAUDE_DESKTOP_CONFIG environment variable if Claude Desktop's config lives
 * somewhere nonstandard on your machine.
 */
import { existsSync, mkdirSync, readFileSync, realpathSync, writeFileSync } from "node:fs";
import { homedir, platform } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const PROJECT_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const EXAMPLE_CONFIG_PATH = join(PROJECT_ROOT, "claude_desktop_config.example.json");

/**
 * Claude Desktop's own config file path for the current platform. \`env\`/\`plat\` are injectable (tests pass
 * a temporary HOME so this never touches a real user's config).
 */
export function claudeDesktopConfigPath(env = process.env, plat = platform()) {
  const home = env.HOME ?? homedir();
  if (plat === "darwin") {
    return join(home, "Library", "Application Support", "Claude", "claude_desktop_config.json");
  }
  if (plat === "win32") {
    return join(env.APPDATA ?? join(home, "AppData", "Roaming"), "Claude", "claude_desktop_config.json");
  }
  return join(env.XDG_CONFIG_HOME ?? join(home, ".config"), "Claude", "claude_desktop_config.json");
}

/**
 * Reads a JSON config file; an absent file reads as {} (nothing to merge with / into yet). A file that
 * exists but is not valid JSON, is not a JSON object at the top level (e.g. an array or null), or has a
 * non-object "mcpServers" field, throws instead of guessing -- silently treating a malformed Claude Desktop
 * config as {} would merge into an empty object and, once written, drop every one of the person's other
 * registered MCP servers.
 */
export function readJsonConfig(path) {
  if (!existsSync(path)) return {};
  let parsed;
  try {
    parsed = JSON.parse(readFileSync(path, "utf8"));
  } catch (e) {
    throw new Error(
      \`\${path} is not valid JSON (\${e instanceof Error ? e.message : String(e)}). Nothing was written -- fix or remove the file and try again.\`,
    );
  }
  if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error(
      \`\${path} must be a JSON object at the top level. Nothing was written -- fix or remove the file and try again.\`,
    );
  }
  if (
    "mcpServers" in parsed &&
    (parsed.mcpServers === null || typeof parsed.mcpServers !== "object" || Array.isArray(parsed.mcpServers))
  ) {
    throw new Error(
      \`\${path}'s "mcpServers" field must be a JSON object. Nothing was written -- fix or remove the file and try again.\`,
    );
  }
  return parsed;
}

/**
 * Pure merge (no I/O): overlays \`example\`'s mcpServers entries onto \`target\`'s. Every other top-level key
 * in \`target\`, and every mcpServers entry \`example\` does not declare, is preserved untouched -- this never
 * clobbers a person's other MCP server registrations. Running this twice with the same \`example\` is a
 * no-op the second time (the merged result already equals \`example\`'s entries, so re-merging changes
 * nothing), which is what makes \`npm run mcp:claude-desktop\` safe to run more than once.
 */
export function mergeMcpConfig(target, example) {
  return {
    ...target,
    mcpServers: {
      ...(target.mcpServers ?? {}),
      ...(example.mcpServers ?? {}),
    },
  };
}

/**
 * Does the actual read-merge-(print-or-write) work, parameterized over env/plat (see
 * claudeDesktopConfigPath) so it is directly callable with a temporary HOME from a test, with no child
 * process and no risk of ever touching a real Claude Desktop config. Returns what happened rather than
 * just logging it, so a test can assert on configPath / merged / backedUp directly.
 *
 * configPathOverride bypasses claudeDesktopConfigPath's own per-OS detection entirely when given (real
 * users never need it -- the per-OS default is what they want). It exists so a test driving this through a
 * real subprocess (main(), below) can pin the exact config path independent of the CI host's actual
 * platform: env/plat alone are not enough there, since a real child process always reports its own real
 * platform() regardless of what env.HOME is set to.
 */
export function syncClaudeDesktopConfig({
  env = process.env,
  plat = platform(),
  printOnly = false,
  configPathOverride,
} = {}) {
  const example = readJsonConfig(EXAMPLE_CONFIG_PATH);
  const configPath = configPathOverride ?? claudeDesktopConfigPath(env, plat);
  const merged = mergeMcpConfig(readJsonConfig(configPath), example);

  if (printOnly) {
    return { configPath, merged, wrote: false, backedUp: false };
  }

  mkdirSync(dirname(configPath), { recursive: true });
  const backedUp = existsSync(configPath);
  if (backedUp) {
    writeFileSync(\`\${configPath}.bak\`, readFileSync(configPath, "utf8"));
  }
  writeFileSync(configPath, \`\${JSON.stringify(merged, null, 2)}\n\`);
  return { configPath, merged, wrote: true, backedUp };
}

/**
 * The value following a literal "--config" in argv, if present (e.g. ["--config", "/tmp/x.json"] -> the
 * path). Overrides the per-OS default -- mainly useful for tests driving this script as a real subprocess,
 * where env.HOME alone cannot pin the config path independent of the host's actual platform().
 */
function configPathArg(argv) {
  const i = argv.indexOf("--config");
  return i === -1 ? undefined : argv[i + 1];
}

function main() {
  const printOnly = process.argv.includes("--print");
  const configPathOverride = configPathArg(process.argv) ?? process.env.KOHAKU_CLAUDE_DESKTOP_CONFIG;
  let result;
  try {
    result = syncClaudeDesktopConfig({ printOnly, configPathOverride });
  } catch (e) {
    console.error(\`claude-desktop.mjs: \${e instanceof Error ? e.message : String(e)}\`);
    process.exitCode = 1;
    return;
  }
  if (printOnly) {
    console.log(JSON.stringify(result.merged, null, 2));
    return;
  }
  console.log(\`Registered with Claude Desktop: \${result.configPath}\`);
  console.log("Restart Claude Desktop to pick up the change.");
}

// Run only when launched directly (npm run mcp:claude-desktop); importing this module (e.g. from a test)
// has no side effects beyond the pure/read-only exports above. realpathSync matters here: on macOS, the
// system temp directory is reached through a symlink (/tmp -> /private/tmp, /var -> /private/var), so
// process.argv[1] (the literal path node was invoked with) and import.meta.url (already resolved through
// the symlink by the module loader) would otherwise never compare equal, silently skipping main()
// entirely -- exactly the failure this comment is here to prevent a future edit from reintroducing.
let isMain = false;
if (process.argv[1] !== undefined) {
  try {
    isMain = import.meta.url === pathToFileURL(realpathSync(process.argv[1])).href;
  } catch {
    isMain = false;
  }
}
if (isMain) main();
`;
