import { createCoreRegistry } from "@kohaku-ui/renderer-react/core";
import { registerSalesImpls } from "@kohaku-ui-sample/web/renderer-impls";
import { describe, expect, it } from "vitest";

/**
 * Regression guard that the MCP shared renderer (renderer/main.tsx) registers the same sales-domain
 * implementations as the Web surface. main.tsx builds the registry with registerSalesImpls(createCoreRegistry())
 * (the crux of Strategy A). Without it, the sales.kpiCard in the L0 fixed Spec (kpi_overview / target_attainment)
 * becomes "unimplemented component type: sales.kpiCard" on the MCP side / snapshot. Verified directly against the
 * real registry (intent-tools.test.ts stubs out the renderer HTML, so it cannot verify this layer).
 */
describe("sample-mcp: sales domain parts are registered in the shared renderer registry", () => {
  it("createCoreRegistry() + registerSalesImpls resolves sales.kpiCard / sales.calendarHeatmap", () => {
    const registry = registerSalesImpls(createCoreRegistry());

    // A component generated by the L0 fixed Spec. The regression point where, if unregistered, it became "unimplemented component type" on the MCP side.
    expect(registry.get("sales.kpiCard")).toBeTypeOf("function");
    // Native implementation of a promoted component. Shares the same implementation as the Web app (prevents version/type drift from registering only one side).
    expect(registry.get("sales.calendarHeatmap")).toBeTypeOf("function");

    // The core-catalog components remain registered (an overlay, not a replacement).
    expect(registry.get("presentChart")).toBeTypeOf("function");
    expect(registry.get("presentSpreadsheet")).toBeTypeOf("function");
  });
});
