/**
 * Emits the GUI facet descriptors (FacetView) from INTENT_DEFINITIONS (catalog.ts) to JSON.
 * Run: pnpm intents:emit (= pnpm --filter @kohaku-ui-sample/api run intents:emit)
 *
 * The single source is sample-api's INTENT_DEFINITIONS. sample-web imports this JSON as "framework-independent data"
 * (keeping it independent of server code = the toQueries / drilldown closures).
 * The output is deterministic and committed — regenerate and commit when you change catalog.ts's facet declarations
 * (CI checks for drift via the diff between the regenerated result and the committed output; the same discipline as generate-schemas).
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { INTENT_DEFINITIONS } from "../src/intents/catalog.js";

// Emit directly to sample-web's src (web does not depend on api and imports local JSON within its own package).
const OUT_DIR = join(dirname(fileURLToPath(import.meta.url)), "../../sample-web/src/generated");

// Emit only Intents that declare facets as dashboard views
// (Intents without facets, such as sales.custom, are not shown in the GUI view).
const views = INTENT_DEFINITIONS.map((d) => d.toFacetView()).filter((v) => v.facets.length > 0);

mkdirSync(OUT_DIR, { recursive: true });
const json =
  JSON.stringify(
    {
      "//":
        "Generated by `pnpm intents:emit` (apps/sample-api's INTENT_DEFINITIONS is the single source). " +
        "Do not edit by hand; regenerate and commit when you change catalog.ts's facet declarations.",
      views,
    },
    null,
    2,
  ) + "\n";
writeFileSync(join(OUT_DIR, "facet-views.json"), json);

console.log(`generated: apps/sample-web/src/generated/facet-views.json (${views.length} views)`);
