"""Sample MCP server (the Python version of apps/sample-mcp/src/index.ts. stdio transport).

Because it uses the same Ports / Composition Service as sample-api, "the same request -> the same Spec as the Web app
-> the same renderer rendering" holds in external chat too. The common setup (env, create_app, recorder, attach) is
consolidated in mcp_setup.py, and this file only handles connecting to the stdio transport.

Run: cd python && uv run python -m sales_api.mcp_main
Connects over stdio to MCP clients such as Claude Desktop. For the ui:// resource, it serves the shared renderer built
on the TS side (apps/sample-mcp/dist/renderer/index.html — generated by `pnpm --filter @kohaku-ui-sample/mcp
build:renderer`). If not built, it falls back to placeholder HTML.

For remote connections (claude.ai / ChatGPT, etc.), use the Streamable HTTP entry (mcp_http.py).
"""

from __future__ import annotations

import asyncio
import sys

from .mcp_setup import create_kohaku_mcp_setup


async def main() -> None:
    try:
        from mcp.server.stdio import stdio_server
    except ImportError as err:
        raise RuntimeError(
            "Starting the MCP server requires mcp. Run `uv sync` (dev) or"
            " `pip install 'kohaku[mcp]'`."
        ) from err

    setup = await create_kohaku_mcp_setup()
    server = setup.create_server()

    print(
        f"kohaku-sales-sample MCP server: ready (stdio) / LLM: {setup.llm.provider}",
        file=sys.stderr,
    )
    async with stdio_server() as (read_stream, write_stream):
        await server.run(read_stream, write_stream, server.create_initialization_options())


if __name__ == "__main__":
    asyncio.run(main())
