import type { ImplRegistry } from "@kohaku-ui/renderer-react";
import { KpiCard } from "./KpiCard.js";
import { SalesCalendarHeatmap } from "./SalesCalendarHeatmap.js";

/**
 * The single source of truth for registering the sales-domain part implementations (outside the core catalog) into the registry.
 * Both the Web surface (SpecSurface) and the MCP shared renderer (sample-mcp/renderer/main.tsx)
 * call this function to layer the same implementations onto createCoreRegistry().
 *
 * This is what makes "the Web and MCP iframes use the same implementation for pixel parity (strategy A, docs/design.md)"
 * hold. To prevent double-managed registration (adding to one side only, leaving the other with an "unimplemented part type"),
 * the mapping of part types and versions is consolidated in this one place.
 *
 * - sales.kpiCard: the card part generated by the L0 fixed Specs (kpi_overview / target_attainment).
 * - sales.calendarHeatmap: the native implementation of a promoted part (pre-bundled). Before promotion it does not appear in the Spec.
 */
export function registerSalesImpls(registry: ImplRegistry): ImplRegistry {
  return registry
    .register("sales.kpiCard", "1.0.0", KpiCard)
    .register("sales.calendarHeatmap", "1.0.0", SalesCalendarHeatmap);
}

export { KpiCard } from "./KpiCard.js";
export { SalesCalendarHeatmap } from "./SalesCalendarHeatmap.js";
