import { type ImplRegistry, implement } from "@kohaku-ui/renderer-react";
import { salesCalendarHeatmap, salesKpiCard } from "@kohaku-ui-sample/parts";
import { KpiCard } from "./KpiCard.js";
import { SalesCalendarHeatmap } from "./SalesCalendarHeatmap.js";

/**
 * The single source of truth for registering the sales-domain part implementations (outside the core catalog) into the registry.
 * Both the Web surface (SpecSurface) and the MCP shared renderer (sample-mcp/renderer/main.tsx)
 * call this function to layer the same implementations onto createCoreRegistry().
 *
 * This is what makes "the Web and MCP iframes use the same implementation for pixel parity (strategy A, docs/design.md)"
 * hold. The type + version each part registers under comes from its ComponentDefinition in
 * @kohaku-ui-sample/parts (design.md #68) via `implement`, rather than being re-typed here as a string
 * literal — the single place that used to make double-managed registration possible (a typo or version
 * drift between this file and the catalog contribution going undetected until runtime).
 *
 * - sales.kpiCard: the card part generated by the L0 fixed Specs (kpi_overview / target_attainment).
 * - sales.calendarHeatmap: the native implementation of a promoted part (pre-bundled). Before promotion it does not appear in the Spec.
 */
export function registerSalesImpls(registry: ImplRegistry): ImplRegistry {
  return registry
    .use(implement(salesKpiCard, KpiCard))
    .use(implement(salesCalendarHeatmap, SalesCalendarHeatmap));
}

export { KpiCard } from "./KpiCard.js";
export { SalesCalendarHeatmap } from "./SalesCalendarHeatmap.js";
