import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { exportDistillationDataset } from "@kohaku-ui/evals";
import {
  type ActionParamIssue,
  type ActionParamsSchema,
  ALLOWED_ATTRS,
  ALLOWED_STYLE_PROPS,
  ALLOWED_TAGS,
  actionPayloadHash,
  type CacheKeyParts,
  cacheKey,
  canonicalStringify,
  computeIntentHash,
  computeSpecHash,
  computeStructureHash,
  decodeSeqCursor,
  encodeSeqCursor,
  type FixationRecord,
  findUnsafeActionParamKeys,
  type JsonObject,
  type LineageEventRecord,
  type LineagePage,
  type LineagePageRequest,
  type PromotionState,
  pageLineageArray,
  parseSpec,
  sha256Hex,
  validateActionParams,
} from "@kohaku-ui/spec-core";
import { describe, expect, it } from "vitest";
// Relative (not "@kohaku-ui/composer") import: spec does not declare composer as a dependency, same
// reasoning as generate-cross-language-fixtures.ts's own composer import (see that file's comment).
import {
  DEFAULT_KIT_VOCABULARY,
  type DesignSystemGuide,
  designKitPromptFragment,
  designSystemPromptFragment,
} from "../../packages/composer/src/design-system.js";
import { L2_SYSTEM_PROMPT, PROMPT_REVISION } from "../../packages/composer/src/prompt.js";
// Relative (not "@kohaku-ui/lineage") import, same reasoning as generate-cross-language-fixtures.ts's
// own lineage import.
import {
  buildEvidencePack,
  type EvidenceManifest,
  type EvidenceSource,
  importEd25519PrivateKeyPkcs8,
  importEd25519PublicKeyRaw,
  signManifest,
  verifyManifestSignature,
} from "../../packages/lineage/src/index.js";

/**
 * Cross-language golden (TS side). Pins that the TS implementation reproduces the fixture
 * (generated by scripts/generate-cross-language-fixtures.ts). The Python implementation
 * (python/kohaku/tests/spec/test_cross_language_golden.py) validates the same fixture too, so both
 * sides' CI protect byte compatibility of canonical JSON (= cross-language agreement of intent.hash / specHash).
 *
 * To change the fixture, re-run generate-cross-language-fixtures and commit
 * (if this test fails: regenerate for an intended change, or it is a regression for an unintended one).
 */
const fixturePath = join(dirname(fileURLToPath(import.meta.url)), "fixtures/cross-language-canonical.json");

interface Fixture {
  canonical: { value: unknown; canonical: string; sha256: string }[];
  intents: { canonical: string; params: Record<string, never>; hash: string }[];
  spec: { file: string; specHash: string; structureHash: string };
  cacheKey: { parts: CacheKeyParts; key: string }[];
  lineageCursor: { seq: number; cursor: string }[];
  actionParams: {
    schema: ActionParamsSchema;
    payload: JsonObject;
    issues: ActionParamIssue[];
    payloadHash: string;
  }[];
  actionPayloadScan: { payload: JsonObject; issues: ActionParamIssue[] }[];
  sandboxDom: { tags: string[]; attrs: string[]; styleProps: string[] };
  distillation: { jsonl: string };
  promptFragments: {
    designKit: string;
    designSystem: { guide: DesignSystemGuide; fragment: string };
    designBrief: string[];
    promptRevision: string;
  };
}

const fixture = JSON.parse(readFileSync(fixturePath, "utf8")) as Fixture;

// The Compliance Evidence Pack golden lives in its own directory (a store + a manifest + a detached
// signature -- see generate-cross-language-fixtures.ts's own comment), not inside the single
// cross-language-canonical.json above.
const evidencePackDir = join(dirname(fixturePath), "evidence-pack");
interface EvidencePackStore {
  scope: { tenant?: string; since: string; until: string };
  generator: string;
  generatedAt: string;
  events: LineageEventRecord[];
  promotions: PromotionState[];
  fixations: FixationRecord[];
}
const evidenceStore = JSON.parse(
  readFileSync(join(evidencePackDir, "store.json"), "utf8"),
) as EvidencePackStore;
const evidenceManifestFixture = JSON.parse(
  readFileSync(join(evidencePackDir, "manifest.json"), "utf8"),
) as EvidenceManifest;
const evidenceSignatureFixture = readFileSync(join(evidencePackDir, "manifest.sig"), "utf8").trim();

describe("cross-language golden (byte compatibility of canonical JSON / hash)", () => {
  it("canonicalStringify + sha256Hex reproduces the fixture", async () => {
    for (const c of fixture.canonical) {
      expect(canonicalStringify(c.value)).toBe(c.canonical);
      expect(await sha256Hex(c.canonical)).toBe(c.sha256);
    }
  });

  it("computeIntentHash reproduces the fixture", async () => {
    for (const c of fixture.intents) {
      expect(await computeIntentHash({ canonical: c.canonical, params: c.params })).toBe(c.hash);
    }
  });

  it("computeSpecHash / computeStructureHash reproduces the fixture", async () => {
    const spec = parseSpec(
      JSON.parse(
        readFileSync(join(dirname(fixturePath), "../..", fixture.spec.file.replace(/^spec\//, "")), "utf8"),
      ),
    );
    expect(await computeSpecHash(spec)).toBe(fixture.spec.specHash);
    expect(await computeStructureHash(spec)).toBe(fixture.spec.structureHash);
  });

  it("cacheKey reproduces the fixture (the policyFingerprint 7th component's segment/placeholder format)", () => {
    for (const c of fixture.cacheKey) {
      expect(cacheKey(c.parts)).toBe(c.key);
    }
  });

  it("encodeSeqCursor/decodeSeqCursor reproduce the fixture's literal cursor bytes (design.md #53)", () => {
    for (const c of fixture.lineageCursor) {
      expect(encodeSeqCursor(c.seq)).toBe(c.cursor);
      expect(decodeSeqCursor(c.cursor)).toBe(c.seq);
    }
  });

  it("validateActionParams / actionPayloadHash reproduce the fixture (design.md #62/#63)", async () => {
    for (const c of fixture.actionParams) {
      expect(validateActionParams(c.schema, c.payload)).toEqual(c.issues);
      expect(await actionPayloadHash(c.payload)).toBe(c.payloadHash);
    }
  });

  it("findUnsafeActionParamKeys reproduces the fixture (design.md #62)", () => {
    expect(fixture.actionPayloadScan.length).toBeGreaterThan(0);
    for (const c of fixture.actionPayloadScan) {
      expect(findUnsafeActionParamKeys(c.payload)).toEqual(c.issues);
    }
  });

  it("the sandbox DOM allowlist (packages/spec-core/src/schema/sandbox-dom.ts) reproduces the fixture", () => {
    expect([...ALLOWED_TAGS].sort()).toEqual(fixture.sandboxDom.tags);
    expect([...ALLOWED_ATTRS].sort()).toEqual(fixture.sandboxDom.attrs);
    expect([...ALLOWED_STYLE_PROPS].sort()).toEqual(fixture.sandboxDom.styleProps);
  });

  it("exportDistillationDataset reproduces the fixture's JSONL byte-for-byte", async () => {
    const spec = parseSpec(
      JSON.parse(
        readFileSync(join(dirname(fixturePath), "../..", fixture.spec.file.replace(/^spec\//, "")), "utf8"),
      ),
    );
    const record: FixationRecord = {
      intentHash: spec.intent.hash,
      canonical: spec.intent.canonical,
      structureHash: fixture.spec.structureHash,
      pinnedSpec: spec,
      fixatedAt: "2026-06-10T03:12:00Z",
      approver: { id: "qa-lead" },
      tenant: "tenant-acme",
      catalogFingerprint: "catalog@2026-06-10",
    };
    // `golden: [spec]` shares the fixation's intentHash, also pinning the fixation-before-golden tie-break.
    expect(exportDistillationDataset({ fixations: [record], golden: [spec] })).toBe(
      fixture.distillation.jsonl,
    );
  });
});

describe("cross-language golden (prompt fragments)", () => {
  it("designKitPromptFragment(DEFAULT_KIT_VOCABULARY) reproduces the fixture", () => {
    expect(designKitPromptFragment(DEFAULT_KIT_VOCABULARY)).toBe(fixture.promptFragments.designKit);
  });

  it("designSystemPromptFragment reproduces the fixture (input+output both pinned, since the guide is not an exported constant)", () => {
    expect(designSystemPromptFragment(fixture.promptFragments.designSystem.guide)).toBe(
      fixture.promptFragments.designSystem.fragment,
    );
  });

  it("the design brief inside L2_SYSTEM_PROMPT reproduces the fixture", () => {
    const lines = L2_SYSTEM_PROMPT.split("\n");
    const start = lines.indexOf("- Design brief (follow every point):");
    // indexOf returns -1 (not found) rather than throwing, and lines.slice(-1) would silently compare
    // against just the prompt's last line instead of failing outright — assert the line is actually present.
    expect(start).toBeGreaterThan(-1);
    expect(lines.slice(start)).toEqual(fixture.promptFragments.designBrief);
  });

  it("PROMPT_REVISION reproduces the fixture (catches an accidental, unbumped prompt change)", () => {
    expect(PROMPT_REVISION).toBe(fixture.promptFragments.promptRevision);
  });
});

describe("cross-language golden (Compliance Evidence Pack, design.md #67)", () => {
  const ED25519_PKCS8_PREFIX = "302e020100300506032b657004220420";
  // Same RFC 8032 §7.1 TEST 1 vector packages/lineage/test/evidence-sign.test.ts and
  // python/kohaku/tests/lineage/test_evidence.py independently pin (a well-known, publicly verifiable
  // vector, not a fixture-specific secret).
  const RFC8032_TEST1_SECRET_KEY_SEED = "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60";
  const RFC8032_TEST1_PUBLIC_KEY = "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a";

  function hexToBytes(hex: string): Uint8Array {
    const bytes = new Uint8Array(hex.length / 2);
    for (let i = 0; i < bytes.length; i++) bytes[i] = Number.parseInt(hex.slice(i * 2, i * 2 + 2), 16);
    return bytes;
  }

  function evidenceSourceFromStore(store: EvidencePackStore): EvidenceSource {
    return {
      async listLineage(filter) {
        return store.events.filter((e) => {
          if (filter.tenant != null && e.tenant !== filter.tenant) return false;
          if (filter.since != null && e.ts < filter.since) return false;
          if (filter.until != null && e.ts > filter.until) return false;
          return true;
        });
      },
      async pageLineage(req: LineagePageRequest): Promise<LineagePage> {
        return pageLineageArray(store.events, req);
      },
      async listPromotionStates(tenant) {
        return tenant == null ? store.promotions : store.promotions.filter((p) => p.tenant === tenant);
      },
      async listFixations(tenant) {
        return tenant == null ? store.fixations : store.fixations.filter((f) => f.tenant === tenant);
      },
    };
  }

  it("buildEvidencePack reproduces the fixture manifest byte-for-byte", async () => {
    const rebuilt = await buildEvidencePack({
      source: evidenceSourceFromStore(evidenceStore),
      scope: evidenceStore.scope,
      generator: evidenceStore.generator,
      signer: evidenceManifestFixture.signer,
      now: () => new Date(evidenceStore.generatedAt),
    });
    expect(rebuilt.manifest).toEqual(evidenceManifestFixture);
    expect(canonicalStringify(rebuilt.manifest)).toBe(canonicalStringify(evidenceManifestFixture));
  });

  it("signManifest reproduces the fixture's signature bytes (Ed25519 is deterministic)", async () => {
    const privateKey = await importEd25519PrivateKeyPkcs8(
      hexToBytes(ED25519_PKCS8_PREFIX + RFC8032_TEST1_SECRET_KEY_SEED),
    );
    const signature = await signManifest(evidenceManifestFixture, privateKey);
    expect(signature).toBe(evidenceSignatureFixture);
  });

  it("the fixture's signature verifies against the RFC 8032 TEST 1 public key", async () => {
    const publicKey = await importEd25519PublicKeyRaw(hexToBytes(RFC8032_TEST1_PUBLIC_KEY));
    expect(await verifyManifestSignature(evidenceManifestFixture, evidenceSignatureFixture, publicKey)).toBe(
      true,
    );
  });
});
