import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { exportDistillationDataset } from "@kohaku-ui/evals";
import {
  ALLOWED_ATTRS,
  ALLOWED_STYLE_PROPS,
  ALLOWED_TAGS,
  type CacheKeyParts,
  cacheKey,
  canonicalStringify,
  computeIntentHash,
  computeSpecHash,
  computeStructureHash,
  type FixationRecord,
  parseSpec,
  sha256Hex,
} from "@kohaku-ui/spec-core";
import { describe, expect, it } from "vitest";

/**
 * Cross-language golden (TS side). Pins that the TS implementation reproduces the fixture
 * (generated by scripts/generate-cross-language-fixtures.ts). The Python implementation
 * (python/kohaku/tests/spec/test_cross_language_golden.py) validates the same fixture too, so both
 * sides' CI protect byte compatibility of canonical JSON (= cross-language agreement of intent.hash / specHash).
 *
 * To change the fixture, re-run generate-cross-language-fixtures and commit
 * (if this test fails: regenerate for an intended change, or it is a regression for an unintended one).
 */
const fixturePath = join(dirname(fileURLToPath(import.meta.url)), "fixtures/cross-language-canonical.json");

interface Fixture {
  canonical: { value: unknown; canonical: string; sha256: string }[];
  intents: { canonical: string; params: Record<string, never>; hash: string }[];
  spec: { file: string; specHash: string; structureHash: string };
  cacheKey: { parts: CacheKeyParts; key: string }[];
  sandboxDom: { tags: string[]; attrs: string[]; styleProps: string[] };
  distillation: { jsonl: string };
}

const fixture = JSON.parse(readFileSync(fixturePath, "utf8")) as Fixture;

describe("cross-language golden (byte compatibility of canonical JSON / hash)", () => {
  it("canonicalStringify + sha256Hex reproduces the fixture", async () => {
    for (const c of fixture.canonical) {
      expect(canonicalStringify(c.value)).toBe(c.canonical);
      expect(await sha256Hex(c.canonical)).toBe(c.sha256);
    }
  });

  it("computeIntentHash reproduces the fixture", async () => {
    for (const c of fixture.intents) {
      expect(await computeIntentHash({ canonical: c.canonical, params: c.params })).toBe(c.hash);
    }
  });

  it("computeSpecHash / computeStructureHash reproduces the fixture", async () => {
    const spec = parseSpec(
      JSON.parse(
        readFileSync(join(dirname(fixturePath), "../..", fixture.spec.file.replace(/^spec\//, "")), "utf8"),
      ),
    );
    expect(await computeSpecHash(spec)).toBe(fixture.spec.specHash);
    expect(await computeStructureHash(spec)).toBe(fixture.spec.structureHash);
  });

  it("cacheKey reproduces the fixture (the policyFingerprint 7th component's segment/placeholder format)", () => {
    for (const c of fixture.cacheKey) {
      expect(cacheKey(c.parts)).toBe(c.key);
    }
  });

  it("the sandbox DOM allowlist (packages/spec-core/src/schema/sandbox-dom.ts) reproduces the fixture", () => {
    expect([...ALLOWED_TAGS].sort()).toEqual(fixture.sandboxDom.tags);
    expect([...ALLOWED_ATTRS].sort()).toEqual(fixture.sandboxDom.attrs);
    expect([...ALLOWED_STYLE_PROPS].sort()).toEqual(fixture.sandboxDom.styleProps);
  });

  it("exportDistillationDataset reproduces the fixture's JSONL byte-for-byte", async () => {
    const spec = parseSpec(
      JSON.parse(
        readFileSync(join(dirname(fixturePath), "../..", fixture.spec.file.replace(/^spec\//, "")), "utf8"),
      ),
    );
    const record: FixationRecord = {
      intentHash: spec.intent.hash,
      canonical: spec.intent.canonical,
      structureHash: fixture.spec.structureHash,
      pinnedSpec: spec,
      fixatedAt: "2026-06-10T03:12:00Z",
      approver: { id: "qa-lead" },
      tenant: "tenant-acme",
      catalogFingerprint: "catalog@2026-06-10",
    };
    // `golden: [spec]` shares the fixation's intentHash, also pinning the fixation-before-golden tie-break.
    expect(exportDistillationDataset({ fixations: [record], golden: [spec] })).toBe(
      fixture.distillation.jsonl,
    );
  });
});
