/**
 * Shared renderer that runs inside the MCP Apps iframe (Strategy A: the same rendering code as the Web app). It has 2 modes:
 * - Normal mode (ext-apps bridge): receive {spec, capability} via ui/notifications/tool-result →
 *   render with renderer-react. Data resolution goes through the app-only tool kohaku_resolve_binding (bulk data
 *   does not pass through the model's context). Component events go kohaku_event → re-render with the new Spec.
 *   Writes (presentForm submit / action.button) go through the app-only tool kohaku_action.
 * - Snapshot mode (#kohaku-snapshot is non-null): self-contained HTML generated by kohaku_render_snapshot
 *   for UI-incapable hosts (CLI, etc.). It does not connect to the bridge; it renders statically from the
 *   embedded Spec + resolved data (re-composition events are no-op). The goal is to display it with the same rendering code as the Web app.
 *
 * Hang countermeasures: because Claude Desktop's App Bridge has a known
 * issue where it does not respond to widget-originated tools/call (ext-apps issue #386), (A) initial data is
 * co-embedded in the tool-result's _meta so the initial display appears even if the host's tool call is broken,
 * and (B) callServerTool has a timeout and a diagnostic display to avoid an indefinite "loading". Furthermore,
 * (C) the receiving side is logged unconditionally so we can distinguish "the host is not sending" from "it is
 * sending but the shape is different" on real devices, and (D) when the tool-result does not arrive, a self-recovery
 * that re-calls a model-visible tool from the widget is attempted once. Connection / reception milestones are printed
 * with console.log("[kohaku] …"), traceable in Claude Desktop's Developer Mode (Cmd+Option+I).
 */

import { type BindingClient, createBindingClient, splitReservedParams } from "@kohaku-ui/data-binding";
import { defaultDarkTheme, defaultLightTheme, themeFromHostStyles } from "@kohaku-ui/renderer-core";
import { type ImplRegistry, RendererProvider, SpecView, type SurfaceEvent } from "@kohaku-ui/renderer-react";
import { createCoreRegistry } from "@kohaku-ui/renderer-react/core";
import { parseSpec, specToText, type TabularData, type ThemeTokens, type UISpec } from "@kohaku-ui/spec-core";
// Overlay the same sales-domain implementations as the Web app (sales.kpiCard / sales.calendarHeatmap) onto the registry.
// Share the same registration function as the Web surface (SpecSurface), so both surfaces match pixel-for-pixel (Strategy A).
// Without this, the sales.kpiCard in the L0 fixed Spec becomes an "unimplemented component type" on the MCP side / snapshot.
import { registerSalesImpls } from "@kohaku-ui-sample/web/renderer-impls";
import { App } from "@modelcontextprotocol/ext-apps";
import { StrictMode, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import {
  canToggleFullscreen,
  extractSpecView,
  nextDisplayMode,
  type OpenAiWidgetApi,
  persistView,
  readPersistedView,
  recoveryBlockReason,
  resolveHostTheme,
  type ThemeHostContext,
} from "./host-integration.js";

/**
 * Timeout for app-originated tool calls (ms). A cutoff so an unresponsive host does not freeze indefinitely.
 * Applied to resolve / action (fast data reads/writes) and self-recovery (re-calling a cached compose).
 */
const SERVER_TOOL_TIMEOUT_MS = 15_000;
/**
 * Timeout for re-composition (kohaku_event) (ms). Since re-composition runs LLM generation (L1) on a cache miss,
 * the cutoff is longer than resolve / action (matched to the MCP SDK default of 60 seconds to avoid regressing the live-LLM path).
 */
const EVENT_TIMEOUT_MS = 60_000;
/** Grace period before attempting self-recovery (re-calling a model-visible tool) if no tool-result arrives after connect (ms). */
const RECOVER_AFTER_MS = 5_000;
/** Backstop grace period before falling to the diagnostic display when self-recovery does not start (stays waiting) (ms). */
const WAIT_DIAGNOSTIC_MS = 10_000;

/**
 * Combines host-integration's pure `resolveHostTheme` extraction ({ mode, variables }) with
 * renderer-core's theme defaults + `themeFromHostStyles` overlay to build the `ThemeTokens`
 * handed to `RendererProvider`. renderer-core owns the default-theme values (single source) —
 * a partial literal copy here would silently stop tracking brand changes made there.
 *
 * Used both for the initial theme (from `ui/initialize`'s hostContext, via
 * `app.getHostContext()`) and on every `ui/notifications/host-context-changed` that touches
 * `theme`/`styles` (see createBridgeController below). L2 (freely-generated HTML rendered in
 * the sandbox) is out of scope: it is not exposed on the MCP surface today (only L0/L1 render
 * through renderer-react here), so only this path needs host-theme adoption.
 */
function themeFromHostContext(hostContext: ThemeHostContext | undefined): ThemeTokens {
  const { mode, variables } = resolveHostTheme(hostContext);
  const base = mode === "dark" ? defaultDarkTheme : defaultLightTheme;
  return themeFromHostStyles(variables, base);
}

/** The theme used before any host context is known (snapshot mode; bridge mode before connect). */
const DEFAULT_THEME: ThemeTokens = { ...defaultLightTheme };

interface ViewState {
  spec: UISpec;
  capability: string;
  /**
   * The initial data co-embedded in the tool-result's _meta (effective ref → TabularData).
   * The fetcher looks it up by ref.raw and deletes it once used (consume-once). It is a Map for in-place consumption.
   */
  initialData?: Map<string, TabularData>;
}

/** Embedded snapshot. The keys of data are the raw of the effective ref (paired with the host's buildSnapshot). */
interface Snapshot {
  spec: unknown;
  data: Record<string, TabularData>;
}

/** Diagnostic info on a wait timeout (bridge mode only). */
interface BridgeDiagnostics {
  hostName?: string;
  hostVersion?: string;
  /** Whether the host declares app-originated tool calls (serverTools). Used only for wording to avoid false negatives. */
  serverToolsDeclared: boolean;
}

/**
 * The waiting phase when no view has arrived (bridge mode only; transitions in the self-recovery orchestration).
 * - waiting: waiting for a tool-result / for self-recovery to start (initial).
 * - recovering: the self-recovery callServerTool is running (no diagnostic display during this = do not create silent time).
 * - diagnostic: it is confirmed that no tool-result arrived (self-recovery impossible / failed). Show the Diagnostic.
 */
type WaitingPhase = "waiting" | "recovering" | "diagnostic";
interface WaitingState {
  phase: WaitingPhase;
  /** Whether self-recovery was attempted and failed (adds a "self-recovery also failed" line to the diagnostic display). */
  recoveryFailed: boolean;
}

/**
 * A controller that absorbs the mode difference (normal = bridge / snapshot = embedded data).
 * Root handles binding and events through this, so the rendering code (SpecView + RendererProvider) is common to both modes.
 */
interface RendererController {
  /** Create a BindingClient for the view's capability. */
  makeBinding(view: ViewState): BindingClient;
  /** Handle component events (no-op in snapshot mode). */
  handleEvent(
    view: ViewState,
    event: SurfaceEvent,
    setView: (view: ViewState) => void,
    setError: (message: string) => void,
  ): void;
  /** A note indicating this is a static snapshot (undefined in normal mode). */
  note?: string;
  /**
   * Supply of diagnostic info on a wait timeout (wired only in bridge mode).
   * Root draws the waiting phases (recovering / diagnostic) only when this is wired.
   * Snapshot mode is not wired because initialView is always non-null (it never enters the waiting display).
   */
  diagnostics?(): BridgeDiagnostics;
  /**
   * displayMode toggling (MCP Apps standard ui/request-display-mode). Wired only in bridge mode.
   * Root draws the fullscreen toggle only when available() is true (on unsupported hosts, the button itself does not appear).
   */
  displayMode?: {
    available(): boolean;
    current(): string | undefined;
    request(mode: "inline" | "fullscreen"): Promise<string | undefined>;
    /** Subscription point for host-driven changes (host-context-changed). Root uses it to sync the current-value display. */
    onChange(cb: (mode: string | undefined) => void): void;
  };
  /**
   * Host-theme adoption (MCP Apps / OpenAI Apps SDK `hostContext.theme` + `hostContext.styles.variables`).
   * Wired only in bridge mode (snapshot mode is not connected to a host and always renders with
   * `DEFAULT_THEME`). Root seeds its theme state from `initial()` and re-renders on `onChange`
   * (fired from `ui/notifications/host-context-changed`).
   */
  theme?: {
    initial(): ThemeTokens;
    /** Subscription point for host-driven theme changes (host-context-changed). */
    onChange(cb: (theme: ThemeTokens) => void): void;
  };
}

/** Diagnostic display on a wait timeout (bridge mode only). */
function Diagnostic(props: { info: BridgeDiagnostics; recoveryFailed?: boolean }): React.ReactNode {
  const { info, recoveryFailed } = props;
  return (
    <div style={{ color: "#92400e", fontSize: 13, lineHeight: 1.7 }}>
      <div style={{ fontWeight: 600, marginBottom: 6 }}>
        The UI Spec has not arrived yet (no tool result received).
      </div>
      <div>
        Host: {info.hostName ?? "unknown"}
        {info.hostVersion != null ? ` v${info.hostVersion}` : ""}
      </div>
      <div>App-originated tool calls (serverTools) declared: {info.serverToolsDeclared ? "yes" : "no"}</div>
      {recoveryFailed === true ? (
        <div style={{ marginTop: 8, color: "#991b1b" }}>
          Self-recovery also failed (callServerTool may not be functioning).
        </div>
      ) : null}
      <div style={{ marginTop: 8 }}>
        The host may not be forwarding the UI tool result to the widget. Try displaying via a static snapshot
        (kohaku_render_snapshot).
      </div>
    </div>
  );
}

function Root(props: {
  controller: RendererController;
  initialView: ViewState | null;
  /**
   * Register so that, when a tool-result arrives in normal mode, setView / setError / setWaiting can be injected from outside.
   * setError is used by bridge-side events like ontoolcancelled; setWaiting by the self-recovery phase transitions.
   */
  onReady?: (api: {
    setView: (view: ViewState) => void;
    setError: (message: string) => void;
    setWaiting: (waiting: WaitingState) => void;
  }) => void;
}): React.ReactNode {
  const { controller } = props;
  const [view, setView] = useState<ViewState | null>(props.initialView);
  const [error, setError] = useState<string | null>(null);
  const [waiting, setWaiting] = useState<WaitingState>({ phase: "waiting", recoveryFailed: false });
  // displayMode: syncing the display of the current mode. Host-driven changes are followed via the onChange subscription.
  const dm = controller.displayMode;
  const [mode, setMode] = useState<string | undefined>(dm?.current());
  useEffect(() => {
    dm?.onChange(setMode);
  }, [dm]);

  // Host-theme adoption: seed from the controller's initial theme (snapshot mode has no theme
  // controller, so it stays on DEFAULT_THEME) and follow host-driven changes via onChange.
  const themeController = controller.theme;
  const [theme, setTheme] = useState<ThemeTokens>(themeController?.initial() ?? DEFAULT_THEME);
  useEffect(() => {
    themeController?.onChange(setTheme);
  }, [themeController]);

  // On every render, hand the latest setView / setError / setWaiting outward (a result arriving before the first render
  // comes via initialView). useState's setters are stable references, so re-assigning on every render is harmless.
  props.onReady?.({ setView, setError, setWaiting });

  // Backstop (insurance): in bridge mode, if self-recovery does not start (stays waiting) for WAIT_DIAGNOSTIC_MS,
  // fall to the diagnostic display. Normally bootBridge's self-recovery (RECOVER_AFTER_MS = 5 seconds) advances the
  // phase to recovering / diagnostic first, so this does not fire. A last line of defense to avoid silent time.
  useEffect(() => {
    if (view != null || controller.diagnostics == null || waiting.phase !== "waiting") return;
    const id = setTimeout(
      () => setWaiting((w) => (w.phase === "waiting" ? { phase: "diagnostic", recoveryFailed: false } : w)),
      WAIT_DIAGNOSTIC_MS,
    );
    return () => clearTimeout(id);
  }, [view, controller, waiting.phase]);

  if (error != null) {
    return <div style={{ color: "#991b1b", fontSize: 13 }}>{error}</div>;
  }
  if (view == null) {
    // Only bridge mode (diagnostics wired) draws recovering / diagnostic distinctly.
    if (controller.diagnostics != null && waiting.phase === "recovering") {
      return (
        <div style={{ color: "#6b7280", fontSize: 13 }}>
          Attempting self-recovery… (checking whether the host is not sending the tool result)
        </div>
      );
    }
    if (controller.diagnostics != null && waiting.phase === "diagnostic") {
      return <Diagnostic info={controller.diagnostics()} recoveryFailed={waiting.recoveryFailed} />;
    }
    return <div style={{ color: "#6b7280", fontSize: 13 }}>Waiting for the UI Spec…</div>;
  }

  const impls: ImplRegistry = registerSalesImpls(createCoreRegistry());
  const handleEvent = (event: SurfaceEvent): void => controller.handleEvent(view, event, setView, setError);
  // displayMode toggle: show a small toggle button only on fullscreen-capable hosts.
  const toggleDisplayMode = (): void => {
    if (dm == null) return;
    const next = nextDisplayMode(mode);
    dm.request(next)
      .then((granted) => setMode(granted ?? next))
      .catch((e: unknown) =>
        console.log(`[kohaku] displayMode switch failed: ${e instanceof Error ? e.message : String(e)}`),
      );
  };

  return (
    <RendererProvider value={{ impls, binding: controller.makeBinding(view), theme, onEvent: handleEvent }}>
      {dm?.available() ? (
        <div style={{ display: "flex", justifyContent: "flex-end", marginBottom: 4 }}>
          <button
            type="button"
            onClick={toggleDisplayMode}
            style={{
              fontSize: 11,
              color: "#6b7280",
              background: "transparent",
              border: "1px solid #e5e7eb",
              borderRadius: 4,
              padding: "2px 8px",
              cursor: "pointer",
            }}
          >
            {mode === "fullscreen" ? "Exit fullscreen" : "Fullscreen"}
          </button>
        </div>
      ) : null}
      <SpecView spec={view.spec} />
      {controller.note != null ? (
        <div style={{ marginTop: 12, color: "#6b7280", fontSize: 11 }}>{controller.note}</div>
      ) : null}
    </RendererProvider>
  );
}

/** Read the JSON of #kohaku-snapshot. Returns null for the default `null` (normal mode) or invalid content. */
function readSnapshot(): Snapshot | null {
  const raw = document.getElementById("kohaku-snapshot")?.textContent;
  if (raw == null || raw.trim() === "" || raw.trim() === "null") return null;
  try {
    const parsed = JSON.parse(raw) as unknown;
    if (parsed == null || typeof parsed !== "object") return null;
    const s = parsed as Partial<Snapshot>;
    if (s.spec == null || s.data == null) return null;
    return { spec: s.spec, data: s.data };
  } catch {
    return null;
  }
}

/** Snapshot mode: render statically from the embedded Spec + data (does not connect to the bridge). */
function bootSnapshot(snapshot: Snapshot): void {
  const controller: RendererController = {
    makeBinding: (view) =>
      createBindingClient({
        capability: view.capability,
        fetcher: async (ref) => {
          // Resolve from the embedded data map (key = raw of the effective ref). Out of range is 404-equivalent.
          const found = snapshot.data[ref.raw];
          return { status: found != null ? 200 : 404, body: found ?? null };
        },
        // In a static snapshot, writes are not possible (a click shows useInvokeAction's failed display).
        actionFetcher: async () => {
          throw new Error("Write operations cannot be executed in a static snapshot.");
        },
      }),
    // A static snapshot is not re-composed (operation events are ignored).
    handleEvent: () => {},
    note: "Static snapshot (same renderer as the Web app). No re-fetch or re-composition happens on interaction.",
  };
  const initialView: ViewState = {
    spec: parseSpec(snapshot.spec),
    // capability is not used (the fetcher returns the embedded data).
    capability: "snapshot",
  };
  createRoot(document.getElementById("root")!).render(
    <StrictMode>
      <Root controller={controller} initialView={initialView} />
    </StrictMode>,
  );
}

/**
 * Bridge mode's RendererController (binding / events / diagnostics / displayMode toggling).
 * Owns the model-context feedback and the host-driven displayMode listener;
 * bootBridge only wires the returned controller into Root.
 */
function createBridgeController(app: App, openai: OpenAiWidgetApi | undefined): RendererController {
  /**
   * Feed a summary of the current view back into the model context (ui/update-model-context).
   * Changes via app-only tools (kohaku_event / kohaku_action) are invisible to the model (as designed with
   * visibility ["app"]), so after an operation "what is currently visible" is fed back as summary text only —
   * bulk data does not pass through (the principle that bulk data never enters the model context is unchanged).
   * The semantics are overwrite (the host injects only the last one into the next user message), so sending the
   * full amount each time is fine. On unsupported hosts it is a no-op; failures are observation logs only (does not break the UI).
   * Not called on the first tool-result (content[0]'s text fallback is already model-visible — avoid double injection).
   */
  const pushModelContext = (text: string): void => {
    if (app.getHostCapabilities()?.updateModelContext == null) return;
    void app
      .updateModelContext({ content: [{ type: "text", text }] })
      .catch((e: unknown) =>
        console.log(`[kohaku] update-model-context failed: ${e instanceof Error ? e.message : String(e)}`),
      );
  };

  // A listener that transcribes host-driven displayMode changes (host-context-changed) to Root.
  let modeListener: ((mode: string | undefined) => void) | null = null;
  // A listener that transcribes host-driven theme changes (host-context-changed) to Root.
  let themeListener: ((theme: ThemeTokens) => void) | null = null;
  app.onhostcontextchanged = (params) => {
    if (params.displayMode != null) modeListener?.(params.displayMode);
    // host-context-changed's params carry only the changed fields (a partial update), and the SDK
    // merges them into its internal context before this handler fires (getHostContext() below already
    // reflects the merge). So re-derive the theme from the full merged context rather than `params`
    // directly — otherwise a params payload that changes styles.variables but omits theme (or vice
    // versa) would drop the field that did not change in this particular notification.
    if (params.theme != null || params.styles != null) {
      themeListener?.(themeFromHostContext(app.getHostContext()));
    }
  };

  return {
    makeBinding: (view) =>
      createBindingClient({
        capability: view.capability,
        fetcher: async (ref) => {
          // Initial data is embedded (host-mcp-apps' preresolveInitialData) keyed by each component's base
          // $ref — the literal ref the Spec declares, with no reserved paging/sort params. Once a bound part
          // is serverSide (e.g. sales.records' presentSpreadsheet), its very first fetch already carries
          // pageSize as a reserved `_limit` (buildResolveOptions merges it in whenever pageSize is set, even
          // before any user sort/page interaction — see renderer-core's spreadsheet-remote-controller
          // start()/refetch()), so ref.raw itself would never match the embedded key and every first paint
          // would pay a live round trip. Strip reserved params before matching (mirrors host-core's
          // binding-ref.ts / parseInvokableRef, which validate/merge against the same base-ref split) so the
          // embedded snapshot still hits regardless of which reserved params happen to be attached.
          const baseRef = splitReservedParams(ref.raw).base.raw;
          // If initial data is embedded, return it consume-once and avoid going through the host.
          // The reason for consume-once (delete once used): so the invalidation re-resolution after a write does not
          // return stale embedded data (use the embedding only the first time; thereafter fetch the latest via the host).
          const embedded = view.initialData?.get(baseRef);
          if (embedded != null) {
            view.initialData!.delete(baseRef);
            console.log(`[kohaku] resolve: ${ref.raw} (initialData hit)`);
            return { status: 200, body: embedded };
          }
          console.log(`[kohaku] resolve start: ${ref.raw} (via bridge)`);
          try {
            const result = await app.callServerTool(
              { name: "kohaku_resolve_binding", arguments: { ref: ref.raw, capability: view.capability } },
              // Cut off so an unresponsive host does not freeze indefinitely. Do not extend the timeout on progress notifications.
              { timeout: SERVER_TOOL_TIMEOUT_MS, resetTimeoutOnProgress: false },
            );
            if (result.isError === true) {
              console.log(`[kohaku] resolve failed: ${ref.raw} (tool error)`);
              return { status: 403, body: null };
            }
            const data = (result.structuredContent as { data?: TabularData } | undefined)?.data;
            console.log(`[kohaku] resolve done: ${ref.raw}`);
            return { status: data != null ? 200 : 500, body: data ?? null };
          } catch (e) {
            // If callServerTool is unresponsive (timeout) / rejected, BoundDataController stays in "loading".
            // Re-wrap it into a Japanese Error including the original error message and throw (BoundDataController
            // displays this message as-is as the error).
            const cause = e instanceof Error ? e.message : String(e);
            console.log(`[kohaku] resolve failed: ${ref.raw} (${cause})`);
            throw new Error(
              "The host is not responding to the data-resolution call (kohaku_resolve_binding). " +
                "This may be a known host-side issue. Try a static snapshot via kohaku_render_snapshot. " +
                `(cause: ${cause})`,
            );
          }
        },
        // Wire writes (presentForm submit / action.button) to the app-only tool kohaku_action.
        actionFetcher: async (action, payload) => {
          const result = await app.callServerTool(
            { name: "kohaku_action", arguments: { action, payload, capability: view.capability } },
            { timeout: SERVER_TOOL_TIMEOUT_MS, resetTimeoutOnProgress: false },
          );
          if (result.isError === true) {
            // Put the tool error's body (Japanese message) onto useInvokeAction's failed display.
            const text = (result.content as { text?: string }[] | undefined)
              ?.map((c) => c.text ?? "")
              .join("");
            throw new Error(`Write operation "${action}" failed: ${text ?? ""}`);
          }
          // Writes (app-only tools) are also invisible to the model, so feed back only the fact of execution
          // (if the immediately following re-resolution updates the view, that summary overwrites this).
          pushModelContext(
            `The user performed the write operation "${action}" (the result is already reflected in the display).`,
          );
          // structuredContent is { result, invalidates?, refVersions? } (parseActionResult reads it as-is).
          return { status: 200, body: result.structuredContent as unknown };
        },
      }),
    handleEvent: (view, event, setView, setError) => {
      console.log(`[kohaku] event: ${event.on}`);
      void app
        .callServerTool(
          {
            name: "kohaku_event",
            arguments: {
              intent: { canonical: view.spec.intent.canonical, params: view.spec.intent.params },
              on: event.on,
              payload: event.payload,
            },
          },
          // Since re-composition runs LLM generation (L1) on a cache miss, the cutoff is longer than resolve / action
          // (fast data reads/writes) (15 seconds would erroneously abort the live-LLM path. matched to the MCP SDK default of 60 seconds).
          { timeout: EVENT_TIMEOUT_MS, resetTimeoutOnProgress: false },
        )
        .then((result) => {
          // The structure check + parseSpec + _meta initial-data read is consolidated in extractSpecView
          // (shared with the tool-result / self-recovery paths). A missing spec/capability is silently
          // ignored, while a malformed spec surfaces as the error display.
          const extracted = extractSpecView(result);
          if (!extracted.ok) {
            if (extracted.reason === "parse-error") setError(extracted.detail);
            return;
          }
          const next = extracted.view;
          setView(next);
          // Also save the re-composed view to widgetState (remount restore tracks the latest display).
          persistView(openai, { spec: next.spec, capability: next.capability });
          void app.sendSizeChanged({ height: document.documentElement.scrollHeight + 24 });
          // Re-composition (app-only tool) is invisible to the model, so feed back a summary of the current view.
          pushModelContext(
            `The display was updated by a user action. Current view:\n\n${specToText(next.spec)}`,
          );
        })
        .catch((e: unknown) => setError(e instanceof Error ? e.message : String(e)));
    },
    diagnostics: () => {
      const host = app.getHostVersion();
      return {
        ...(host?.name != null ? { hostName: host.name } : {}),
        ...(host?.version != null ? { hostVersion: host.version } : {}),
        serverToolsDeclared: app.getHostCapabilities()?.serverTools != null,
      };
    },
    // displayMode toggling (MCP Apps standard). Availability is decided by the host context's
    // availableDisplayModes (on unsupported hosts, the toggle is hidden).
    displayMode: {
      available: () => canToggleFullscreen(app.getHostContext()?.availableDisplayModes),
      current: () => app.getHostContext()?.displayMode,
      request: async (mode) => (await app.requestDisplayMode({ mode })).mode,
      onChange: (cb) => {
        modeListener = cb;
      },
    },
    // Host-theme adoption (MCP Apps / OpenAI Apps SDK hostContext.theme + styles.variables).
    // `initial()` reads whatever hostContext is already available at the time Root mounts
    // (bootBridge renders Root only after `await app.connect()`, so the ui/initialize hostContext
    // is already merged in by then); `onChange` is driven by the app.onhostcontextchanged handler above.
    theme: {
      initial: () => themeFromHostContext(app.getHostContext()),
      onChange: (cb) => {
        themeListener = cb;
      },
    },
  };
}

/**
 * The bridge's view / wait-state channel. A tool-result can arrive either before or after the first
 * render: before render it is stashed in initialView; after render it is forwarded to the setters
 * received via Root's onReady (setError is for ontoolcancelled, setWaiting for the self-recovery phases).
 */
interface ViewChannel {
  /** Applies a view: marks viewApplied, persists to widgetState, and routes it to React or initialView. */
  applyView(view: ViewState): void;
  /** Whether some view has been applied (suppresses self-recovery once a display exists). */
  viewApplied(): boolean;
  /** The view that arrived before the first render (handed to Root exactly once at mount). */
  initialView(): ViewState | null;
  /** Root's onReady: receives the live state setters on every render (useState setters are stable). */
  onReady(api: {
    setView: (view: ViewState) => void;
    setError: (message: string) => void;
    setWaiting: (waiting: WaitingState) => void;
  }): void;
  setError(message: string): void;
  setWaiting(waiting: WaitingState): void;
}

function createViewChannel(openai: OpenAiWidgetApi | undefined): ViewChannel {
  let initialView: ViewState | null = null;
  let viewApplied = false;
  let setViewExternal: ((view: ViewState) => void) | null = null;
  let setErrorExternal: ((message: string) => void) | null = null;
  let setWaitingExternal: ((waiting: WaitingState) => void) | null = null;
  return {
    applyView: (view) => {
      viewApplied = true;
      // Save the current view to widgetState (only actually acts on ChatGPT; for remount restore).
      persistView(openai, { spec: view.spec, capability: view.capability });
      if (setViewExternal != null) setViewExternal(view);
      else initialView = view;
    },
    viewApplied: () => viewApplied,
    initialView: () => initialView,
    onReady: (api) => {
      setViewExternal = api.setView;
      setErrorExternal = api.setError;
      setWaitingExternal = api.setWaiting;
    },
    setError: (message) => setErrorExternal?.(message),
    setWaiting: (waiting) => setWaitingExternal?.(waiting),
  };
}

/**
 * Self-recovery orchestration, including cancellation as a terminal state. Owns the recovery flags / backstop timer and the app's
 * tool-result / tool-input / tool-cancelled handlers; bootBridge only wires it and calls start() after render.
 */
function setupRecovery(app: App, views: ViewChannel): { start(): void } {
  // Hold the tool-input (the arguments of the tool the host used to open this widget). Used for the self-recovery re-call.
  let lastToolInput: Record<string, unknown> | undefined;
  // If the user cancels a model-visible tool, treat it as a terminal state. Suppress subsequent self-recovery and
  // prevent resuming the cancelled LLM processing / overwriting the cancellation display. Set to true in ontoolcancelled.
  let cancelled = false;
  // The self-recovery backstop timer after connect. Held so it can be clearTimeout'd on cancellation.
  let recoverTimer: ReturnType<typeof setTimeout> | undefined;

  /**
   * Extracts and applies a Spec from the callServerTool response of tool-result / self-recovery. The
   * extraction itself is host-integration's extractSpecView (shared with kohaku_event's path). On success
   * applyView + sendSizeChanged and return true; otherwise log the reason and return false.
   * source is the caller label for logging ("tool-result" / "self-recovery").
   */
  const applyResultView = (result: unknown, source: string): boolean => {
    const extracted = extractSpecView(result);
    if (!extracted.ok) {
      // On failure, ignore it (a text fallback is shown on the host side). Just log the reason.
      console.log(
        extracted.reason === "missing"
          ? `[kohaku] ignoring ${source}: ${extracted.detail}`
          : `[kohaku] failed to parse spec: ${extracted.detail}`,
      );
      return false;
    }
    const view = extracted.view;
    console.log(
      `[kohaku] applied ${source}: intent=${view.spec.intent.canonical} components=${view.spec.components.length} initialData=${view.initialData?.size ?? 0}`,
    );
    views.applyView(view);
    void app.sendSizeChanged({ height: document.documentElement.scrollHeight + 24 });
    return true;
  };

  app.ontoolresult = (params) => {
    const p = (params ?? {}) as Record<string, unknown>;
    const result = (p as { result?: unknown }).result ?? params;
    const r = (result ?? {}) as {
      structuredContent?: Record<string, unknown>;
      _meta?: Record<string, unknown>;
    };
    // Log the fact of reception unconditionally (to distinguish "the host is not sending" from "it is sending but the shape is different" on real devices).
    console.log(
      `[kohaku] tool-result received (raw): param keys=[${Object.keys(p).join(", ")}]` +
        ` / structuredContent=${
          r.structuredContent != null ? `keys[${Object.keys(r.structuredContent).join(", ")}]` : "none"
        }` +
        ` / _meta=${r._meta != null ? `keys[${Object.keys(r._meta).join(", ")}]` : "none"}`,
    );
    // The extraction of spec/capability and the "ignore" reason log for parse failures is consolidated in applyResultView (shared with self-recovery).
    const applied = applyResultView(result, "tool-result");
    // Claude Desktop strips structuredContent and _meta when forwarding ui/notifications/tool-result and passes only
    // content (callServerTool itself is normal, and the response contains both completely. confirmed on real device 2026-07-15).
    // If a stripped result (= a tool-result that could not be applied) is detected, self-recover immediately without waiting for the 5-second timer.
    // attemptRecovery is guarded by recoveryAttempted / viewApplied / cancelled, so it does not run twice or after cancellation;
    // it does not conflict with the 5-second backstop either, and if already cancelled, calling it returns immediately.
    if (!applied && !views.viewApplied()) void attemptRecovery();
  };

  // For diagnostics / self-recovery, register and hold the tool-input (tool arguments) before connect.
  app.ontoolinput = (params) => {
    lastToolInput = params.arguments;
    console.log(
      `[kohaku] tool-input received: argument keys=[${
        params.arguments != null ? Object.keys(params.arguments).join(", ") : ""
      }]`,
    );
  };

  // If the tool execution is cancelled, display it explicitly (do not silently stay in "waiting…").
  // Treat cancellation as a terminal state. Set the cancelled flag to suppress subsequent self-recovery (attemptRecovery)
  // and stop the backstop timer. Re-calling, via callServerTool, the model-visible tool the user cancelled would resume
  // the cancelled LLM processing and overwrite the cancellation display.
  app.ontoolcancelled = (params) => {
    cancelled = true;
    if (recoverTimer != null) clearTimeout(recoverTimer);
    const reason = params.reason != null ? `(reason: ${params.reason})` : "";
    console.log(`[kohaku] tool-cancelled ${reason}`);
    views.setError(`Tool execution was cancelled. ${reason}`);
  };

  /**
   * Self-recovery (fallback when tool-result does not arrive / is stripped). Re-call once, from the widget, the
   * model-visible tool the host used to open this widget. It starts on two triggers:
   * - immediate: Claude Desktop strips structuredContent/_meta from the tool-result notification (confirmed on real device
   *   2026-07-15. callServerTool itself is normal and the response contains both completely), so when ontoolresult detects
   *   stripping, call it immediately without waiting 5 seconds.
   * - backstop: for the case where no tool-result notification arrives at all (remount, etc.), call it if there is still no
   *   view after RECOVER_AFTER_MS since connect.
   * Double execution is prevented by the recoveryAttempted / viewApplied guards. Furthermore, if the user has already
   * cancelled the tool (cancelled), do not recover as a terminal state (avoid resuming the cancelled LLM processing /
   * overwriting the cancellation display).
   * Purpose: (i) repair the case where the host does not send / strips the tool-result, (ii) field diagnosis of whether callServerTool works.
   * compose-family tools are cached, so re-calling returns the same Spec (same display as the model path).
   * kohaku_render_snapshot is not called (it is an HTML generation tool and does not return a Spec). Calling a model-visible tool
   * from the widget is unrelated to visibility (visibility from the model) and is fine.
   */
  let recoveryAttempted = false;
  const attemptRecovery = async (): Promise<void> => {
    // Only once; unneeded if a view already exists; do not recover if already cancelled.
    if (views.viewApplied() || recoveryAttempted || cancelled) return;
    recoveryAttempted = true;
    const toolName = app.getHostContext()?.toolInfo?.tool?.name;
    // If the tool name cannot be obtained / it is a snapshot generation tool (does not return a Spec), do not recover and go to the diagnostic display.
    const blocked = recoveryBlockReason(toolName);
    if (blocked != null) {
      console.log(`[kohaku] self-recovery not possible: ${blocked}`);
      views.setWaiting({ phase: "diagnostic", recoveryFailed: false });
      return;
    }
    // The arguments are the ones held in tool-input (if absent, try with {} = many kohaku-family intent tools allow omitted arguments).
    const args = lastToolInput ?? {};
    console.log(`[kohaku] attempting self-recovery: tool=${toolName}`);
    views.setWaiting({ phase: "recovering", recoveryFailed: false });
    try {
      const result = await app.callServerTool(
        { name: toolName!, arguments: args },
        { timeout: SERVER_TOOL_TIMEOUT_MS, resetTimeoutOnProgress: false },
      );
      if (views.viewApplied()) return; // if the real tool-result arrived while waiting, do nothing
      if (applyResultView(result, "self-recovery")) {
        console.log("[kohaku] self-recovery succeeded");
      } else {
        console.log("[kohaku] self-recovery failed: cannot extract spec/capability from the response");
        views.setWaiting({ phase: "diagnostic", recoveryFailed: true });
      }
    } catch (e) {
      console.log(`[kohaku] self-recovery failed: ${e instanceof Error ? e.message : String(e)}`);
      views.setWaiting({ phase: "diagnostic", recoveryFailed: true });
    }
  };

  return {
    start: () => {
      // Start self-recovery (bridge only). If there is still no view after RECOVER_AFTER_MS, attempt it once.
      // If already cancelled, attemptRecovery returns immediately via its leading guard. In addition, on
      // cancellation ontoolcancelled clearTimeout's this recoverTimer itself, so this does not fire.
      recoverTimer = setTimeout(() => {
        void attemptRecovery();
      }, RECOVER_AFTER_MS);
    },
  };
}

/** Normal mode: connect to the ext-apps bridge and pass the Spec via tool-result / event. */
async function bootBridge(): Promise<void> {
  // Declare displayMode support (inline / fullscreen) via appCapabilities (MCP Apps standard).
  // pip is assumed host-driven only and is not a toggle target.
  const app = new App(
    { name: "kohaku-renderer", version: "0.1.0" },
    { availableDisplayModes: ["inline", "fullscreen"] },
  );
  // ChatGPT's own widgetState (no standard mechanism); feature-detected and used for remount restore.
  const openai = (globalThis as { openai?: OpenAiWidgetApi }).openai;

  const controller = createBridgeController(app, openai);
  const views = createViewChannel(openai);
  const recovery = setupRecovery(app, views);

  // Remount restore from widgetState (ChatGPT only). Shows the previous view faster than tool-result / self-recovery.
  // initialData is not saved, so data is re-resolved fresh via the bridge. Restore sets viewApplied, so self-recovery
  // (attemptRecovery) is suppressed, and if a later tool-result arrives it overwrites this.
  const restored = readPersistedView(openai);
  if (restored != null) {
    console.log("[kohaku] restored the previous view from widgetState");
    views.applyView({ spec: restored.spec, capability: restored.capability });
  }

  await app.connect();
  const host = app.getHostVersion();
  console.log(
    `[kohaku] connect done: host=${host?.name ?? "unknown"} v${host?.version ?? "unknown"} serverTools=${
      app.getHostCapabilities()?.serverTools != null ? "declared" : "not declared"
    }`,
  );
  createRoot(document.getElementById("root")!).render(
    <StrictMode>
      <Root controller={controller} initialView={views.initialView()} onReady={views.onReady} />
    </StrictMode>,
  );

  recovery.start();
}

const snapshot = readSnapshot();
if (snapshot != null) {
  bootSnapshot(snapshot);
} else {
  await bootBridge();
}
