/**
 * Golden Spec regression test (a bundled demonstration of the scaffold golden).
 *
 * Purpose: pin the "meaningful structure" of input Intent -> generated Spec as a regression. Since fluctuations in
 *   LLM output (provenance / intent.hash / dataVersion / refVersions / component IDs) are absorbed by runGolden's
 *   normalization, only the structure of layout, components, and events is compared.
 *
 * What is pinned: the Spec resulting from composing the L1 Intent `sales.trend` with FakeLlm's scripted responses
 *   (the drafts in golden/*.json). The form after passing through deterministic post-processing (ID normalization, default-props filling, chart-kind rules).
 * What is masked: provenance / intent.hash / dataVersion / refVersions, and positional normalization of component IDs
 *   (c0, c1, …). Even if these remain in the golden, they are ignored in the comparison.
 *
 * Determinism: no LLM is used. drafts are fed to FakeLlm, so CI always produces the same result.
 *
 * How to update goldens (when the UI is changed intentionally):
 *   KOHAKU_GOLDEN_UPDATE=1 pnpm vitest run --project sample-api golden.test
 *   writes each fixture's expected back to the actual compose output; review the git diff and commit.
 *   For a new case, place a {name,input,drafts,expected:null} JSON in golden/ and generate it with the same command.
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { type ComposeContext, type ComposeInput, compose } from "@kohaku-ui/composer";
import { type GoldenCase, runGolden } from "@kohaku-ui/evals";
import { FakeLlm } from "@kohaku-ui/llm/fake";
import type { StoragePort, UISpec } from "@kohaku-ui/spec-core";
import { describe, expect, it } from "vitest";
import { createApp } from "../src/app.js";
import { createHmacAuthzPort } from "../src/ports/authz-port.js";

const GOLDEN_DIR = join(dirname(fileURLToPath(import.meta.url)), "golden");
const UPDATE = process.env["KOHAKU_GOLDEN_UPDATE"] === "1";
// Update mode rewrites goldens instead of asserting them (see the "how to update goldens" note above),
// so it must never run unattended in CI -- a stray/leaked KOHAKU_GOLDEN_UPDATE=1 there would silently
// turn every regression into a new "expected" and report green.
if (UPDATE && process.env["CI"] != null) {
  throw new Error(
    "KOHAKU_GOLDEN_UPDATE=1 must not run in CI (it rewrites goldens instead of asserting them); " +
      "run it locally, review the git diff, and commit",
  );
}

interface GoldenFixture {
  name: string;
  input: ComposeInput;
  /** Raw drafts of the L1 generation schema (FakeLlm's scripted responses). Line up as many as the repair loop needs. */
  drafts: unknown[];
  /** Expected Spec. Auto-generated by the update procedure (initial value is null). */
  expected: UISpec | null;
}

/** In-memory StoragePort (0 fixations, so few-shot is empty and deterministic). */
function makeMemoryStorage(): StoragePort {
  const cache = new Map<string, UISpec>();
  return {
    async getSpecCache(key) {
      return cache.get(key) ?? null;
    },
    async putSpecCache(key, spec) {
      cache.set(key, spec);
    },
    async appendLineage() {},
    async listLineage() {
      return [];
    },
    async getPromotionState() {
      return null;
    },
    async putPromotionState() {},
    async listPromotionStates() {
      return [];
    },
    async getFixation() {
      return null;
    },
    async putFixation() {},
    async listFixations() {
      return [];
    },
  };
}

/** Extract the ComposeContext from the sample API's real wiring. drafts are used as the L1 FakeLlm responses. */
async function makeContext(drafts: unknown[]): Promise<ComposeContext> {
  const llm = new FakeLlm({ objects: drafts });
  const storage = makeMemoryStorage();
  const authz = createHmacAuthzPort("test-secret");
  return (await createApp({ llm, storage, authz })).composeCtx;
}

const files = existsSync(GOLDEN_DIR)
  ? readdirSync(GOLDEN_DIR)
      .filter((f) => f.endsWith(".json"))
      .sort()
  : [];

describe("golden regression (sales.trend L1 generation)", () => {
  if (files.length === 0) {
    it.skip("add a fixture (*.json) to golden/", () => {});
    return;
  }
  for (const file of files) {
    const path = join(GOLDEN_DIR, file);
    const fixture = JSON.parse(readFileSync(path, "utf8")) as GoldenFixture;
    it(UPDATE ? `[UPDATE MODE - NOT ASSERTING] ${fixture.name}` : fixture.name, async () => {
      const ctx = await makeContext(fixture.drafts);
      if (UPDATE) {
        // Update mode: write the actual compose output back as the golden (review the git diff and commit).
        const { spec } = await compose(fixture.input, ctx);
        writeFileSync(path, JSON.stringify({ ...fixture, expected: spec }, null, 2) + "\n");
        return;
      }
      expect(
        fixture.expected,
        `${file}: expected not generated. Run KOHAKU_GOLDEN_UPDATE=1 to generate it`,
      ).not.toBeNull();
      const cases: GoldenCase[] = [{ name: fixture.name, input: fixture.input, expected: fixture.expected! }];
      const report = await runGolden(cases, ctx);
      const failed = report.cases.find((c) => !c.pass);
      expect(
        report.pass,
        failed
          ? `golden mismatch (${file}). expected↓ / actual↓\n${failed.expected}\n---\n${failed.actual}`
          : undefined,
      ).toBe(true);
    });
  }
});
