"""Cross-language golden (Python side).

Checks that the Python implementation reproduces the fixture generated by the TS implementation
(spec/test/fixtures/cross-language-canonical.json). The gatekeeper of canonical-JSON byte compatibility
(= cross-language agreement of intent.hash / specHash). The TS counterpart is spec/test/cross-language.test.ts.
"""

from __future__ import annotations

import asyncio
import json
from typing import Any

import pytest

from kohaku.composer import (
    DEFAULT_KIT_VOCABULARY,
    L2_SYSTEM_PROMPT,
    PROMPT_REVISION,
    DesignSystemGuide,
    design_kit_prompt_fragment,
    design_system_prompt_fragment,
)
from kohaku.evals import export_distillation_dataset
from kohaku.lineage import (
    EvidenceManifest,
    EvidencePackScope,
    build_evidence_pack,
    import_ed25519_private_key_pkcs8,
    import_ed25519_public_key_raw,
    sign_manifest,
    verify_manifest_signature,
)
from kohaku.registry.core import core_catalog
from kohaku.spec import (
    ALLOWED_ATTRS,
    ALLOWED_STYLE_PROPS,
    ALLOWED_TAGS,
    CacheKeyParts,
    FixationRecord,
    IntentInput,
    LineageActor,
    LineageEventRecord,
    LineageFilter,
    LineagePage,
    LineagePageRequest,
    Principal,
    PromotionState,
    action_payload_hash,
    cache_key,
    canonical_stringify,
    compute_intent_hash,
    compute_spec_hash,
    compute_structure_hash,
    decode_seq_cursor,
    encode_seq_cursor,
    find_unsafe_action_param_keys,
    page_lineage_events,
    parse_spec,
    sha256_hex,
    validate_action_params,
    validate_fixation_record,
    validate_promotion_state,
)

from ..conftest import REPO_ROOT


def test_canonical_stringify_and_sha256(cross_language_fixture: dict[str, Any]) -> None:
    for case in cross_language_fixture["canonical"]:
        got = canonical_stringify(case["value"])
        assert got == case["canonical"], f"canonical mismatch for {case['value']!r}"
        assert sha256_hex(got) == case["sha256"]


def test_intent_hash(cross_language_fixture: dict[str, Any]) -> None:
    for case in cross_language_fixture["intents"]:
        got = compute_intent_hash(IntentInput(canonical=case["canonical"], params=case["params"]))
        assert got == case["hash"], f"intent hash mismatch for {case['canonical']}"


def test_spec_and_structure_hash(cross_language_fixture: dict[str, Any]) -> None:
    spec_case = cross_language_fixture["spec"]
    spec = parse_spec(json.loads((REPO_ROOT / spec_case["file"]).read_text(encoding="utf-8")))
    assert compute_spec_hash(spec) == spec_case["specHash"]
    assert compute_structure_hash(spec) == spec_case["structureHash"]


def test_cache_key(cross_language_fixture: dict[str, Any]) -> None:
    """The policyFingerprint 7th component's segment/placeholder format must match TS exactly."""
    for case in cross_language_fixture["cacheKey"]:
        parts = CacheKeyParts(**case["parts"])
        assert cache_key(parts) == case["key"], f"cacheKey mismatch for {case['parts']!r}"


def test_lineage_cursor(cross_language_fixture: dict[str, Any]) -> None:
    """encode_seq_cursor/decode_seq_cursor must reproduce the TS-generated fixture's literal cursor bytes
    (design.md #53) -- the opaque {v,seq} base64url codec is meant to be byte-for-byte shared, not merely
    mutually decodable."""
    for case in cross_language_fixture["lineageCursor"]:
        assert encode_seq_cursor(case["seq"]) == case["cursor"], (
            f"cursor mismatch for seq {case['seq']}"
        )
        assert decode_seq_cursor(case["cursor"]) == case["seq"]


def test_action_params(cross_language_fixture: dict[str, Any]) -> None:
    """validate_action_params / action_payload_hash must reproduce the fixture byte-for-byte
    (design.md #62/#63) -- the exact `issues` array and `sha256:<hex>` payload hash for each
    (schema, payload) pair."""
    for case in cross_language_fixture["actionParams"]:
        issues = validate_action_params(case["schema"], case["payload"])
        got = [{"path": issue.path, "code": issue.code, "message": issue.message} for issue in issues]
        assert got == case["issues"], f"issues mismatch for schema={case['schema']!r} payload={case['payload']!r}"
        assert action_payload_hash(case["payload"]) == case["payloadHash"]


def test_action_payload_scan(cross_language_fixture: dict[str, Any]) -> None:
    """find_unsafe_action_param_keys must reproduce the fixture's whole-payload `__proto__` / `constructor` /
    `prototype` key scan byte-for-byte (design.md #62)."""
    assert cross_language_fixture["actionPayloadScan"]
    for case in cross_language_fixture["actionPayloadScan"]:
        issues = find_unsafe_action_param_keys(case["payload"])
        got = [{"path": issue.path, "code": issue.code, "message": issue.message} for issue in issues]
        assert got == case["issues"], f"scan mismatch for payload={case['payload']!r}"


def test_sandbox_dom_allowlist(cross_language_fixture: dict[str, Any]) -> None:
    """The sandbox DOM allowlist mirror (kohaku.spec.sandbox_dom) must not drift from the TS source."""
    expected = cross_language_fixture["sandboxDom"]
    assert sorted(ALLOWED_TAGS) == expected["tags"]
    assert sorted(ALLOWED_ATTRS) == expected["attrs"]
    assert sorted(ALLOWED_STYLE_PROPS) == expected["styleProps"]


def test_fallback(cross_language_fixture: dict[str, Any]) -> None:
    """Every core-catalog fallback.map_props hand-port (kohaku.registry.core._FALLBACK_MAP_PROPS) must
    reproduce the TS mapProps output byte-for-byte for the same inputProps (see generate-cross-language-
    fixtures.ts's FALLBACK_CASES comment for why this needs a golden rather than a structural check)."""
    catalog = core_catalog()
    by_type = {d.type: d for d in catalog.components}
    for case in cross_language_fixture["fallback"]:
        definition = by_type.get(case["type"])
        assert definition is not None, f'core catalog has no component "{case["type"]}"'
        assert definition.fallback is not None, (
            f'"{case["type"]}" has no fallback in the Python catalog'
        )
        mapped = definition.fallback.map_props(case["inputProps"])
        assert mapped == case["mappedProps"], f'fallback mapProps mismatch for "{case["type"]}"'


def test_export_distillation_dataset(cross_language_fixture: dict[str, Any]) -> None:
    """export_distillation_dataset's JSONL output must be byte-identical to the TS implementation's."""
    spec_case = cross_language_fixture["spec"]
    spec = parse_spec(json.loads((REPO_ROOT / spec_case["file"]).read_text(encoding="utf-8")))
    record = FixationRecord(
        intentHash=spec.intent.hash,
        canonical=spec.intent.canonical,
        structureHash=spec_case["structureHash"],
        pinnedSpec=spec,
        fixatedAt="2026-06-10T03:12:00Z",
        approver=Principal(id="qa-lead"),
        tenant="tenant-acme",
        catalogFingerprint="catalog@2026-06-10",
    )
    # golden=[spec] shares the fixation's intentHash, also pinning the fixation-before-golden tie-break.
    assert (
        export_distillation_dataset([record], [spec])
        == cross_language_fixture["distillation"]["jsonl"]
    )


def test_design_kit_prompt_fragment(cross_language_fixture: dict[str, Any]) -> None:
    """design_kit_prompt_fragment(DEFAULT_KIT_VOCABULARY) must reproduce the TS-generated fixture. Needs no
    separate input in the fixture: both languages already own an identical exported DEFAULT_KIT_VOCABULARY
    constant (itself pinned by this same golden — a divergent constant changes the rendered fragment)."""
    assert (
        design_kit_prompt_fragment(DEFAULT_KIT_VOCABULARY)
        == cross_language_fixture["promptFragments"]["designKit"]
    )


def test_design_system_prompt_fragment(cross_language_fixture: dict[str, Any]) -> None:
    """design_system_prompt_fragment must reproduce the fixture. Unlike the kit vocabulary, the guide is
    not an exported constant on either side (it is a local test fixture), so its input travels in the
    fixture itself rather than being hand-duplicated a third time."""
    case = cross_language_fixture["promptFragments"]["designSystem"]
    guide = DesignSystemGuide(
        tokens=case["guide"]["tokens"], guidelines=case["guide"]["guidelines"]
    )
    assert design_system_prompt_fragment(guide) == case["fragment"]


def test_design_brief_lines(cross_language_fixture: dict[str, Any]) -> None:
    """The design brief inside L2_SYSTEM_PROMPT (its trailing block, from the header line through the end)
    must reproduce the fixture's pinned lines."""
    lines = L2_SYSTEM_PROMPT.split("\n")
    start = lines.index("- Design brief (follow every point):")
    assert lines[start:] == cross_language_fixture["promptFragments"]["designBrief"]


def test_prompt_revision(cross_language_fixture: dict[str, Any]) -> None:
    """Catches an unbumped PROMPT_REVISION drift between the two languages' prompt.py/prompt.ts."""
    assert PROMPT_REVISION == cross_language_fixture["promptFragments"]["promptRevision"]


# --- Compliance Evidence Pack (design.md #67) ---
#
# Lives in its own directory (spec/test/fixtures/evidence-pack/: a store + a manifest + a detached
# signature), not inside cross-language-canonical.json above -- see generate-cross-language-fixtures.ts's
# own comment on why. The TS counterpart is spec/test/cross-language.test.ts's matching describe block.

_ED25519_PKCS8_PREFIX = bytes.fromhex("302e020100300506032b657004220420")
# Same RFC 8032 §7.1 TEST 1 vector packages/lineage/test/evidence-sign.test.ts and
# python/kohaku/tests/lineage/test_evidence.py independently pin (a well-known, publicly verifiable
# vector, not a fixture-specific secret).
_RFC8032_TEST1_SECRET_KEY_SEED = bytes.fromhex(
    "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60"
)
_RFC8032_TEST1_PUBLIC_KEY = bytes.fromhex(
    "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a"
)


def _load_evidence_pack_fixture() -> dict[str, Any]:
    directory = REPO_ROOT / "spec/test/fixtures/evidence-pack"
    return {
        "store": json.loads((directory / "store.json").read_text(encoding="utf-8")),
        "manifest": json.loads((directory / "manifest.json").read_text(encoding="utf-8")),
        "signature": (directory / "manifest.sig").read_text(encoding="utf-8").strip(),
    }


class _StoreEvidenceSource:
    """Reconstructs an EvidenceSource from the fixture's store.json (mirrors the TS golden test's
    `evidenceSourceFromStore`)."""

    def __init__(self, store: dict[str, Any]) -> None:
        self._events = [
            LineageEventRecord(
                id=e["id"],
                ts=e["ts"],
                actor=LineageActor(**e["actor"]),
                type=e["type"],
                payload=e.get("payload", {}),
                tenant=e.get("tenant"),
            )
            for e in store["events"]
        ]
        self._promotions: list[PromotionState] = []
        for raw in store["promotions"]:
            state = validate_promotion_state(raw)
            assert state is not None
            self._promotions.append(state)
        self._fixations: list[FixationRecord] = []
        for raw in store["fixations"]:
            record = validate_fixation_record(raw)
            assert record is not None
            self._fixations.append(record)

    async def list_lineage(self, filter: LineageFilter | None = None) -> list[LineageEventRecord]:
        f = filter or LineageFilter()

        def matches(e: LineageEventRecord) -> bool:
            if f.tenant is not None and e.tenant != f.tenant:
                return False
            if f.since is not None and e.ts < f.since:
                return False
            if f.until is not None and e.ts > f.until:
                return False
            return True

        return [e for e in self._events if matches(e)]

    async def page_lineage(self, req: LineagePageRequest) -> LineagePage:
        return page_lineage_events(self._events, req)

    async def list_promotion_states(self, tenant: str | None = None) -> list[PromotionState]:
        return (
            self._promotions
            if tenant is None
            else [p for p in self._promotions if p.tenant == tenant]
        )

    async def list_fixations(self, tenant: str | None = None) -> list[FixationRecord]:
        return (
            self._fixations
            if tenant is None
            else [f for f in self._fixations if f.tenant == tenant]
        )


def test_evidence_pack_manifest() -> None:
    """build_evidence_pack must reproduce the TS-generated fixture manifest byte-for-byte."""
    fixture = _load_evidence_pack_fixture()
    store = fixture["store"]
    manifest_fixture = EvidenceManifest.model_validate(fixture["manifest"])

    async def run() -> EvidenceManifest:
        pack = await build_evidence_pack(
            source=_StoreEvidenceSource(store),
            scope=EvidencePackScope(
                since=store["scope"]["since"],
                until=store["scope"]["until"],
                tenant=store["scope"].get("tenant"),
            ),
            generator=store["generator"],
            signer=manifest_fixture.signer,
            now=lambda: str(store["generatedAt"]),
        )
        return pack.manifest

    manifest = asyncio.run(run())
    assert manifest.canonical_dict() == manifest_fixture.canonical_dict()
    assert canonical_stringify(manifest.canonical_dict()) == canonical_stringify(
        manifest_fixture.canonical_dict()
    )


def test_evidence_pack_signature() -> None:
    """sign_manifest must reproduce the fixture's signature bytes exactly (Ed25519 is deterministic)."""
    pytest.importorskip("cryptography", reason="the `evidence` optional extra is not installed")
    fixture = _load_evidence_pack_fixture()
    manifest_fixture = EvidenceManifest.model_validate(fixture["manifest"])
    private_key = import_ed25519_private_key_pkcs8(
        _ED25519_PKCS8_PREFIX + _RFC8032_TEST1_SECRET_KEY_SEED
    )
    signature = sign_manifest(manifest_fixture, private_key)
    assert signature == fixture["signature"]


def test_evidence_pack_signature_verifies_against_rfc8032_public_key() -> None:
    pytest.importorskip("cryptography", reason="the `evidence` optional extra is not installed")
    fixture = _load_evidence_pack_fixture()
    manifest_fixture = EvidenceManifest.model_validate(fixture["manifest"])
    public_key = import_ed25519_public_key_raw(_RFC8032_TEST1_PUBLIC_KEY)
    assert verify_manifest_signature(manifest_fixture, fixture["signature"], public_key) is True
