"""Cross-language golden (Python side).

Checks that the Python implementation reproduces the fixture generated by the TS implementation
(spec/test/fixtures/cross-language-canonical.json). The gatekeeper of canonical-JSON byte compatibility
(= cross-language agreement of intent.hash / specHash). The TS counterpart is spec/test/cross-language.test.ts.
"""

from __future__ import annotations

import json
from typing import Any

from kohaku.composer import (
    DEFAULT_KIT_VOCABULARY,
    L2_SYSTEM_PROMPT,
    PROMPT_REVISION,
    DesignSystemGuide,
    design_kit_prompt_fragment,
    design_system_prompt_fragment,
)
from kohaku.evals import export_distillation_dataset
from kohaku.registry.core import core_catalog
from kohaku.spec import (
    ALLOWED_ATTRS,
    ALLOWED_STYLE_PROPS,
    ALLOWED_TAGS,
    CacheKeyParts,
    FixationRecord,
    IntentInput,
    Principal,
    cache_key,
    canonical_stringify,
    compute_intent_hash,
    compute_spec_hash,
    compute_structure_hash,
    parse_spec,
    sha256_hex,
)

from ..conftest import REPO_ROOT


def test_canonical_stringify_and_sha256(cross_language_fixture: dict[str, Any]) -> None:
    for case in cross_language_fixture["canonical"]:
        got = canonical_stringify(case["value"])
        assert got == case["canonical"], f"canonical mismatch for {case['value']!r}"
        assert sha256_hex(got) == case["sha256"]


def test_intent_hash(cross_language_fixture: dict[str, Any]) -> None:
    for case in cross_language_fixture["intents"]:
        got = compute_intent_hash(IntentInput(canonical=case["canonical"], params=case["params"]))
        assert got == case["hash"], f"intent hash mismatch for {case['canonical']}"


def test_spec_and_structure_hash(cross_language_fixture: dict[str, Any]) -> None:
    spec_case = cross_language_fixture["spec"]
    spec = parse_spec(
        json.loads((REPO_ROOT / spec_case["file"]).read_text(encoding="utf-8"))
    )
    assert compute_spec_hash(spec) == spec_case["specHash"]
    assert compute_structure_hash(spec) == spec_case["structureHash"]


def test_cache_key(cross_language_fixture: dict[str, Any]) -> None:
    """The policyFingerprint 7th component's segment/placeholder format must match TS exactly."""
    for case in cross_language_fixture["cacheKey"]:
        parts = CacheKeyParts(**case["parts"])
        assert cache_key(parts) == case["key"], f"cacheKey mismatch for {case['parts']!r}"


def test_sandbox_dom_allowlist(cross_language_fixture: dict[str, Any]) -> None:
    """The sandbox DOM allowlist mirror (kohaku.spec.sandbox_dom) must not drift from the TS source."""
    expected = cross_language_fixture["sandboxDom"]
    assert sorted(ALLOWED_TAGS) == expected["tags"]
    assert sorted(ALLOWED_ATTRS) == expected["attrs"]
    assert sorted(ALLOWED_STYLE_PROPS) == expected["styleProps"]


def test_fallback(cross_language_fixture: dict[str, Any]) -> None:
    """Every core-catalog fallback.map_props hand-port (kohaku.registry.core._FALLBACK_MAP_PROPS) must
    reproduce the TS mapProps output byte-for-byte for the same inputProps (see generate-cross-language-
    fixtures.ts's FALLBACK_CASES comment for why this needs a golden rather than a structural check)."""
    catalog = core_catalog()
    by_type = {d.type: d for d in catalog.components}
    for case in cross_language_fixture["fallback"]:
        definition = by_type.get(case["type"])
        assert definition is not None, f"core catalog has no component \"{case['type']}\""
        assert definition.fallback is not None, f"\"{case['type']}\" has no fallback in the Python catalog"
        mapped = definition.fallback.map_props(case["inputProps"])
        assert mapped == case["mappedProps"], f"fallback mapProps mismatch for \"{case['type']}\""


def test_export_distillation_dataset(cross_language_fixture: dict[str, Any]) -> None:
    """export_distillation_dataset's JSONL output must be byte-identical to the TS implementation's."""
    spec_case = cross_language_fixture["spec"]
    spec = parse_spec(json.loads((REPO_ROOT / spec_case["file"]).read_text(encoding="utf-8")))
    record = FixationRecord(
        intentHash=spec.intent.hash,
        canonical=spec.intent.canonical,
        structureHash=spec_case["structureHash"],
        pinnedSpec=spec,
        fixatedAt="2026-06-10T03:12:00Z",
        approver=Principal(id="qa-lead"),
        tenant="tenant-acme",
        catalogFingerprint="catalog@2026-06-10",
    )
    # golden=[spec] shares the fixation's intentHash, also pinning the fixation-before-golden tie-break.
    assert export_distillation_dataset([record], [spec]) == cross_language_fixture["distillation"]["jsonl"]


def test_design_kit_prompt_fragment(cross_language_fixture: dict[str, Any]) -> None:
    """design_kit_prompt_fragment(DEFAULT_KIT_VOCABULARY) must reproduce the TS-generated fixture. Needs no
    separate input in the fixture: both languages already own an identical exported DEFAULT_KIT_VOCABULARY
    constant (itself pinned by this same golden — a divergent constant changes the rendered fragment)."""
    assert (
        design_kit_prompt_fragment(DEFAULT_KIT_VOCABULARY)
        == cross_language_fixture["promptFragments"]["designKit"]
    )


def test_design_system_prompt_fragment(cross_language_fixture: dict[str, Any]) -> None:
    """design_system_prompt_fragment must reproduce the fixture. Unlike the kit vocabulary, the guide is
    not an exported constant on either side (it is a local test fixture), so its input travels in the
    fixture itself rather than being hand-duplicated a third time."""
    case = cross_language_fixture["promptFragments"]["designSystem"]
    guide = DesignSystemGuide(tokens=case["guide"]["tokens"], guidelines=case["guide"]["guidelines"])
    assert design_system_prompt_fragment(guide) == case["fragment"]


def test_design_brief_lines(cross_language_fixture: dict[str, Any]) -> None:
    """The design brief inside L2_SYSTEM_PROMPT (its trailing block, from the header line through the end)
    must reproduce the fixture's pinned lines."""
    lines = L2_SYSTEM_PROMPT.split("\n")
    start = lines.index("- Design brief (follow every point):")
    assert lines[start:] == cross_language_fixture["promptFragments"]["designBrief"]


def test_prompt_revision(cross_language_fixture: dict[str, Any]) -> None:
    """Catches an unbumped PROMPT_REVISION drift between the two languages' prompt.py/prompt.ts."""
    assert PROMPT_REVISION == cross_language_fixture["promptFragments"]["promptRevision"]
