import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  DEFAULT_KIT_SKELETON,
  DEFAULT_KIT_VOCABULARY,
  designKitPromptFragment,
  L2_SYSTEM_PROMPT,
} from "../src/index.js";
import { buildL2Prompt } from "../src/prompt.js";

/**
 * Cross-language golden of the "Design kit" section, read from the fixture generated by
 * spec/scripts/generate-cross-language-fixtures.ts (spec/test/cross-language.test.ts and Python's
 * test_cross_language_golden.py assert the identical string against the same fixture file —
 * spec/test/fixtures/cross-language-canonical.json's promptFragments.designKit). Regenerate the fixture
 * (and bump PROMPT_REVISION) when the fragment changes; do not hand-edit this constant, and do not
 * hand-copy it into another test — that is exactly the duplication this fixture replaces.
 */
export const EXPECTED_KIT_FRAGMENT: string = (
  JSON.parse(
    readFileSync(
      join(
        dirname(fileURLToPath(import.meta.url)),
        "../../../spec/test/fixtures/cross-language-canonical.json",
      ),
      "utf8",
    ),
  ) as { promptFragments: { designKit: string } }
).promptFragments.designKit;

describe("DEFAULT_KIT_VOCABULARY", () => {
  it("is versioned like renderer-core's defaultDesignKit and lists namespaces for the lint", () => {
    expect(DEFAULT_KIT_VOCABULARY.id).toBe("kohaku");
    expect(DEFAULT_KIT_VOCABULARY.version).toBe("1");
    expect(DEFAULT_KIT_VOCABULARY.namespaces).toContain("k-");
    expect(DEFAULT_KIT_VOCABULARY.namespaces).toContain("gap-");
    expect(DEFAULT_KIT_VOCABULARY.utilities).toContain("grid-cols-3");
    expect(Object.keys(DEFAULT_KIT_VOCABULARY.classes)).toContain("k-card");
  });

  it("the skeleton uses only vocabulary classes and is a body fragment (no <html>, no <script>)", () => {
    const known = new Set([
      ...Object.keys(DEFAULT_KIT_VOCABULARY.classes),
      ...DEFAULT_KIT_VOCABULARY.utilities,
      "is-up",
      "is-down",
    ]);
    for (const m of DEFAULT_KIT_SKELETON.matchAll(/class="([^"]*)"/g)) {
      for (const cls of m[1]!.split(/\s+/).filter((c) => c !== "")) expect(known.has(cls), cls).toBe(true);
    }
    expect(DEFAULT_KIT_SKELETON).not.toContain("<html");
    expect(DEFAULT_KIT_SKELETON).not.toContain("<script");
  });
});

describe("designKitPromptFragment", () => {
  it("emits the cross-language golden", () => {
    expect(designKitPromptFragment(DEFAULT_KIT_VOCABULARY)).toBe(EXPECTED_KIT_FRAGMENT);
  });

  it("a custom kit is rendered with its own id/version, an optional skeleton, and its own classes sorted by name", () => {
    const fragment = designKitPromptFragment({
      id: "acme",
      version: "3",
      classes: { "k-tile": "tile" },
      utilities: ["flex"],
      namespaces: ["k-"],
      skeleton: '<div class="k-tile">x</div>',
    });
    expect(fragment.split("\n")[0]).toBe("## Design kit (acme v3)");
    expect(fragment).toContain("  - k-tile: tile");
    expect(fragment).toContain(
      "- Utilities (exactly these names exist; any other utility name has no effect): flex",
    );
    // Custom skeleton replaces the default one, indented the same way.
    expect(fragment).toContain('  <div class="k-tile">x</div>');
    expect(fragment).not.toContain("Sales by region");
  });

  it("m-15: classes are sorted by name, not Object.entries' insertion order — matters for an integer-like key", () => {
    // JS treats an integer-like key ("2col") specially: Object.keys/entries would sort it *before* every
    // non-numeric key regardless of declaration order, which is exactly the kind of divergence from
    // Python's insertion-order dict iteration this sort exists to close. Declare "zebra" (a normal string
    // key that sorts last) before "2col" and "alpha" (which both sort before it) to prove the fragment
    // does not simply echo declaration order either.
    const fragment = designKitPromptFragment({
      id: "custom",
      version: "1",
      classes: { zebra: "z", "2col": "two columns", alpha: "a" },
      utilities: [],
      namespaces: [],
    });
    const classLines = fragment.split("\n").filter((l) => l.startsWith("  - "));
    expect(classLines).toEqual(["  - 2col: two columns", "  - alpha: a", "  - zebra: z"]);
  });

  it("m-14: an empty classes/utilities/namespaces section is omitted entirely (heading included), not left dangling on a colon", () => {
    const fragment = designKitPromptFragment({
      id: "empty",
      version: "1",
      classes: {},
      utilities: [],
      namespaces: [],
    });
    expect(fragment).not.toContain("Kit classes");
    expect(fragment).not.toContain("Component classes");
    expect(fragment).not.toContain("Utilities (");
    expect(fragment).not.toContain("Reserved prefixes");
    // No line ends with a bare, self-contradicting trailing colon/paren from an emptied-out list.
    for (const line of fragment.split("\n")) {
      expect(line.trimEnd().endsWith(":")).toBe(false);
    }
  });

  it("m-14: without an explicit skeleton, a non-built-in kit gets no Skeleton section at all (never the built-in k-* skeleton)", () => {
    const fragment = designKitPromptFragment({
      id: "empty",
      version: "1",
      classes: {},
      utilities: [],
      namespaces: [],
    });
    expect(fragment).not.toContain("Skeleton of a well-formed widget body");
    expect(fragment).not.toContain("k-card");
    expect(fragment).not.toContain("Sales by region");
  });

  it("m-14: an explicit skeleton is still honored on a kit with otherwise-empty sections", () => {
    const fragment = designKitPromptFragment({
      id: "empty",
      version: "1",
      classes: {},
      utilities: [],
      namespaces: [],
      skeleton: "<div>ok</div>",
    });
    expect(fragment).toContain("Skeleton of a well-formed widget body");
    expect(fragment).toContain("  <div>ok</div>");
  });

  it("m-14: a DEFAULT_KIT_VOCABULARY structural copy (same id/version/classes, not the same object) gets no default skeleton — only the exact constant does", () => {
    // The built-in-skeleton fallback is an identity check (`kit === DEFAULT_KIT_VOCABULARY`), not a
    // structural id/version match — see designKitPromptFragment's own doc for why. A caller that
    // reconstructs an equivalent object (rather than importing and passing the constant itself) gets no
    // skeleton at all, not a silently-reused built-in one.
    const copy = { ...DEFAULT_KIT_VOCABULARY };
    expect(copy).not.toBe(DEFAULT_KIT_VOCABULARY);
    const fragment = designKitPromptFragment(copy);
    expect(fragment).not.toContain("Skeleton of a well-formed widget body");
  });
});

describe("L2 prompt integration", () => {
  const args = {
    intent: { canonical: "sales.custom", params: { request: "test" }, hash: "sha256:" + "0".repeat(64) },
    refs: ["query://sales/custom"],
    shapesByRef: new Map(),
  };

  it("the system prompt ends with the design brief instead of the old 'simple and readable' line", () => {
    expect(L2_SYSTEM_PROMPT).not.toContain("Keep the design simple and readable");
    expect(L2_SYSTEM_PROMPT).toContain("- Design brief (follow every point):");
    expect(L2_SYSTEM_PROMPT.split("\n").at(-1)).toBe(
      "  - never leave browser-default styling on tables, buttons or inputs",
    );
  });

  it("without a kit the Design kit section is absent; with a kit it follows the design-system section", () => {
    expect(buildL2Prompt({ ...args, designSystem: {} })).not.toContain("## Design kit");
    const prompt = buildL2Prompt({ ...args, designSystem: { kit: DEFAULT_KIT_VOCABULARY } });
    const dsAt = prompt.indexOf("## Design system");
    const kitAt = prompt.indexOf("## Design kit");
    // indexOf returns -1 (not found) rather than throwing, so a section that silently vanished from the
    // prompt would still pass `kitAt > dsAt` if dsAt were also -1 — assert both are actually present first.
    expect(dsAt).toBeGreaterThan(-1);
    expect(kitAt).toBeGreaterThan(-1);
    expect(kitAt).toBeGreaterThan(dsAt);
    expect(kitAt).toBeLessThan(prompt.indexOf("## Output language"));
    expect(prompt).toContain(EXPECTED_KIT_FRAGMENT);
  });
});
