import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  DEFAULT_KIT_SKELETON,
  DEFAULT_KIT_VOCABULARY,
  designKitPromptFragment,
  L2_SYSTEM_PROMPT,
} from "../src/index.js";
import { buildL2Prompt } from "../src/prompt.js";

/**
 * Cross-language golden of the "Design kit" section, read from the fixture generated by
 * spec/scripts/generate-cross-language-fixtures.ts (spec/test/cross-language.test.ts and Python's
 * test_cross_language_golden.py assert the identical string against the same fixture file —
 * spec/test/fixtures/cross-language-canonical.json's promptFragments.designKit). Regenerate the fixture
 * (and bump PROMPT_REVISION) when the fragment changes; do not hand-edit this constant, and do not
 * hand-copy it into another test — that is exactly the duplication this fixture replaces.
 */
export const EXPECTED_KIT_FRAGMENT: string = (
  JSON.parse(
    readFileSync(
      join(
        dirname(fileURLToPath(import.meta.url)),
        "../../../spec/test/fixtures/cross-language-canonical.json",
      ),
      "utf8",
    ),
  ) as { promptFragments: { designKit: string } }
).promptFragments.designKit;

describe("DEFAULT_KIT_VOCABULARY", () => {
  it("is versioned like renderer-core's defaultDesignKit and lists namespaces for the lint", () => {
    expect(DEFAULT_KIT_VOCABULARY.id).toBe("kohaku");
    expect(DEFAULT_KIT_VOCABULARY.version).toBe("1");
    expect(DEFAULT_KIT_VOCABULARY.namespaces).toContain("k-");
    expect(DEFAULT_KIT_VOCABULARY.namespaces).toContain("gap-");
    expect(DEFAULT_KIT_VOCABULARY.utilities).toContain("grid-cols-3");
    expect(Object.keys(DEFAULT_KIT_VOCABULARY.classes)).toContain("k-card");
  });

  it("the skeleton uses only vocabulary classes and is a body fragment (no <html>, no <script>)", () => {
    const known = new Set([
      ...Object.keys(DEFAULT_KIT_VOCABULARY.classes),
      ...DEFAULT_KIT_VOCABULARY.utilities,
      "is-up",
      "is-down",
    ]);
    for (const m of DEFAULT_KIT_SKELETON.matchAll(/class="([^"]*)"/g)) {
      for (const cls of m[1]!.split(/\s+/).filter((c) => c !== "")) expect(known.has(cls), cls).toBe(true);
    }
    expect(DEFAULT_KIT_SKELETON).not.toContain("<html");
    expect(DEFAULT_KIT_SKELETON).not.toContain("<script");
  });
});

describe("designKitPromptFragment", () => {
  it("emits the cross-language golden", () => {
    expect(designKitPromptFragment(DEFAULT_KIT_VOCABULARY)).toBe(EXPECTED_KIT_FRAGMENT);
  });

  it("a custom kit is rendered with its own id/version, classes in insertion order, and an optional skeleton", () => {
    const fragment = designKitPromptFragment({
      id: "acme",
      version: "3",
      classes: { "k-tile": "tile" },
      utilities: ["flex"],
      namespaces: ["k-"],
      skeleton: '<div class="k-tile">x</div>',
    });
    expect(fragment.split("\n")[0]).toBe("## Design kit (acme v3)");
    expect(fragment).toContain("  - k-tile: tile");
    expect(fragment).toContain(
      "- Utilities (exactly these names exist; any other utility name has no effect): flex",
    );
    // Custom skeleton replaces the default one, indented the same way.
    expect(fragment).toContain('  <div class="k-tile">x</div>');
    expect(fragment).not.toContain("Sales by region");
  });
});

describe("L2 prompt integration", () => {
  const args = {
    intent: { canonical: "sales.custom", params: { request: "test" }, hash: "sha256:" + "0".repeat(64) },
    refs: ["query://sales/custom"],
    shapesByRef: new Map(),
  };

  it("the system prompt ends with the design brief instead of the old 'simple and readable' line", () => {
    expect(L2_SYSTEM_PROMPT).not.toContain("Keep the design simple and readable");
    expect(L2_SYSTEM_PROMPT).toContain("- Design brief (follow every point):");
    expect(L2_SYSTEM_PROMPT.split("\n").at(-1)).toBe(
      "  - never leave browser-default styling on tables, buttons or inputs",
    );
  });

  it("without a kit the Design kit section is absent; with a kit it follows the design-system section", () => {
    expect(buildL2Prompt({ ...args, designSystem: {} })).not.toContain("## Design kit");
    const prompt = buildL2Prompt({ ...args, designSystem: { kit: DEFAULT_KIT_VOCABULARY } });
    const dsAt = prompt.indexOf("## Design system");
    const kitAt = prompt.indexOf("## Design kit");
    // indexOf returns -1 (not found) rather than throwing, so a section that silently vanished from the
    // prompt would still pass `kitAt > dsAt` if dsAt were also -1 — assert both are actually present first.
    expect(dsAt).toBeGreaterThan(-1);
    expect(kitAt).toBeGreaterThan(-1);
    expect(kitAt).toBeGreaterThan(dsAt);
    expect(kitAt).toBeLessThan(prompt.indexOf("## Output language"));
    expect(prompt).toContain(EXPECTED_KIT_FRAGMENT);
  });
});
