"""Mirror of the TS sandbox DOM allowlist (packages/spec-core/src/schema/sandbox-dom.ts).

Python has no sandbox runtime of its own (the L2 worker/applier is a browser-only concern implemented in
packages/sandbox), so nothing in this codebase actually enforces this allowlist from Python. This module
exists purely so the cross-language golden (spec/test/fixtures/cross-language-canonical.json, generated by
spec/scripts/generate-cross-language-fixtures.ts) can pin that the allowlist itself does not silently drift
between the two languages — see python/kohaku/tests/spec/test_cross_language_golden.py.

Keep this file's constants and predicate functions in lockstep with the TS source; regenerate the fixture and
re-run both languages' golden tests after any change.
"""

from __future__ import annotations

import re

ALLOWED_TAGS: frozenset[str] = frozenset(
    {
        # HTML
        "div",
        "span",
        "p",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "ul",
        "ol",
        "li",
        "table",
        "thead",
        "tbody",
        "tfoot",
        "tr",
        "th",
        "td",
        "caption",
        "strong",
        "em",
        "b",
        "i",
        "small",
        "code",
        "pre",
        "br",
        "hr",
        "button",
        "label",
        "input",
        "select",
        "option",
        "textarea",
        "section",
        "article",
        "header",
        "footer",
        "figure",
        "figcaption",
        # SVG
        "svg",
        "g",
        "path",
        "rect",
        "circle",
        "ellipse",
        "line",
        "polyline",
        "polygon",
        "text",
        "tspan",
        "defs",
        "lineargradient",
        "stop",
        "clippath",
        "title",
    }
)

EXPLICITLY_DENIED_TAGS: frozenset[str] = frozenset(
    {
        "a",
        "img",
        "form",
        "iframe",
        "object",
        "embed",
        "script",
        "style",
        "link",
        "meta",
        "base",
        "template",
        "foreignobject",
        "use",
        "image",
    }
)

VOID_TAGS: frozenset[str] = frozenset({"br", "hr", "input"})

_GLOBAL_ATTRS: frozenset[str] = frozenset({"id", "class", "title", "role", "tabindex", "hidden"})
_INPUT_ATTRS: frozenset[str] = frozenset(
    {
        "type",
        "value",
        "placeholder",
        "disabled",
        "checked",
        "selected",
        "name",
        "min",
        "max",
        "step",
        "rows",
        "cols",
    }
)
_TABLE_ATTRS: frozenset[str] = frozenset({"colspan", "rowspan", "scope"})
_SVG_ATTRS: frozenset[str] = frozenset(
    {
        "d",
        "x",
        "y",
        "x1",
        "y1",
        "x2",
        "y2",
        "cx",
        "cy",
        "r",
        "rx",
        "ry",
        "width",
        "height",
        "points",
        "fill",
        "stroke",
        "stroke-width",
        "stroke-linecap",
        "stroke-linejoin",
        "stroke-dasharray",
        "opacity",
        "fill-opacity",
        "stroke-opacity",
        "transform",
        "viewbox",
        "preserveaspectratio",
        "text-anchor",
        "font-size",
        "font-family",
        "offset",
        "stop-color",
        "stop-opacity",
        "gradientunits",
        "gradienttransform",
        "clip-path",
    }
)

ALLOWED_ATTRS: frozenset[str] = frozenset(_GLOBAL_ATTRS | _INPUT_ATTRS | _TABLE_ATTRS | _SVG_ATTRS)
ALLOWED_ATTR_PREFIXES: tuple[str, ...] = ("aria-", "data-")

ALWAYS_DENIED_ATTRS: frozenset[str] = frozenset(
    {
        "href",
        "xlink:href",
        "src",
        "srcdoc",
        "srcset",
        "action",
        "formaction",
        "ping",
        "target",
        "download",
        "is",
        "style",
    }
)

ALLOWED_PROPERTY_OPS: frozenset[str] = frozenset(
    {"value", "checked", "disabled", "selected", "scrollTop", "scrollLeft", "hidden", "indeterminate"}
)

ALLOWED_STYLE_PROPS: frozenset[str] = frozenset(
    {
        "display",
        "position",
        "top",
        "right",
        "bottom",
        "left",
        "width",
        "height",
        "min-width",
        "min-height",
        "max-width",
        "max-height",
        "margin",
        "margin-top",
        "margin-right",
        "margin-bottom",
        "margin-left",
        "padding",
        "padding-top",
        "padding-right",
        "padding-bottom",
        "padding-left",
        "box-sizing",
        "box-shadow",
        "aspect-ratio",
        "flex",
        "flex-direction",
        "flex-wrap",
        "flex-grow",
        "flex-shrink",
        "flex-basis",
        "justify-content",
        "align-items",
        "align-content",
        "align-self",
        "order",
        "gap",
        "row-gap",
        "column-gap",
        "grid-template-columns",
        "grid-template-rows",
        "grid-column",
        "grid-row",
        "grid-auto-flow",
        "grid-gap",
        "font-family",
        "font-size",
        "font-weight",
        "font-style",
        "line-height",
        "letter-spacing",
        "text-align",
        "text-decoration",
        "text-transform",
        "text-overflow",
        "white-space",
        "word-break",
        "word-wrap",
        "vertical-align",
        "color",
        "background",
        "background-color",
        "background-image",
        "background-size",
        "background-position",
        "background-repeat",
        "opacity",
        "fill",
        "stroke",
        "stroke-width",
        "border",
        "border-width",
        "border-style",
        "border-color",
        "border-radius",
        "border-top",
        "border-right",
        "border-bottom",
        "border-left",
        "border-collapse",
        "border-spacing",
        "outline",
        "outline-color",
        "outline-width",
        "outline-style",
        "transform",
        "transform-origin",
        "transition",
        "transition-property",
        "transition-duration",
        "transition-timing-function",
        "overflow",
        "overflow-x",
        "overflow-y",
        "cursor",
        "visibility",
        "z-index",
        "list-style",
        "list-style-type",
        "table-layout",
    }
)

_UPPER_RE = re.compile(r"[A-Z]")
_JAVASCRIPT_SCHEME_RE = re.compile(r"javascript\s*:", re.IGNORECASE)
_URL_RE = re.compile(r"url\(\s*['\"]?([^'\")]*)['\"]?\s*\)", re.IGNORECASE)

DEFAULT_MAX_DOM_NODES = 20_000
DEFAULT_MAX_DOM_DEPTH = 64
DEFAULT_MUTATIONS_PER_MINUTE = 6000


def to_kebab_case(prop: str) -> str:
    return _UPPER_RE.sub(lambda m: f"-{m.group(0).lower()}", prop)


def is_tag_allowed(tag: str) -> bool:
    return tag.lower() in ALLOWED_TAGS


def contains_javascript_scheme(value: str) -> bool:
    return _JAVASCRIPT_SCHEME_RE.search(value) is not None


def is_attr_allowed(name: str) -> bool:
    lower = name.lower()
    if lower in ALWAYS_DENIED_ATTRS or lower.startswith("on"):
        return False
    if any(lower.startswith(p) for p in ALLOWED_ATTR_PREFIXES):
        return True
    return lower in ALLOWED_ATTRS


def is_attr_value_safe(value: str) -> bool:
    return not contains_javascript_scheme(value)


def is_style_prop_allowed(prop: str) -> bool:
    return to_kebab_case(prop).lower() in ALLOWED_STYLE_PROPS


def is_style_value_safe(value: str) -> bool:
    lower = value.lower()
    if "expression(" in lower or "@import" in lower:
        return False
    for m in _URL_RE.finditer(lower):
        if not m.group(1).startswith("#"):
            return False
    return True
