import type { SalesSeedInput } from "@kohaku-ui-sample/api/browser";

/**
 * A small handwritten seed for the playground — not the real demo data (`apps/sample-api/src/domain/seed/`,
 * generated by `pnpm seed` and read from disk by `readSeedFromDisk`, which this browser host never
 * reaches). u5-3 records the ReplayLlm fixtures against a fixed dataset and a fixed clock
 * (`create-host.ts`'s `PLAYGROUND_NOW`); this is a placeholder large enough to exercise every core Intent
 * with non-empty results, to be replaced (or extended) once that recording happens.
 */
export const PLAYGROUND_SEED: SalesSeedInput = {
  products: [
    { id: "p1", name: "Sonic Widget", category: "hardware", unitPrice: 4200 },
    { id: "p2", name: "Cloud Ledger", category: "software", unitPrice: 9800 },
    { id: "p3", name: "Onboarding Care", category: "services", unitPrice: 30000 },
  ],
  records: [
    {
      id: "r1",
      fiscalYear: 2026,
      quarter: 1,
      month: "2026-04",
      region: "japan",
      productId: "p1",
      channel: "direct",
      units: 120,
      revenue: 504_000,
    },
    {
      id: "r2",
      fiscalYear: 2026,
      quarter: 1,
      month: "2026-05",
      region: "north_america",
      productId: "p2",
      channel: "online",
      units: 40,
      revenue: 392_000,
    },
    {
      id: "r3",
      fiscalYear: 2026,
      quarter: 2,
      month: "2026-07",
      region: "europe",
      productId: "p3",
      channel: "partner",
      units: 10,
      revenue: 300_000,
    },
    {
      id: "r4",
      fiscalYear: 2026,
      quarter: 2,
      month: "2026-08",
      region: "japan",
      productId: "p2",
      channel: "direct",
      units: 25,
      revenue: 245_000,
    },
    {
      id: "r5",
      fiscalYear: 2026,
      quarter: 3,
      month: "2026-10",
      region: "apac",
      productId: "p1",
      channel: "online",
      units: 80,
      revenue: 336_000,
    },
    {
      id: "r6",
      fiscalYear: 2026,
      quarter: 3,
      month: "2026-11",
      region: "north_america",
      productId: "p3",
      channel: "partner",
      units: 5,
      revenue: 150_000,
    },
  ],
  targets: [
    { fiscalYear: 2026, quarter: 1, region: "japan", targetRevenue: 450_000 },
    { fiscalYear: 2026, quarter: 1, region: "north_america", targetRevenue: 350_000 },
    { fiscalYear: 2026, quarter: 2, region: "europe", targetRevenue: 280_000 },
    { fiscalYear: 2026, quarter: 2, region: "japan", targetRevenue: 220_000 },
    { fiscalYear: 2026, quarter: 3, region: "apac", targetRevenue: 300_000 },
    { fiscalYear: 2026, quarter: 3, region: "north_america", targetRevenue: 140_000 },
  ],
  seedTag: "playground-demo-seed-v1",
};
