/** Embedded template for scaffold ports */
export const PORTS_TEMPLATE = `import type { DomainPort } from "@kohaku-ui/spec-core";

/**
 * The one Port every product still writes by hand: how "query://<source>/<op>" reads and action.invoke
 * writes actually reach your data. createKohakuHost() (see server.ts) already supplies working defaults
 * for the other three Ports (storage, authz, the LLM-backed SemanticPort built from intents.ts) -- replace
 * those only once your product outgrows them (see @kohaku-ui/host's README).
 */
export const domainPort: DomainPort = {
  // TODO: enumerate your real operations (the op in query://<source>/<op>; include write actions invoked
  // via action.invoke too -- hosts restrict issued capability write scopes to the names listed here) and
  // implement invoke to actually read/write your data instead of throwing.
  async listOperations() {
    return [{ name: "example", description: "sample operation" }];
  },
  async invoke(op) {
    throw new Error(\`unknown operation: \${op}\`);
  },
};
`;

/** Embedded template for scaffold ports: the Intent catalog backing createKohakuHost's default SemanticPort. */
export const INTENTS_TEMPLATE = `import { defineIntent, type IntentBuilder } from "@kohaku-ui/intents";
import { z } from "zod";

// TODO: replace with your own Intent(s) -- canonical name, params (zod), and how they map to queries (each
// query's path must be one of domainPort.listOperations()'s names in ports.ts).
export const intents: IntentBuilder[] = [
  defineIntent({
    canonical: "example.summary",
    description: "Example view (replace with your own Intent)",
    source: "example",
    params: z.object({}),
    examples: ["show the example view"],
    queries: [{ path: "example" }],
  }),
];
`;

export const SERVER_TEMPLATE = `// Dependencies this file needs in your app's package.json: "hono", "@hono/node-server", "tsx",
// and the @kohaku-ui/* packages imported below (npm install @kohaku-ui/host @kohaku-ui/llm
// @ai-sdk/anthropic zod — @ai-sdk/anthropic is the provider SDK for Claude, an optional peer dependency
// of @kohaku-ui/llm; swap it for @ai-sdk/openai / @ai-sdk/google / @ai-sdk/openai-compatible depending on
// the provider you configure — see docs/user-guide.md §6 Step 0). Building this inside the kohaku monorepo
// itself instead of a standalone app? Depend on them via "workspace:*" there instead.
import { serve } from "@hono/node-server";
import { createKohakuHost } from "@kohaku-ui/host";
import { createLlmFromEnv } from "@kohaku-ui/llm";
import { intents } from "./intents.js";
import { domainPort } from "./ports.js";

const { app } = createKohakuHost({
  domain: domainPort,
  querySource: "example", // must match ports.ts / intents.ts's source name
  llm: createLlmFromEnv(),
  intents: intents.map((i) => i.toIntentDef()),
  dataVersion: () => "example@v1", // bump this whenever the underlying data changes
});

serve({ fetch: app.fetch, port: 8787 }, (info) =>
  console.log(\`kohaku host: http://localhost:\${info.port}\`),
);
`;

/** The Golden regression test scaffold generated by scaffold golden */
export const GOLDEN_TEST_TEMPLATE = `/**
 * Golden Spec regression test (generated by kohaku scaffold golden).
 *
 * Purpose: freeze the "meaningful structure" of input Intent → generated Spec as a regression. The jitter
 *   in LLM output (provenance / intent.hash / dataVersion / refVersions / component IDs) is absorbed by
 *   runGolden's normalization, so only the layout / component / event structure is compared.
 *
 * Determinism: no LLM is used. Each fixture's drafts (the raw drafts of the L1 generation schema) are given
 *   as FakeLlm's scripted responses, so the result is always the same in CI.
 *
 * Adding a fixture: just drop a JSON of the following shape under golden/ (no code changes needed):
 *   {
 *     "name": "case name",
 *     "input": { "kind": "intent", "intent": { "canonical": "...", "params": { ... } } },
 *     "drafts": [ <raw L1-generated drafts. multiple allowed to reproduce the repair loop> ],
 *     "expected": null
 *   }
 *   Do not hand-write expected; auto-generate it with the update procedure below.
 *
 * Updating golden (when you intentionally change the UI):
 *   KOHAKU_GOLDEN_UPDATE=1 <the command that runs this test>
 *   writes each fixture's expected back from the actual compose output; review the git diff and
 *   commit. The update is deterministic (no LLM needed).
 */
import { compose, type ComposeContext, type ComposeInput } from "@kohaku-ui/composer";
import { runGolden, type GoldenCase } from "@kohaku-ui/evals";
import { FakeLlm } from "@kohaku-ui/llm/fake";
import type { UISpec } from "@kohaku-ui/spec-core";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const GOLDEN_DIR = join(dirname(fileURLToPath(import.meta.url)), "golden");
const UPDATE = process.env["KOHAKU_GOLDEN_UPDATE"] === "1";

interface GoldenFixture {
  name: string;
  input: ComposeInput;
  /** Raw drafts of the L1 generation schema (FakeLlm's scripted responses). List as many as the repair loop needs. */
  drafts: unknown[];
  /** The expected Spec. Auto-generated by the update procedure (initial value is null). */
  expected: UISpec | null;
}

/**
 * TODO: wire up and return the product's ComposeContext. drafts is used for the FakeLlm response of L1 generation.
 * For a concrete example, see apps/sample-api/test/golden.test.ts in the kohaku repository.
 */
function makeContext(drafts: unknown[]): ComposeContext {
  const llm = new FakeLlm({ objects: drafts });
  throw new Error(\`TODO: implement makeContext (wire up llm=\${llm.provider})\`);
}

const files = existsSync(GOLDEN_DIR)
  ? readdirSync(GOLDEN_DIR)
      .filter((f) => f.endsWith(".json"))
      .sort()
  : [];

describe("golden regression", () => {
  if (files.length === 0) {
    it.skip("add fixtures (*.json) under golden/", () => {});
    return;
  }
  for (const file of files) {
    const path = join(GOLDEN_DIR, file);
    const fixture = JSON.parse(readFileSync(path, "utf8")) as GoldenFixture;
    it(fixture.name, async () => {
      const ctx = makeContext(fixture.drafts);
      if (UPDATE) {
        // Update mode: write the actual compose output back as the golden (review the git diff and commit).
        const { spec } = await compose(fixture.input, ctx);
        writeFileSync(path, JSON.stringify({ ...fixture, expected: spec }, null, 2) + "\\n");
        return;
      }
      expect(
        fixture.expected,
        \`\${file}: expected not generated. Generate it with KOHAKU_GOLDEN_UPDATE=1\`,
      ).not.toBeNull();
      const cases: GoldenCase[] = [
        { name: fixture.name, input: fixture.input, expected: fixture.expected! },
      ];
      const report = await runGolden(cases, ctx);
      const failed = report.cases.find((c) => !c.pass);
      expect(
        report.pass,
        failed ? \`golden mismatch (\${file}). expected↓ / actual↓\\n\${failed.expected}\\n---\\n\${failed.actual}\` : undefined,
      ).toBe(true);
    });
  }
});
`;

/** Placed directly under golden/ by scaffold golden: an explanation of the fixture format and update procedure */
export const GOLDEN_README_TEMPLATE = `# golden fixtures

The \`*.json\` files in this directory are the inputs of the Golden Spec regression. 1 file = 1 case.

## Format

\\\`\\\`\\\`json
{
  "name": "case name (becomes the test title)",
  "input": { "kind": "intent", "intent": { "canonical": "sales.trend", "params": {} } },
  "drafts": [ /* raw drafts of the L1 generation schema (FakeLlm's scripted responses) */ ],
  "expected": null
}
\\\`\\\`\\\`

- \`drafts\`: the "raw" drafts of L1 generation (an object containing the components/events arrays). To
  reproduce the repair loop, list several in the order failing draft → successful draft.
- \`expected\`: the expected Spec. **Do not hand-write it.** Auto-generate it with the update procedure below.

## Generating / updating expected

When you intentionally change the UI (or add a new case), write expected back in update mode:

\\\`\\\`\\\`bash
KOHAKU_GOLDEN_UPDATE=1 <the command that runs golden.test>
\\\`\\\`\\\`

Review the git diff of the written-back \`expected\` and commit it if it is as intended. Generation is deterministic and needs no LLM.

## What is masked in the comparison

runGolden masks provenance / intent.hash / dataVersion / refVersions and normalizes component IDs to
position-based ones (c0, c1, …) for comparison. These values are ignored even if left in expected.
`;
